### ISSUE TITLE
Feature request: maintainer name?

### ISSUE THREAD

**Issue by elboulangero** [repology/repology-updater#1005]
Hi,

Here's my use-case: I'm the developer of an application named "goodvibes", and I want to credit the maintainers who package my application. This can be seen here: https://goodvibes.readthedocs.io/en/latest/credits.html#package-maintainers

So, how can I automatically retrieve the names of the maintainers of the goodvibes package? I thought repology would be the best answer, however repology only gives me the email addresses of the maintainers.

```
$ wget https://repology.org/api/v1/project/goodvibes -O- | jq . | grep maintainers -A 2

    "maintainers": [
      "orphan@voidlinux.org"
    ],
--
    "maintainers": [
      "milouse@aur"
    ],
--
...
```

So that doesn't work for me.

Do you think having the maintainer names as well would be a useful addition to repology?

**Comment by AMDmi3** [comment]
There's nowhere to parse maintainer names from. Only a few repositories provide information beyond email, and using that won't change much.

**Comment by AMDmi3** [comment]
Btw, orphaned@voidlinux.org means that it doesn't have a maintainer there.

**Comment by elboulangero** [comment]
> There's nowhere to parse maintainer names from. Only a few repositories provide information beyond email, and using that won't change much.

Debian has a field `Maintainer` in the control file, although it can be either the name of a person or the name of a team.

For Fedora, I ended up parsing the changelog part of the spec file to get the maintainer name, not great but it works. Similar trick for openSuse.

Archlinux might have a `# Maintainer: ` comment at the beginning of the PKGBUILD, although it's only a convention.

> Btw, orphaned@voidlinux.org means that it doesn't have a maintainer there.

Ah OK, I thought it was nick :sweat_smile: ... Thanks for the clarification!

**Comment by elboulangero** [comment]
(note that in my comment above, I refer to fetching files from the source packages, while your answer hints that repology queries repositories instead, which would make sense given the name of the project)

**Comment by AMDmi3** [comment]
Repology doesn't parse spec changelogs and PKGBUILDS. Parsing these would be unnecessary complicated for the small gain and still won't solve a task of having maintainer name information.

**Comment by elboulangero** [comment]
Ack, thanks for the clarification!
