### ISSUE TITLE
centos repos don't get updated

### ISSUE THREAD

**Issue by kilobyte** [repology/repology-updater#1012]
The data Repology shows for Centos is really outdated.  Looking at the [data source](https://github.com/repology/repology-updater/blob/master/repos.d/rpm/centos.yaml) I see that the URLs there are either:
* pointing at historic snapshots (http://vault.centos.org/centos/8/), or
* dead and pointing at a domain squatter (http://centos-packages.com/8/)

For example, a package that I was looking at this time (ndctl) for Centos 8 is at version 62 in [the historic vault](http://vault.centos.org/centos/8/BaseOS/Source/SPackages/) and Repology yet 65 on [live mirrors](http://mirror.centos.org/centos-8/8/BaseOS/x86_64/os/Packages/).  The headers atop of both pages are pretty descriptive.

**Comment by AMDmi3** [comment]
Please point to an actual location of source packages. Vault is the only I've seen so far, mirror.centos.org does not seem to contain source packages.

**Comment by AMDmi3** [comment]
Timeout, no action required
