### ISSUE TITLE
Asciidoc badges

### ISSUE THREAD

**Issue by Foadsf** [repology/repology-updater#1023]
the MarkDown:

     [![Packaging status](https://repology.org/badge/vertical-allrepos/<packageName>.svg)](https://repology.org/project/<packageName>/versions)

for Asciidoc is 

    image::https://repology.org/badge/vertical-allrepos/<packageName>.svg["Packaging status", link=https://repology.org/project/<packageName>/versions]

**Comment by AMDmi3** [comment]
I don't plan to clutter the badges page with the code for all the formats. There's enough information to adapt it for any of them.
