### ISSUE TITLE
Add SystemRescueCD linux recovery distro

### ISSUE THREAD

**Issue by PartialVolume** [repology/repology-updater#1031]
Add the recovery distro SystemRescueCD

Latest package list here http://www.system-rescue-cd.org/Detailed-packages-list/

**Comment by AMDmi3** [comment]
Does not met basic requirements https://repology.org/addrepo

**Comment by PartialVolume** [comment]
I'm assuming that's because the version numbers have been appended to, i.e. upstream, the program nwipe uses 0.28 etc for version where systemRescueCD has mmodified it to 0.28-1 ? Am I correct or are there other issues ?

**Comment by AMDmi3** [comment]
Versions numbers are OK and can be handled just like Arch.
The real issue is lack of information on base package (e.g. `llvm` for `llvm-libs`) and no homepage information needed to disambiguate unrelated packages. Also HTML format, but I could overlook it this time.
