### ISSUE TITLE
Is this SSL incomplete chain error valid?

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-updater#1041]
re: adacontrol package
Repology identifies this issue for many days:
Homepage link "https://www.adalog.fr/en/adacontrol.html" is dead (SSL incomplete certificate chain) for more than a month.

However, Chrome is happy with it.  It says the certificate is valid and the site is secure.
Is there any tool that I can use to verify this "incomplete certificate chain"?  I'm wondering if this is a false positive because I would think chrome would flag this site if it really had a certificate chain issue.

**Comment by AMDmi3** [comment]
This is not a false positive, and in fact quite common issue. You can check it on, for instance, https://www.ssllabs.com/ssltest/analyze.html?d=www.adalog.fr (_This server's certificate chain is incomplete. Grade capped to B_ and _Chain issues: Incomplete_). This usually doesn't show up in big browsers as they bundle _Let's Encrypt Authority X3_ certificate, but will hit you in any other place where it's inaccessible:

```
% fetch -o/dev/null https://www.adalog.fr
Certificate verification failed for /CN=adalog.fr
34370547712:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
fetch: https://www.adalog.fr: Authentication error
% curl https://www.adalog.fr
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
% wget https://www.adalog.fr
--2020-05-11 20:39:23--  https://www.adalog.fr/
Resolving www.adalog.fr (www.adalog.fr)... 95.142.174.86
Connecting to www.adalog.fr (www.adalog.fr)|95.142.174.86|:443... connected.
ERROR: cannot verify www.adalog.fr's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Unable to locally verify the issuer's authority.
To connect to www.adalog.fr insecurely, use `--no-check-certificate'.
```

In fact I didn't expect these to fail as I have `ca_root_nss` with `ETCSYMLINK` option installed, which should contain the named certificate and make it available to ssl-using apps, but it seems to not be the case. Well, the better it demonstrates the issue - without complete certificate chain provided by the server, SSL connections to it will fail unless the intermediate certificates are available from some other source, which is not guaranteed at all.

**Comment by jrmarino** [comment]
okay, good to know.
Since I actually know the adacontrol author personally, I will let him know with much of this information.  So is the recommendation from his point of view to buy any cert from a more reputable issuer?  I'm just trying to think of an answer if his question is "what should I do about it?"

**Comment by jrmarino** [comment]
found a fix:
https://notsomany.com/2018/07/25/servers-certificate-chain-is-incomplete-grade-capped-to-b/

"Concatenate the certificate file with the Intermediate CA."

**Comment by jrmarino** [comment]
I sent an email to adalog.fr.  
Closing the issue.

**Comment by AMDmi3** [comment]
> "Concatenate the certificate file with the Intermediate CA."

Usually no extra action is required to setup the chain correctly. Honestly I don't even know how people introduce this kind of misconfiguration.

In my case certbot produces `fullchain.pem` and `privkey.pem`, I add these to nginx config as `ssl_certificate` and `ssl_certificate_key` correspondingly, everything works.

**Comment by jrmarino** [comment]
Just curious: about how many days does it take the error to clear?  The author of adacontrol said he got his site fixed and that was several days ago.

**Comment by AMDmi3** [comment]
Links are rechecked once per 5-9 days, as long as the queue is not clogged by huge amount of new links which is often the case lately. I'll force recheck for this domain now.

**Comment by AMDmi3** [comment]
Although all 4 adalog.fr urls were already rechecked and are reporting OKs, or are you referring to different host?

**Comment by AMDmi3** [comment]
Oh, I see now - the problem has not disappeared. This is broken as link status change does not trigger project update. Forced the update for adacontrol, added repology/repology-updater#1053

**Comment by jrmarino** [comment]
cool, thanks.  Glad I asked!
