### ISSUE TITLE
Fedora maintainers information missed

### ISSUE THREAD

**Issue by Vascom** [repology/repology-updater#1048]
Hi.
Can you add information about Fedora maintainers, please?

**Comment by AMDmi3** [comment]
There's no such info in repository data we get from fedora, there's only `<packager>Fedora Project</packager>`

**Comment by Vascom** [comment]
But this information available in pagure.
Do you use information only from repo?

**Comment by AMDmi3** [comment]
Yes. If there are alternative machine readable sources, please provide links.

**Comment by Vascom** [comment]
You can get it via pagure API.
For example look at this https://pagure.io/releng/blob/master/f/scripts/find_unblocked_orphans.py near lines 154-179.

**Comment by AMDmi3** [comment]
Ready to use data which can be accessed with a single HTTP request is needed, which contains at least the same data as repository.

**Comment by Vascom** [comment]
Can we talk in russian?

**Comment by AMDmi3** [comment]
It's a public place, so English is strongly preferred.

**Comment by xfgusta** [comment]
Hey @AMDmi3,

What about adding `packagename-maintainers@fedoraproject.org`, which is an official email alias to contact maintainers and co-maintainers [1], to all packages? For instance, for the `asciinema` package it would be `asciinema-maintainers@fedoraproject.org` [2]. Currently the "Maintainer(s)" column for Fedora is empty [3].

[1]: https://fedoraproject.org/wiki/EmailAliases#Package_maintainers_email_aliases
[2]: https://packages.fedoraproject.org/pkgs/asciinema/asciinema/
[3]: https://repology.org/project/asciinema/versions#fedora_rawhide

**Comment by AMDmi3** [comment]
The purpose of tracking maintainers in repology is to provide each person/team with statistics, feeds and other information limited only by packages these parties are responsible for. Per-package aliases have no use for that purpose.

**Comment by xfgusta** [comment]
I see, I hadn't considered this. Thanks for the reply.
