### ISSUE TITLE
Add package details link for Fedora/EPEL

### ISSUE THREAD

**Issue by sbraz** [repology/repology-updater#1051]
Hi,
I think that all Fedora/EPEL packages have some kind of home page at `https://src.fedoraproject.org/rpms/<pkg name>`, for example https://src.fedoraproject.org/rpms/firefox.

Would it be possible to add a link to this?

@Vascom I know you maintain quite a few packages for Fedora (including mine :smile:), what do you think of adding this?

**Comment by Vascom** [comment]
I am welcome any improvement.

**Comment by AMDmi3** [comment]
There's already such a link for Fedora. Adding for EPEL as well.

**Comment by sbraz** [comment]
Oh you're right, I think I only noticed EPEL because it was the first in alphabetical order!
