### ISSUE TITLE
extract_maintainers doesn't work for CRUX

### ISSUE THREAD

**Issue by TimB87** [repology/repology-updater#1054]
Hi!
I wish my python skills were better so I could fix that myself, but time currently permits me to dig deeper into it.

From my understanding, extract_maintainers function doesn't work with the crux way of declaring Maintainers in Pkgfiles (example: [dash Pkgfile](https://crux.nu/gitweb/?p=ports/core.git;a=blob;f=dash/Pkgfile;h=c2e616b99900b59cc5970cb9d4e431cba8c8f04d;hb=HEAD)):
`# Maintainer: (first name) name, email at host dot tld`

Is it easily possibly to get this going?

**Comment by AMDmi3** [comment]
By using non-obfuscated emails in CRUX, yes.
In Repology - no, we purposely do not and will not deobfuscate emails.

**Comment by TimB87** [comment]
@AMDmi3 I'll close the issue as is as there is nothing to be done then (not my decision, not sure how the CRUX team feels about that either).

Anyway, thanks for the quick reply and repology as a whole! 👍

**Comment by AMDmi3** [comment]
Couple of additional thoughts:
- I don't think CRUX team would force you to obfuscate _your_ email if you don't want to
- At some point, CRUX parsing in Repology would anyway have to either be switched from parsing Pkgfiles as plaintext (incomplete and unreliable) to parsing some kind of machine readable dump of package metadata produced on CRUX side, or be removed. When/if such a dump is implemented, emails can be converted to readable form in the process of generating it (probably on opt-in basis per maintainer). Ataraxia linux uses package format similar to CRUX and have developed a way to generate such a dump (#913), which probably can be reused for CRUX. Just telling if you or someone else from CRUX community would be interesting in keeping/improving Repology support in future.

**Comment by TimB87** [comment]
Thanks for the valuable input!
In the long term I would prefer to keep repology going for us as well, so just unobfuscating my mails would solve anything. I'll try and talk to people and see what we can get going here!

**Comment by AMDmi3** [comment]
Still closing as there's nothing to do here on Repology side.
