### ISSUE TITLE
How to get a copy of the database?

### ISSUE THREAD

**Issue by jtrakk** [repology/repology-updater#1057]
Hello, I like looking at the repology website, and I am interested in running some queries on the repology database myself. How can I generate or download a copy of the database?

**Comment by Atemu** [comment]
Might also want to consider ZSTD, it's a competitor to Brotli.

**Comment by AMDmi3** [comment]
DNS issues were fixed, dumps.repology.org is now fully usable.

**Comment by AMDmi3** [comment]
> Might also want to consider ZSTD, it's a competitor to Brotli.

Right, I've forgot about it. It's even more effective than brotli on our case and medium compression level:

```
COMPRESSOR      SIZE    TIME
  brotli.1   612.7MB   23.94
    zstd.1   521.6MB   16.92
    zstd.2   521.0MB   19.62
  brotli.2   490.5MB   43.59
    zstd.3   488.9MB   22.05
    zstd.4   487.5MB   22.85
  brotli.3   474.1MB   50.84
    zstd.5   463.3MB   40.68
  brotli.4   449.3MB   64.20
    zstd.6   428.9MB   58.66
    zstd.7   416.0MB   67.35
  brotli.5   402.6MB  122.27
    zstd.8   400.4MB   85.02
    zstd.9   397.0MB   95.54
   zstd.10   391.6MB  128.16
  brotli.6   388.1MB  167.90
   zstd.11   383.1MB  158.93
   zstd.12   379.3MB  225.00
   zstd.13   374.7MB  321.89
  brotli.7   372.2MB  288.47
   zstd.14   371.3MB  467.97
```
Will switch to it for dumps.
