### ISSUE TITLE
Request: equip API with information as to whether a package is PRE-installed on a distro

### ISSUE THREAD

**Issue by MagnusBrzenk** [repology/repology-updater#1059]
I'm interested to know what distros have tmux PRE-installed (not just installable). 

According to [this comment](https://github.com/repology/repology-webapp/issues/139#issuecomment-646682896), that piece of information is not available in the API. Would it be possible to add it? Thanks.

**Comment by AMDmi3** [comment]
What is the point of this duplicate issue?
I've already explained it: none of known repositories provides such information, so this is not possible.
