### ISSUE TITLE
Request to add RebornOS repository

### ISSUE THREAD

**Issue by damian101** [repology/repology-updater#1068]
I use [RebornOS](https://rebornos.org) as my main distro for almost two years now and would really like to see its repository on repology.org. It is an Arch Linux derivative and was originally an Antergos fork, and it still uses the Cnchi installer which will be replaced with the new Fenix installer when it's ready. RebornOS has gotten its own repository with the discontinuation of Antergos, before that it used the Antergos repository.
The RebornOS repository is located here: [https://repo.rebornos.org/RebornOS](https://repo.rebornos.org/RebornOS)

**Comment by AMDmi3** [comment]
Repository host is down, subject for removal.

https://repology.org/log/4774240

**Comment by damian101** [comment]
@AMDmi3 
There were some issues with expired SSL certificates. The RebornOS repository is now hosted on OSDN:
https://mirrors.dotsrc.org/osdn/storage/g/r/re/rebornos/repo/RebornOS/
