### ISSUE TITLE
homebrew-livecheck data sources

### ISSUE THREAD

**Issue by davidak** [repology/repology-updater#1070]
brew has different functions to get the latest version from different data sources

https://github.com/Homebrew/homebrew-livecheck/tree/master/livecheck/livecheck_strategy

Can you use them as inspiration to implement missing data sources?

**Comment by AMDmi3** [comment]
This doesn't bring anything new. GitHub already suggested in #1 and #938, npm in #649, pypi in #278, hackage already supported, and other smaller sites won't be supported.
