### ISSUE TITLE
Parser for SWORD Project module pages

### ISSUE THREAD

**Issue by mkszuba** [repology/repology-updater#1076]
It would be nice for Repology to support the SWORD Project (https://crosswire.org/sword/index.jsp). To my knowledge they do not presently have a JSON endpoint, that said their module pages are well-structured so it is possible to extract all the relevant information from there. Attaching the Python script I use to gather this information for the purpose of updating Gentoo ebuilds of SWORD modules, I reckon it shouldn't be too difficult to make it into something compatible with Repology.
[sword_module_metadata.txt](https://github.com/repology/repology-updater/files/5219128/sword_module_metadata.txt)

**Comment by AMDmi3** [comment]
We're absolutely not parsing any HTML

**Comment by mkszuba** [comment]
Okay, I'll check with them then.

**Comment by mkszuba** [comment]
Relevant request to upstream: http://tracker.crosswire.org/projects/SWEB/issues/SWEB-16

**Comment by AMDmi3** [comment]
Timeout
