### ISSUE TITLE
KaOS does not provide homepage information in a way accessible by Repology?

### ISSUE THREAD

**Issue by demmm** [repology/repology-updater#1083]
When opening https://repology.org/repository/kaos, the banner states that KaOS is subject to removal if home url & download options are not provided correctly.
Looking at https://github.com/repology/repology-updater/blob/master/repos.d/kaos.yaml
it seems all needed info is there (though https://github.com/repology/repology-updater/blob/master/repos.d/kaos.yaml#L16, line 22 , line 43 & line 46 are no longer correct, packageviewer is completely rewritten in GO and on a different server: https://kaosx.us/packages/index.php)

What extra or different info is needed to have the home url correct?
Is the download link on each package page not accessible? Example:
https://kaosx.us/packages/view.php?repo=apps&name=ack-3.4.0-1

Thanks for any info, corrections will be done as soon as it is clear what is missing.

**Comment by AMDmi3** [comment]
That referred to information on upstream homepages, I've added a clarification. In fact, KaOS support is generally deficient as we have to reside to HTML parsing, and that HTML only provides package names and versions - that's far below Repology requirements. Proper machine readable (json) dump or API would solve this.

**Comment by demmm** [comment]
The packageviewer uses json files to parse the output, we'll adjust [pmanager](https://github.com/KaOSx/pmanager) so there will be https://kaosx.us/packages/repology.js that you can parse.
Expect this to be up in 1-2 weeks.

**Comment by AMDmi3** [comment]
> Regular .db files have always been up, if that would usable:

Sure it would, I might've missed it when kaos support had been added back in 2017 (#323).

I'll try to switch to .db files in a few days.

**Comment by demmm** [comment]
In https://github.com/repology/repology-updater/issues/323, link should have been http://kaosx.tk/repo/ not http://kaosx.tk/packages/....
Sorry that I never knew about it (when KaOS was added, or who submitted it).

**Comment by demmm** [comment]
API option added, so you can use that if that works easier:
https://kaosx.us/packages/api.php

**Comment by AMDmi3** [comment]
> API option added, so you can use that if that works easier:

Thanks, but I'd prefer .db for now - it contains all needed info (btw, API seems to lack an analogue of `%BASE%` attribute which allows to tie source and binary packages), it's ground truth since it's repository index, and it allows to reuse already existing arch parser. Deploying switch to .db now.

**Comment by AMDmi3** [comment]
Fixed now, thanks!

**Comment by AMDmi3** [comment]
I also plan to add kde-next as a separate repo. Does this make sense? Is `KaOS KDE-next` the right name?

**Comment by demmm** [comment]
Yes, kde-next is in use most of the time, better name would be all lowercase for repo imo, KaOS kde-next.
