### ISSUE TITLE
Cygwin tzcode showing as dropped rather than updated

### ISSUE THREAD

**Issue by BrianInglis** [repology/repology-updater#1088]
[Cygwin tzcode](https://repology.org/maintainer/brian.inglis%40cygwin/feed-for-repo/cygwin) showing as dropped rather than updated

**Comment by AMDmi3** [comment]
It was merged to tzdata. I've noticed that it produces strangely looking log entries, but there's no solution to that yet.

**Comment by BrianInglis** [comment]
They derive from different source tarballs with differing contents, and tzcode is not released if there are no diffs from the tzcode sources in the previous release. 
Docs tz-art.html, tz-how-to.html, and tz-link.html are only in tzcode, so it will be released if those change, although I believe they are mostly associated with the rules in the data, although downstream package links and language bindings are in tz-link.html. 
I would split all those files into a separate docs package but do not know how to meaningfully name such perhaps tzdocs but nothing similar exists in any other distro.

**Comment by AMDmi3** [comment]
They come from the single code base, which is also available and used in some repos as a whole, so it would be incorrect and impossible to split these.
