### ISSUE TITLE
Request to add RuckZuck repository

### ISSUE THREAD

**Issue by damian101** [repology/repology-updater#1089]
https://ruckzuck.tools/Home/Repository

**Comment by AMDmi3** [comment]
Need a proper machine readable package metadata dump with compatible package names, see https://repology.org/addrepo for details

**Comment by AMDmi3** [comment]
You haven't mentioned that there's an [API](https://github.com/rzander/ruckzuck/wiki/REST-API), it's usable for accessing data.
However, there are no compatible names. `ShortName` field is close, but it may contain garbage which is not related to product name, such as versions, branches and architecture. Also there's no information on downloads so there's no way to verify versions.
I'm thinking on adding ruckzuck support in a pessimized way, ignoring unmatched packages (35%) and newest versions.  

@rzander you may be interested.

**Comment by rzander** [comment]
1) Use https://cdn.ruckzuck.tools/rest/v2/GetCatalog to get the Catalog (Summary of all latest versions in RuckZuck)
2) then use e.g. https://cdn.ruckzuck.tools/rest/v2/GetSoftwares?shortname=teams to get the package details

The **ProductName**, **Version** and **Manufacturer** in RuckZuck does match with the AddRemovePrograms entries in Windows (Registry). The **shortname** is a common name to access the latest version of a package. It can happen that the **shortname** contains major version like  **.NET35** (Version 3.5 of .NET) or specific variations of a package e.g. **7-Zip(MSI)**

A Package definition can contain multiple packages (e.g. https://cdn.ruckzuck.tools/rest/v2/GetSoftwares?shortname=adobereader%20dc , it includes the full installation and an update package) for different languages, architectures or other special cases...

**Comment by AMDmi3** [comment]
Unfortunately I'm not going to perform a HTTP request per each package. In fact, it doesn't provide any extra usable info, for example looking at Firefox I see that URL is a script instead of an URL. But I can at least see what's going on with openvpn (it's in fact openvpn-connect) or python (just incorrect version). Aren't there per-package web packages with similar info?

**Comment by rzander** [comment]
What's wrong with python ? it's exact the version as it has:
![image](https://user-images.githubusercontent.com/11909453/101942781-5aff5100-3bea-11eb-862f-7a41c84989c3.png)

**Comment by AMDmi3** [comment]
The version is `3.9.1`, I have no idea what `3.9.1150.0` is.
