### ISSUE TITLE
Add package metadata (YACP)

### ISSUE THREAD

**Issue by fd00** [repology/repology-updater#1093]
https://repology.org/repository/yacp
> This repository does not provide package homepage information in a way accessible by Repology. This is critical, because homepages are used to resolve project name conflicts, e.g. to distinguish similarly named packages of unrelated projects. Because of that, this repository is subject for removal in the near future.
> 
> See documentation for a best way to make package metadata accessible for Repology.

Would you crawl https://yacp.osdn.jp/packages.json.xz to update YACP package metadata?

- metadata generated by my ruby script ( https://github.com/fd00/kelger )
- update daily by cron

**Comment by AMDmi3** [comment]
Sure, it would be great. I've found some problems with data though:

- a bogus empty entry between `sassc` and `sbpl`:
```json
    {
      "name": "sassc",
      "version": "3.6.1",
      "category": [
        "Web"
      ],
      "summary": "Wrapper around libsass",
      "homepage": "https://github.com/sass/sassc",
      "subpackages": [
        {
          "name": "sassc",
          "category": [
            "Web"
          ]
        }
      ],
      "maintainers": [
        "Daisuke Fujimura"
      ]
    },
    {},
    {
      "name": "sbpl",
```

Some missing or broken version suffixes (note that these cases weren't correctly handled by repology before, but I guess now is the chance to finally do it right):
```
-cmake-modules-webos-1.0.0 rc6
+cmake-modules-webos 1.0.0c6
-cmyktool-0.1.6 pre1
+cmyktool 0.1.6
-hisat-0.1.6 beta
+hisat 0.1.6
-libcircle-0.2.1 rc1
+libcircle 0.2.1c.1
-libstorj-2.0.0 beta
-libstree-0.4.3 pre2
+libstorj 2.0.0
+libstree 0.4.3
-msdl-1.2.7 r2
+msdl 1.2.7
-octetos-biblion-0.1.1 alpha
-octetos-core-2.5.0 alpha
-octetos-coreutils-0.7.0 alpha
+octetos-biblion 0.1.1
+octetos-core 2.5.0
+octetos-coreutils 0.7.0
-protobuf-c-text-1.0.0 rc1
+protobuf-c-text 1.0.0c1
```

Broken python package names:
```
+python36os-genmsg 0.5.16
+python36osdep 0.19.0
+python36osinstall 0.7.8
+python36ospkg 1.2.8
+python36osunit 1.15.6
```

And one more breakage, it seems like the problem is that `-r` is just eaten everywhere:
```
-vc2-reference 0.1.0.2
+vc2eference 0.1.0.2
```

**Comment by AMDmi3** [comment]
Also there are two URLs which contain unicode byte order marks which mess up the parsing:

```% head -1 libbubblemon/*cygport | head -1 | hexdump -C
00000000  48 4f 4d 45 50 41 47 45  3d 22 ef bb bf 68 74 74  |HOMEPAGE="...htt|
00000010  70 3a 2f 2f 77 77 77 2e  6e 6f 6e 67 6e 75 2e 6f  |p://www.nongnu.o|
00000020  72 67 2f 24 7b 50 4e 7d  2f 22 0a                 |rg/${PN}/".|
0000002b
% head -1 libaffa/*cygport | head -1 | hexdump -C
00000000  48 4f 4d 45 50 41 47 45  3d 22 ef bb bf 68 74 74  |HOMEPAGE="...htt|
00000010  70 3a 2f 2f 77 77 77 2e  6e 6f 6e 67 6e 75 2e 6f  |p://www.nongnu.o|
00000020  72 67 2f 24 7b 50 4e 7d  2f 22 0a                 |rg/${PN}/".|
0000002b
```

**Comment by fd00** [comment]
Sorry. I will fix it as soon as I can.

**Comment by fd00** [comment]
I fixed script and regenerated packages.json.xz
- https://github.com/fd00/kelger/commit/533a200e3df37dd7264003351b071b0c7db008d2

**Comment by AMDmi3** [comment]
Deployed, thanks!
