### ISSUE TITLE
kiss-games: issue with git submodules

### ISSUE THREAD

**Issue by sdsddsd1** [repology/repology-updater#1099]
Hello,
the repology-updater has an issue updating https://github.com/sdsddsd1/kiss-games since I added https://github.com/sdsddsd1/kiss-games/tree/master/equipment/qt5-script which is basically linked to a git submodule in the root directory. 
I did this for convenience to not maintain these packages myself since another KISS related project is already doing so. When there is no fix found with a reasonable effort I can just delete it again.
Greetings.
Edit: I have just found https://github.com/repology/repology-updater/pull/1038. I will probably just remove the submodules then again.

**Comment by AMDmi3** [comment]
Is any action required on repology side?

**Comment by sdsddsd1** [comment]
Nope. I have just reverted my changes.
