### ISSUE TITLE
Multiple levels of outdatedness

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#11]
E.g. darker red color

**Comment by waldyrious** [comment]
A color scale (i.e. varying in hue, not just in brightness) would be nice. Something like [viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html), for example?

Also, is the plan to have the color be based on date, or number of versions?

**Comment by AMDmi3** [comment]
> A color scale (i.e. varying in hue, not just in brightness) would be nice. Something like viridis, for example?

Not sure, since it may intersect with other colors(we'll need a few ones for new states, such as legacy (I've planned yellow) and unstable (purple or a variant between green and cyan, as an in-between to "unique" and "latest" states).

> Also, is the plan to have the color be based on date, or number of versions?

For the start it will definitely be an index in a list of sorted versions. This may still be tricky as there could be multiple branches (e.g. postgresql 9.4, 9.5, 9.6), but still doable.

Using dates is an interesting idea, but I'm not sure if it has benefits over versions.
- We need to accumulate at least several months of chronological data
- The inner workings would become more complex, as we'll need to fetch chronological data in addition to package data we already have
- It's unreliable, as when a repository is added, some intermediate version never seen before may pop out. Which date should it be associated with?
- Color coded dates are not too visual.
  - There may be a huge time gap between versions, but the changes may still be minor - this will have huge difference in color, which does not correspond to reality
  - There may be a critical fix released right after the previous version. There will be no difference in color, but the update is important

So, I'd stay with version numbers, but I'd put it another way:
- Should it only take into account version numbers visible to repology, or
- Should it remember all seen versions ever seen and also use these?

E.g. if the actual repos contain versions `1.0`, `1.7`, `1.8`, while there's also `1.1`, `1.3`, `1.6` which were visible in the past and `1.2`, `1.4`, `1.5` which repology has never seen, what should it do?

Anyway, the first version of this feature will have the simplest possible inplementation: in each branch, the number of versions from the latest one will determine the color, and there will be like 5 fixed levels.

I need to note that Repology tries to be compatible with strict HTTP Content Security Policy which does not allow inline styles, so all colors should be fixed in CSS.

**Comment by AMDmi3** [comment]
For now I have something like this in mind:

![colors](https://user-images.githubusercontent.com/474217/29921538-a00cd024-8e5a-11e7-8908-a5571f6a2f84.png)

**Comment by waldyrious** [comment]
>> A color scale (i.e. varying in hue, not just in brightness) would be nice. Something like viridis, for example?
>
> Not sure, since it may intersect with other colors(we'll need a few ones for new states, such as legacy (I've planned yellow) and unstable (purple or a variant between green and cyan, as an in-between to "unique" and "latest" states).

Understood, that makes sense.

As for the dates, I see your point. Going backwards from the latest version is indeed a good heuristic for a first approximation. Eventually, it would be nice to have all the relevant bits of information --type of version (major, minor, patch), date, number of versions, etc.-- used as weights to calculate a combined outdateness score, but going step by step is a good strategy indeed.
