### ISSUE TITLE
Please add AIX Toolbox repository

### ISSUE THREAD

**Issue by sanket-rathi** [repology/repology-updater#1101]
Hi,
We have an open source packages repository for AIX. 
The packages are ported for AIX in rpm format and are maintained for updates and security vulnerabilities.
We are also keep adding new packages to repository.
The repository supports yum as well.
Here is the information 
Name : AIX Toolbox
Website : https://www.ibm.com/support/pages/aix-toolbox-linux-applications-overview
Repositories : 
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/noarch/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-6.1/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-7.2/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-7.1/

All of the above repositories have repodata directory.

The source RPMs are in following location
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/SRPMS/

Kindly let me know if any more information is needed.

**Comment by AMDmi3** [comment]
@sanket-rathi it looks like repodata for SRPMS had not beed updated since 2017. This needs to be fixed for repology to see actual repository state.

**Comment by sanket-rathi** [comment]
Thank you. Will update SRPM repodata. But until then can we add RPM repositories and will add SRPM later ?

**Comment by sanket-rathi** [comment]
Oh.. I see you have added the repository yaml file. Sorry for earlier message. But looks like it is using AIX toolbox homepage URL. Can we use RPMS repodata to fetch. Then it can fetch all version and more packages I think.

**Comment by AMDmi3** [comment]
> But looks like it is using AIX toolbox homepage URL.

Is this not correct?

> Can we use RPMS repodata to fetch

Repology works with source packages.

**Comment by sanket-rathi** [comment]
The home page URL is correct but we also have repositories with RPM database in repodata format. Will that be not better ? 

https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/noarch/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-6.1/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-7.2/
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-7.1/

**Comment by AMDmi3** [comment]
Like I've said, Repology works with source packages.
