### ISSUE TITLE
Homebrew disabled status not respected

### ISSUE THREAD

**Issue by SMillerDev** [repology/repology-updater#1103]
https://repology.org/project/osquery/versions shows homebrew's osquery as outdated, and while this is true. Users can't even install osquery from Homebrew. 

https://formulae.brew.sh/formula/osquery shows that it's disabled in the title, and in https://formulae.brew.sh/api/formula/osquery.json `jq '$.disabled'` will be true.

**Comment by AMDmi3** [comment]
Not sure why we should respect it. As long as a formula is not removed, I don't see it different from masked package in gentoo, or BROKEN port in FreeBSD or just any implicitly broken package in AUR which a user cannot install either. However the formula is there, it may be undisabled manually by anybody, is outdated/vulnerable properties still apply.

**Comment by SMillerDev** [comment]
Thanks for the reply, I'm not sure I follow the logic though
> it may be undisabled manually by anybody

This is true to the same extend that any package can be manually downgraded by anyone, that would make the outdated status inapplicable.

**Comment by AMDmi3** [comment]
I have no idea how downgrading a package under homebrew works. The point is that the repository still contains and provides a formula.
