### ISSUE TITLE
Funtoo have wrong url

### ISSUE THREAD

**Issue by tczaude** [repology/repology-updater#1107]
Funtoo repo ask github which is not mainstreem and not update provided wrong info

Correct updated repository is on code.funtoo.org in example

https://code.funtoo.org/bitbucket/scm/auto/browser-kit.git

with specific branch

**Comment by AMDmi3** [comment]
It cannot be fixed by dumb replacement of github urls to code.funtoo.org - for instance there's no gnome-kit on code.gentoo.org. Please submit a pull request with proper changes.
