### ISSUE TITLE
Python packages quantiphy-eval and rkm-codes listead as unique in Alpine

### ISSUE THREAD

**Issue by adhawkins** [repology/repology-updater#1116]
These packages are on PyPi, but my new Alpine packages are showing up as the only ones. Can these be matched up manually somehow so that it picks up changes via PyPi?

**Comment by adhawkins** [comment]
Ah ok, that makes sense. Will monitor those two packages. Thanks

**Comment by AMDmi3** [comment]
Both fixed now.
