### ISSUE TITLE
New distribution: openmamba

### ISSUE THREAD

**Issue by mambasoft** [repology/repology-updater#1119]
Hi,
I'm doing tests to integrate repology-updater into the openmamba distribution maintainance processes.

The attached repos.d file [openmamba.yaml.txt](https://github.com/repology/repology-updater/files/5903939/openmamba.yaml.txt) is currently working fine and if you'd like it could eventually be integrated upstream.

The initial problem I'm trying to sort out is the mapping of 'python-*' and 'perl-*' to 'python:*' and 'perl:*' package effnames. I've been searching in rules.d to see how this is done with the oher distros but I haven't found the extact rules which do this. I think that in my case a simple rule that just converts any e.g. 'python-*' source name to 'python:*' could be fine with few or no exceptions to handle. Do you have any suggestion on how to do this?

Thanks for developing this project and for any feedback!

**Comment by AMDmi3** [comment]
Looks usable, I'm working on adding this. Although it will require a handful of rules (which may be added eventually) to merge versioned packages such as `x264-{116,120,144,148}` and added `lib` prefixes.

> I think that in my case a simple rule that just converts any e.g. 'python-' source name to 'python:' could be fine with few or no exceptions to handle. Do you have any suggestion on how to do this?

Yes, it's done here:
https://github.com/repology/repology-rules/blob/master/500.wildcard.yaml#L121

I'm adding such rules for perl, python, ruby and haskell, not sure for java as we don't have wildcard rules for other repos yet, but openmamba seem to have strong naming policy so this should would probably work too.

A couple of questions:
- Does the config you've attached have complete subrepository list? I.e. it only lists 6 subrepos, but there are 16 devel-* repos at http://cdn.openmamba.org/pub/openmamba/
- I'm going to add per-package links to `https://openmamba.org/it/pacchetti/?tag={subrepo}&pkg={name}.source`, however some of these pages are empty, for example https://openmamba.org/it/pacchetti/?tag=devel&pkg=hunspell-xh.source The same link is shown in https://openmamba.org/en/packages/?tag=devel&pkg=_index, so there seem to be some sort of breakage.
- I'm going to name (`desc` field) it just `openmamba`, as the rest seem to be excessive and needlessly long which would blow up badges and tables on the site. Is this OK? Would adding more openmamba repos (milestones?) make sense? If so, it would be better to use something like `openmamba_rolling`/`openmamba rolling` as name/desc right away to avoid need to rename later. If no, I'd go with `openmamba`/`openmamba`.

**Comment by mambasoft** [comment]
> Looks usable, I'm working on adding this. Although it will require a handful of rules (which may be added eventually) to merge versioned packages such as `x264-{116,120,144,148}` and added `lib` prefixes.

Good!
Versioned packages usually get the soname or version appended with no spaces (e.g. libboost172, libwebp6), x264 is an exception because the base name ends with a number. A basic list of other packages aliases is [here](http://hetzner3.mambasoft.it/pub/openmamba/devel-autodist/autoupdate/aliases).
 
> > I think that in my case a simple rule that just converts any e.g. 'python-' source name to 'python:' could be fine with few or no exceptions to handle. Do you have any suggestion on how to do this?
> 
> Yes, it's done here:
> https://github.com/repology/repology-rules/blob/master/500.wildcard.yaml#L121

Ok, so I suppose it's just a matter of adding _openmamba_ to the list.

> I'm adding such rules for perl, python, ruby and haskell, not sure for java as we don't have wildcard rules for other repos yet, but openmamba seem to have strong naming policy so this should would probably work too.

That's fine. I may eventually suggest any missing conversion rule that I will find.

> A couple of questions:
> 
> * Does the config you've attached have complete subrepository list? I.e. it only lists 6 subrepos, but there are 16 devel-* repos at http://cdn.openmamba.org/pub/openmamba/

Yes, the list I've provided includes all the currently used repositories, the others are obsolete and will probably be removed in future.

> * I'm going to add per-package links to `https://openmamba.org/it/pacchetti/?tag={subrepo}&pkg={name}.source`, however some of these pages are empty, for example https://openmamba.org/it/pacchetti/?tag=devel&pkg=hunspell-xh.source The same link is shown in https://openmamba.org/en/packages/?tag=devel&pkg=_index, so there seem to be some sort of breakage.

The link mask is correct, the problem is on our side and I will check for it.

> * I'm going to name (`desc` field) it just `openmamba`, as the rest seem to be excessive and needlessly long which would blow up badges and tables on the site. Is this OK? Would adding more openmamba repos (milestones?) make sense? If so, it would be better to use something like `openmamba_rolling`/`openmamba rolling` as name/desc right away to avoid need to rename later. If no, I'd go with `openmamba`/`openmamba`.

It's ok. openmamba has currently only a single rolling release, milestones are many years old and would not care about them (they don't even have repodata info).

**Comment by AMDmi3** [comment]
Done!

**Comment by mambasoft** [comment]
> > Versioned packages usually get the soname or version appended with no spaces
> 
> The problem is not stripping the suffix, but knowing which packages need suffix stripped. I don't currently see a way to know that, so manual rules would need to be added.

I see and that's not a big problem unless they cause some disorder in repology.org. Most of those packages are there as temporary legacy and are no longer useful when all dependant packages are rebuilt with the current release. For sake of completeness there is a [file in the repository] http://cdn.openmamba.org/pub/openmamba/devel/legacy) which is just used, as needed, as a ignore list by the automated update processes. 

> Anyway, the repository is now on Repology, enjoy!

Thanks a lot, I've seen the updated site with openmamba and that's great!

I've just a question and sorry if there is another issue for this: It would be great if I could use the information from the
[outdated packages page](https://repology.org/projects/?inrepo=openmamba&outdated=1) to have a list of packages and the newest version to update them to. As far as I can see the only way would be to scrape all those pages (also considering that they are paginated to 200 entries per page). Is there maybe an undocumented machine parsable file or can this be a reasonable TODO request? If not, do you mind if I scrape those pages, say, once a day?

Thanks again!

**Comment by AMDmi3** [comment]
> I see and that's not a big problem unless they cause some disorder in repology.org

It's not a problem for repology, but it interferes with consistent representation of openmamba on repology. E.g. it'll show a bit more projects than there actually are, and won't be able to report CVEs for legacy packages. On one hand, it won't hurt to add rules as they may be useful for other repositories with the same naming schemes, on another these rules use regular expressions which slow down the update process. Anyway, if you're OK with how openmamba looks on repology these are my problems.

> As far as I can see the only way would be to scrape all those pages

There's documented [API](https://repology.org/api), though it's clumsy, returning a lot of data which requires additional processing for the sake of universality, and requiring pagination handling as well. [The view](https://repology.org/api/v1/projects/?inrepo=openmamba&outdated=1) corresponding to the page you've given. I'm fine if you use either API or scrape the site as long as you keep the rate acceptably low (<1RPS). There's also not yet deployed Repology [service](https://github.com/repology/repology-exports) for custom exports we can use to generate the lightweight and ready to use dumps regularly.

**Comment by mambasoft** [comment]
> There's documented [API](https://repology.org/api), though it's clumsy, returning a lot of data which requires additional processing for the sake of universality, and requiring pagination handling as well. [The view](https://repology.org/api/v1/projects/?inrepo=openmamba&outdated=1) corresponding to the page you've given. I'm fine if you use either API or scrape the site as long as you keep the rate acceptably low (<1RPS). There's also not yet deployed Repology [service](https://github.com/repology/repology-exports) for custom exports we can use to generate the lightweight and ready to use dumps regularly.

Oh, sorry for missing this. The API is just what I need, used with some simple parsing code.
Soon I will add the link to repology.org at the bottom of openmamba.org website and announce it to our users.
Thanks again!

**Comment by AMDmi3** [comment]
You're welcome!
