### ISSUE TITLE
Log viewer: failed parse for LiGurOS develop

### ISSUE THREAD

**Issue by palica** [repology/repology-updater#1124]
Hi,

I am having hard time debugging the root cause of the failed update for develop on liguros.

here is the log 

https://repology.org/log/5568778
```
2021-02-17 23:06:29 parsing started
2021-02-17 23:06:29 parsing source liguros-repo started
2021-02-17 23:06:53 ERROR: ParseError: mismatched tag: line 15, column 17
```
Do you have any idea why would this be failing? Could the error log be more verbose?

Thanks in advance

**Comment by AMDmi3** [comment]
No idea, looks like XML problem somewhere and it's already fixed.
I've updated gentoo parser (a79022f) to track which package exceptions are thrown from.

**Comment by palica** [comment]
thanks
