### ISSUE TITLE
Artix repository

### ISSUE THREAD

**Issue by svdm-artix** [repology/repology-updater#1125]
Could the artix repository please be added? Packages are available here: https://archive.artixlinux.org/.

Artix linux is an arch linux fork without systemd.

Thanks for reading, I would really appreciate it.

Edit: maybe https://github.com/artix-linux/packages could be used instead? It includes pkgbuilds.

**Comment by AMDmi3** [comment]
Which repositories (as in "directories which contain *.db file") are enabled by default in the distribution? Are there multiple flavors as in stable/devel?

**Comment by svdm-artix** [comment]
By default system, world and galaxy are enabled. There aren't multiple flavors as in stable/devel, though there are testing repo's (gremlins) that are disabled by default.
