### ISSUE TITLE
Add Meson WrapDB

### ISSUE THREAD

**Issue by dreamer** [repology/repology-updater#1138]
https://wrapdb.mesonbuild.com/
https://mesonbuild.com/Using-wraptool.html

It's a repository of libraries that can be used as fallback dependencies for C/C++ projects using Meson buildsystem, if library is not available via native repo. It's kind-of similar to crates.io or pypi in purpose, except it's designed to complement native OS repositories instead of replacing them.

**Comment by AMDmi3** [comment]
This does not meet our requirements to new repositories as it's not fetchable as a single file (needs to fetch `projects`, then fetch `projects/{project}` for each project, then `projects/{project}/{version}/{revision}/get_wrap` to get useful info. 

@legeana, it looks you're related to wrapdb, you might be interested. We could support wrapdb in repology so it could report outdated and vulnerable versions for packages in wrapdb (FYI my test run shows 63% packages outdated and 15% vulnerable), and announce wrapdb support for projects as well.

For that it would be nice to have a machine readable dump of all info from wrapdb. Of what I see in wrapdb, repology would need `name`, `version`, `revision`, `source_url` fields.

**Comment by AMDmi3** [comment]
Timeout
