### ISSUE TITLE
CRAN parser getting fooled by bad data (multiple rows)

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-updater#1140]
the cran parser looks at:
https://cran.r-project.org/web/checks/check_summary_by_package.html

The main information is inside a table,  The first column is labeled "packages".  I believe every package is supposed to have a unique name.  However, in a few cases, the package name is duplicated and it appears by mistake.  One example of this is abjutils.  Another is xts.  Let me show this graphically:
![cran-xts](https://user-images.githubusercontent.com/1125622/113138535-86369c00-91eb-11eb-9484-abf54e6f4629.png)

In both cases (abjutils and xts) all columns are empty in one row save on a single column in which it's empty on the other row.  When you follow the link on xts v1.0, you get this:
![xts-1-link](https://user-images.githubusercontent.com/1125622/113138658-b7af6780-91eb-11eb-9016-0a3f9ccb6893.png)
So while the index page indicates that link belongs to xts 1.0, you can see it actually belongs to version 0.12

So it appears that one or more package in the CRAN index does not indicate 2 or more versions of that package, but rather that the index is corrupt.   By scrolling through the index visually it appears that columns are never blank unless they have multiple rows with the same package name.  It also appears that the row that contains most of the blank values is the invalid row.

So my suggestion is the parser should recognize it has seen the package before and decide to either reject the second row or replace the original row with the second one based on "empty column" analysis.  But empty columns definitely is an indicator of a corrupt index.

**Comment by AMDmi3** [comment]
Have you reported it to CRAN?

**Comment by jrmarino** [comment]
I have not done so because I don't have a contact.  I'm not opposed to doing it; it's only that I haven't done it yet.  However, it's not a bad idea for the parser to handle this anyway -- as long as it's accepted that multiple rows with the same package name is actually indicative of a problem.  From what I can tell, CRAN doesn't support multiple simultaneous versions (intentionally).

**Comment by AMDmi3** [comment]
I'm strictly against adding handling for others' problems, it adds extra complexity here and does not solve the original problem. CRAN contacts are right at the bottom of their site.

**Comment by jrmarino** [comment]
I keep making the mistake that you care about accuracy more than grandstanding.
In practical terms, it's your problem too.  And not validating input is a rookie mistake.
But sure, I'll fire off an email and if we're lucky somebody in 6 months may fix it.

**Comment by jrmarino** [comment]
As a compromise (temporary?) I suggest:
If a duplicate package name is used, delete the exiting entry and don't insert the new one.  In other words, with duplicates, skip them all.  that way you don't need logic to determine which is correct and let the other repositories carry the data.

**Comment by AMDmi3** [comment]
Only after it is known that the upstream is unresponsive or refuses to fix the problem.

**Comment by AMDmi3** [comment]
Timeout
