### ISSUE TITLE
Site is not updating Ataraxia repository

### ISSUE THREAD

**Issue by protonesso** [repology/repology-updater#1148]
Hello, I am Ataraxia GNU/Linux developer, I noticed repology didn't update the package information on the page, despite "repo" is being updated.

**Comment by AMDmi3** [comment]
https://repology.org/log/6535922

**Comment by protonesso** [comment]
Thank you! Going to fix those

чт, 6 мая 2021 г., 13:26 Dmitry Marakasov ***@***.***>:

**Comment by AMDmi3** [comment]
Not repology problem.

**Comment by protonesso** [comment]
Fixed. Thank you!

сб, 8 мая 2021 г., 14:53 Dmitry Marakasov ***@***.***>:

**Comment by AMDmi3** [comment]
You are now hiding this package, this is faking data for repology. Sorry, I cannot allow that. Please provide complete package data.

**Comment by protonesso** [comment]
This package is meant to be hidden. It's not used everywhere and is used in
bootstrap purposes. However if that really need then consider adding
systemd-runtime and util-linux-runtime aliases.

вс, 9 мая 2021 г., 21:15 Dmitry Marakasov ***@***.***>:

**Comment by AMDmi3** [comment]
As far as I can see, there are a lot of ports ignored this or another way:
```
./lldb/.ignore
./ataraxia-sources/.ignore
./meson/.ignore
./polly/.ignore
./systemd-runtime/.completeignore
./llvm/.ignore
./libclc/.ignore
./docbook-xml/.gitignore
./systemd/.ignoreit
./systemd/.ignore
./util-linux-runtime/.completeignore
./linux/.ignore
```

**Comment by protonesso** [comment]
.completeignore is used to hide ports from database

. ignore is for our updater

вс, 9 мая 2021 г., 21:54 Dmitry Marakasov ***@***.***>:

**Comment by protonesso** [comment]
.ignore will make port updater to not commit update for port but will
notify you that new version is released. Useful if port is big and/or has
lot of patches applied

вс, 9 мая 2021 г., 22:22 Nagakamira ***@***.***>:

**Comment by AMDmi3** [comment]
Repology should see both kinds of packages.

**Comment by protonesso** [comment]
Okay making systemd-runtime and util-linux-runtime visible asap

вс, 9 мая 2021 г., 22:26 Dmitry Marakasov ***@***.***>:

**Comment by AMDmi3** [comment]
In fact I'm not 100% sure for these two, but I don't see any reason why .ignore's should be hidden.

**Comment by AMDmi3** [comment]
Are you sure? For instance meson and lldb are not in the .json, and this seems to be the place:

https://github.com/ataraxialinux/ataraxia/blob/8be1dba95716a9f8e8f4689b16ed0a71495ecaa2/core.functions#L386-L388

**Comment by protonesso** [comment]
Will check asap

вс, 9 мая 2021 г., 23:49 Dmitry Marakasov ***@***.***>:
