### ISSUE TITLE
Request to add MX Linux "AHS" section for MX 19 repos, plus new MX 21 repos

### ISSUE THREAD

**Issue by stevenpusser** [repology/repology-updater#1157]
AHS is our "Advanced Hardware Support" for hardware too new to be supported by Debian Buster's 2019 packages. It's just another section like main or non-free, which repology already tracks:

`deb http://mxrepo.com/mx/repo/ buster main non-free ahs`

We also now have a repo for the Debian 11-based MX 21 set up and are populating it, but with the test and AHS sections to be populated in the future as Bullseye ages:

`deb http://mxrepo.com/mx/repo/ bullseye main non-free ahs`

along with a corresponding MX 21 test repo:

`deb http://mxrepo.com/mx/testrepo/ bullseye test`

Thanks in advance!

**Comment by AMDmi3** [comment]
There's no ahs for bullseye and not testrepo either.

**Comment by stevenpusser** [comment]
Tim, who maintains our repos, just told me that our repo system doesn't create a Release file for a section until we actually put a package in it.  That'll be some months down the road for MX 21, so I'll created an issue for those again when we do add packages.

Thanks again for adding AHS!

**Comment by AMDmi3** [comment]
So should I add MX-21 without ahs for now?

**Comment by AMDmi3** [comment]
Timeout
