### ISSUE TITLE
Add Debian User Repository

### ISSUE THREAD

**Issue by otreblan** [repology/repology-updater#1161]
It's like the AUR but for Debian.
https://www.reddit.com/r/linux/comments/o7tors/product_release_introducing_the_debian_user/

**Comment by AMDmi3** [comment]
Repository/metadata url please

**Comment by otreblan** [comment]
> Repository/metadata url please

https://dur.hunterwittenborn.com/

**Comment by AMDmi3** [comment]
I need an URL for `Sources.xz`, `packages.db.tar.xz` or a similar file.

**Comment by hwittenborn** [comment]
Hi! Looks like I'm popping in now.

The DUR uses the same format as the [AUR](https://repology.org/repository/aur). Mostly everything should be the same (except for the base URL), but I'd be glad to help out if any discrepancies occur.

**Comment by otreblan** [comment]
> I need an URL for `Sources.xz`, `packages.db.tar.xz` or a similar file.

```bash
$ curl -s "https://dur.hunterwittenborn.com/packages.gz" | gzip -d -

# AUR package list, generated on Sat, 26 Jun 2021 22:16:04 GMT
element-desktop-bin
papirus-icon-theme
nerd-fonts-inconsolata-go
dolphin-emu-git
yafetch-git
tisc-git
pplatex
legendary
python3-docutils-stubs
python3-sphinx-argparse-cli
wiimms-szs-tools-git
```

**Comment by AMDmi3** [comment]
> The DUR uses the same format as the AUR
If that's a slow unreliable API which doesn't return all required information, than this does not meet Repology requirements for new repositories.

Anyway, I don't plan to add this until it's somewhat mature.

**Comment by AMDmi3** [comment]
Is this named MPR now?

> versioned JSON interface

Where can it be accessed?

**Comment by otreblan** [comment]
> Is this named MPR now?
> 
> > versioned JSON interface
> 
> Where can it be accessed?

In `https://mpr.hunterwittenborn.com`.
![image](https://user-images.githubusercontent.com/39320840/132078197-9df49f63-5f2e-41fd-8457-8924e0de05d9.png)

**Comment by hwittenborn** [comment]
Yeah, it's known as the MPR (permanently) now.

The JSON interface can be accessed from `https://mpr.hunterwittenborn.com/`, followed by the query arguments which are identical to those at https://aur.archlinux.org.

If you'd need any help getting everything going, I should be on fairly regularly as well (The MPR also has a support room on Matrix which can be found on the makedeb/makedeb GitHub repo).

**Comment by AMDmi3** [comment]
Note that as I've already stated, archweb RPC is not acceptable for new repos, however I'm making an exception for now. Since you seem to use archweb fork, you may consider merging this patch https://github.com/AMDmi3/aurweb/compare/expose-package-sources to solve one of its problems.

**Comment by hwittenborn** [comment]
The backend for the AUR is actually undergoing a rewrite in Python right now, which is probably the main inhibitor of adding new features to the platform at the moment.

After it's complete, I plan on forking the project again though and then doing whatnot with the changes I'd like to make.

From what I saw, you just want package sources (what sources that a package uses to build) exposed via the API?

**Comment by hwittenborn** [comment]
On a side note: can I make an announcement in makedeb's support rooms that support for this was added?

**Comment by AMDmi3** [comment]
> From what I saw, you just want package sources (what sources that a package uses to build) exposed via the API?

As far as I remember it's they only bit of data usable by repology which was missing from the API. However the main problem with it is that it requires iteration page by page, which is slow, unreliable and returns inconsistent results.

> On a side note: can I make an announcement in makedeb's support rooms that support for this was added?

Sure

**Comment by hwittenborn** [comment]
> Sure

Great, thanks a ton! :tada: 

> It requires iteration page by page

That would be from a need of trying to process an HTML page (from the lack of sources in the RPC interface) and not a problem with the RPC interface itself, correct? If otherwise, I think I was a bit confused on what you were asking :P

**Comment by AMDmi3** [comment]
> That would be from a need of trying to process an HTML page (from the lack of sources in the RPC interface) and not a problem with the RPC interface itself, correct? If otherwise, I think I was a bit confused on what you were asking :P

This is not related to sources, and yes, it's a problem with RPC interface itself. The fetcher currently works as follows:
- fetch `https://mpr.hunterwittenborn.com/packages.gz` to get complete list of all packages (RPC cannot even do that)
- generate a bunch of requests like `https://mpr.hunterwittenborn.com/rpc/?v=5&type=info&arg[]=package1&arg[]=package2&...` to get package information. Multiple requests are required because there's a limitation on query string length

So, to fetch AUR we need 261 requests which take several minutes. Also, if some package gets modified, removed or added in the process, we get inconsistent information.

**Comment by hwittenborn** [comment]
Alright, that all makes more sense.

I'll bring it up in the AUR's dev room and see if they have any thoughts. My initial though to why it might not be in the RPC interface is that it's currently querying the database every time it makes a request, and doing something like fetching data for all packages would be quite expensive computationally.

This would definitely be something I think could be implemented, probably after the Python rewrite is actually complete. 

Regarding a technical implementation, my first thought would be to give a special access key or something that gives people access to things like this, but it might not even be needed if the AUR/MPR could just cache certain points directly on the RPC interface.

All just stuff I'm throwing up in the air; I'll send a message here if I get any feedback on it.

If you'd like to directly contact the team behind everything as well (we might get a solution quicker that way since we could do it over a live chat), you can reach out to them at `#archlinux-aurweb` on libera.chat and at `#archlinux-aurweb:libera.chat` on Matrix.

**Comment by AMDmi3** [comment]
> and doing something like fetching data for all packages would be quite expensive computationally

It can be solved by introducing a regular dump of complete package info, as most repos do. It'd be both computation (need to be done once per time interval, not for each request) and traffic (may be compressed) effective, simple and consistent (due to atomicity).

**Comment by hwittenborn** [comment]
Sorry for the delay, got a bit sidetracked :/

Your method is probably what I'd think about doing. I'll go ahead and create an issue for it on the AUR issue tracker and report back once that's all set up

**Comment by hwittenborn** [comment]
Just published an issue at https://gitlab.archlinux.org/archlinux/aurweb/-/issues/111 :)

**Comment by hwittenborn** [comment]
Looks like they just implemented the new package archives :) They should contain data for all the packages on the AUR.

See https://lists.archlinux.org/pipermail/aur-general/2021-November/036659.html for everything about using them.

**Comment by AMDmi3** [comment]
This is fantastic, I'm switching to it right away. Will similar thing be implemented for MPR anytime soon? As I'd like to remove old AUR fetching and parsing code ASAP.

**Comment by hwittenborn** [comment]
I'm glad to hear you like it!

Yes, the MPR should be getting the new archives implemented soon. I'm moving the MPR over to the new AUR implementation on Saturday, so it should be able to get done soon after that (I think I'll need to merge in a could of upstream changes, but I'll have to check).

**Comment by AMDmi3** [comment]
@hwittenborn FYI, MPR update is currently broken  https://repology.org/log/9297404

**Comment by hwittenborn** [comment]
That all makes sense, I currently have the MPR in a maintenance mode while migrating everything over to the new Python implementation.

**Comment by hwittenborn** [comment]
Alright, everything should be set up to start using the new archives for the MPR.

**Comment by AMDmi3** [comment]
@hwittenborn FYI, MPR update is broken since Dec 6: https://repology.org/log/9870013.

**Comment by hwittenborn** [comment]
I was noticing some stuff on the MPR wasn't up to date a bit back - would there be any way for me to be able to check logs myself occasionally?

Regarding the issue though, it doesn't look like the RPC archives include the URL field, is the AUR not having the same issue?

**Comment by AMDmi3** [comment]
> I was noticing some stuff on the MPR wasn't up to date a bit back - would there be any way for me to be able to check logs myself occasionally?

Sure, see [repositories->updates](https://repology.org/repositories/updates) section.

> Regarding the issue though, it doesn't look like the RPC archives include the URL field during generation, is the AUR not having the same issue?

AUR does not have this issue, and MPR did not until something changed on your side (repology parsed have not been changed since Nov 11).

AUR:
```json
  {
    "ID": 204012,
    "Name": "rdiff-backup-devel",
    "PackageBaseID": 173,
    "PackageBase": "rdiff-backup-devel",
    "Version": "1.3.3-2",
    "Description": "A utility for local/remote mirroring and incremental backups",
    "URL": "http://www.nongnu.org/rdiff-backup/",
    "NumVotes": 9,
    "Popularity": 0,
    "OutOfDate": null,
    "Maintainer": "Dragonlord",
    "FirstSubmitted": 1113230185,
    "LastModified": 1435508624,
    "URLPath": "/cgit/aur.git/snapshot/rdiff-backup-devel.tar.gz",
    "License": [
      "GPL"
    ],
    "Keywords": [],
    "Depends": [
      "python2",
      "librsync"
    ],
    "OptDepends": [
      "pylibacl",
      "pyxattr"
    ],
    "Conflicts": [
      "rdiff-backup"
    ],
    "Provides": [
      "rdiff-backup"
    ]
  },
```
MPR:
```json
  {
    "ID": 506,
    "Name": "alacritty",
    "PackageBaseID": 15,
    "PackageBase": "alacritty",
    "Version": "0.9.0-1",
    "Description": "A cross-platform, GPU-accelerated terminal emulator",
    "NumVotes": 0,
    "Popularity": 0,
    "OutOfDate": null,
    "Maintainer": "otreblan",
    "FirstSubmitted": 1624765254,
    "LastModified": 1630184198,
    "URLPath": "/cgit/aur.git/snapshot/alacritty.tar.gz",
    "Depends": [
      "libx11-xcb1",
      "libgl1"
    ],
    "MakeDepends": [
      "cargo",
      "cmake",
      "desktop-file-utils",
      "gdb",
      "git",
      "libfontconfig1-dev",
      "libfreetype6-dev",
      "libncurses-dev",
      "libxcb-render0-dev",
      "libxcb-shape0-dev",
      "libxcb-xfixes0-dev",
      "libxcb1-dev",
      "libxkbcommon-dev",
      "rustc"
    ],
    "CheckDepends": [
      "fonts-dejavu"
    ],
    "License": [
      "APACHE"
    ]
  },
```

**Comment by hwittenborn** [comment]
Sorry for the delay on my end, I've been a bit busy with some other things recently.

I just wanted to send a message that I'm still looking into this and that I haven't just forgotten about it or anything. I'll let you know once I figure out the underlying issue and a fix is implemented though.

**Comment by hwittenborn** [comment]
@AMDmi3: Just checked this issue again and saw the commit you linked, and then found the fix aurweb used - I'm implementing it right now and it should be deployed by the end of today.

**Comment by hwittenborn** [comment]
The issue should be fixed in the deployed instance now.
