### ISSUE TITLE
KISS source file changes

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-updater#1166]
KISS now supports variables in its sources files. 

It looks like this:

```
https://zlib.net/zlib-VERSION.tar.gz
```

Which becomes:

```
https://zlib.net/zlib-1.2.11.tar.gz
```

Supported variable names are (example version file: `1.2.3+stuff-ddaefd 1`): 

- `VERSION` the first field of the version file as-is (`1.2.3+stuff-ddaefd`). 
- `RELEASE` the second field of the version file as-is (`1`).
- `MAJOR` the first component of `VERSION` split on `.+-_` (`1`).
- `MINOR` the second component of `VERSION` split on `.+-_` (`2`).
- `PATCH` the third component of `VERSION` split on `.+-_` (`3`).
- `IDENT` the rest of the components (starting from the fourth) as a single string (`stuff-ddaefd`).
- `PKG` the name of the package (the basename of the file's directory).

This works by simple substitution (marker is replaced by value). 
All matches on all lines are operated on.

While this feature is in the package manager, the repositories do not yet make use of it.
That change can be seen here: https://github.com/kisslinux/repo/pull/286

**Comment by AMDmi3** [comment]
So this is becoming less and less of KISS, as expected. I don't plan to introduce extra complexity to the parser and duplicate the logic. Please provide a machine readable dump of relevant package data.

**Comment by dylanaraps** [comment]
That's one way of looking at it. I don't feel the same way. Feel free to drop KISS from Repology as I have no plans to provide this information in a "fully compiled" form. No hard feelings whatsoever, thank you for supporting KISS thus far - I appreciate it.

**Comment by illiliti** [comment]
I'm very against these new changes. I was in love with KISS because repository layout was so simple and without all of these nonsense variables. Now I feel betrayed... Therefore, I have to quit the development.

**Comment by jedahan** [comment]
@AMDmi3 I am currently generating csv files for both the core kiss repository, and separately for all repositories. They are up on `http://jedahan.com/kiss-find/core.csv` and `http://jedahan.com/kiss-find/db.csv`. The format is roughly `name, version, repository_url, relative_path_to_package, optional_description`. Is there some documentation I can read to make it the most useful for repology, and get this upstreamed somehow?

**Comment by AMDmi3** [comment]
@jedahan, the first file is 404, the format for another seems to have been changed. I'd strongly prefer JSON for being more flexible, self-documented and less prone to incompatible changes. Also it should contain everything we were parsing from raw kiss repos, for instance current format is missing downloads and patches info, while maintainer field contains names instead of emails.

> Is there some documentation I can read to make it the most useful for repology, and get this upstreamed somehow?

https://repology.org/addrepo

**Comment by jedahan** [comment]
I will iterate on a json dump available at https://jedahan.com/kiss-find/repology.json over the next day or two.

Maintainer email is opt-in, so would you prefer (`opt-in email` / `opt-in no email` / `no opt-in`)
- `maintainer: "name <email@example.com>` / `maintainer: "name <>" / `maintainer: "name"`
or
-  `maintainer: { name: "name", email: "email@example.com"}` / `maintainer: { name: "name", email: null}` / `maintainer: { name: "name" }`

or something else?

**Comment by dylanaraps** [comment]
Maintainer email is mandatory for the official KISS repositories and was mandatory in the community repository 
when it was an official one. Not sure if/why you have changed things since then(?).

**Comment by jedahan** [comment]
The maintainer email may be mandatory but the kiss-find web client does not expose it by default since its easily scrape able. If you want to get repology working again for `kisslinux/repo/{core,extra,wayland}` main I'm happy to skip working on this myself. 

I still think kiss-community should be in repology similar to how AUR is (as a separate unofficial repo). I don't know if kiss-community has protocol defined for maintainer email - currently I use git log to grab names in kiss-find, and personally prefer opt-in, so thats what I am doing now.

I'm also happy to stop working on this if theres no consensus on adding stuff to repology, which would be a shame. But I'd rather know that earlier than later.

**Comment by dylanaraps** [comment]
I just wanted to clarify the distribution's stance on maintainer emails (and what the policy was for community before I archived it). 

My comment here still applies: https://github.com/repology/repology-updater/issues/1166#issuecomment-880610738

**Comment by AMDmi3** [comment]
Preferrably #2, but now I wonder how the maintainer names may be opt-in since they come from git IIRC.

**Comment by aabacchus** [comment]
As of kiss 6.1.0, this change has been reverted and the repos are static once again (under the different name of KISS Community). @AMDmi3, can we be added back?

**Comment by AMDmi3** [comment]
> As of kiss 6.1.0, this change has been reverted and the repos are static once again (under the different name of KISS Community). @AMDmi3, can we be added back?

Not unless you provide a repository location at the very least.

**Comment by aabacchus** [comment]
Great, thank you, here are the details:

Title: KISS Community
Repository data locations: https://codeberg.org/kiss-community/repo/ https://codeberg.org/kiss-community/community/
Website: https://kisscommunity.org/

**Comment by aabacchus** [comment]
Thank you very much! Just to avoid any problems, could the main repo be renamed from "KISS Linux main" to "KISS Community main"?

**Comment by aabacchus** [comment]
They are meant to be separate. The correct names would be "KISS Community - main" and "KISS Community - community".
