### ISSUE TITLE
Is it possible that pypi parser recognizes "yanked" releases?

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-updater#1175]
![image](https://user-images.githubusercontent.com/1125622/131138184-596994af-f5cc-4753-9221-b68bbc535148.png)

Current example: https://pypi.org/project/GitPython/#history
GitPython is showing latest version is 3.1.20, but it was revoked along with the previous release, making 3.1.18 the latest valid release.  Can the pypi actually set these yanked releases to some state that isn't considered the latest?

**Comment by AMDmi3** [comment]
Apparently it does https://repology.org/project/python:gitpython/versions#pypi

**Comment by jrmarino** [comment]
I think you misunderstand.
Yes, it's recognizing yanked released, but it's recognizing it as a valid release.
In other words, it shows 3.1.20 as a latest version, rather than some kind of "ignored" version.

 **Can the pypi actually set these yanked releases to some state that isn't considered the latest?**

The answer to this question currently is "no", not yes, because the yanked 3.1.20 is showing as latest.

**Comment by AMDmi3** [comment]
I understand now. Yes, it would be useful, probably applicable to other sources (wikidata), and not too hard to implement. Not sure which effect it should impose, probably marking whole release as outdated without changing order or any ignored statuses.

**Comment by AMDmi3** [comment]
- Repology now supports RECALLED package flag which prevents the whole version from being considered latest
- This flag is set for yanked PyPI releases (yanked status in fact applies to released files, and the package is considered yanked if all of its files are yanked)
- pypicache now preserves releases which are newer than the "latest" release and which have yanked files

I've forced update for GitPython to pick up these releases (other packages will have to wait for an update or need to be updated manually). What's left is some testing and enabling using these yanked releases in Repology.

**Comment by AMDmi3** [comment]
The effect is visible for https://repology.org/project/python:gitpython/information and another example is https://repology.org/project/python:ssh/versions

**Comment by jrmarino** [comment]
looks good, thanks!
