### ISSUE TITLE
[new repo] Homebrew casks versions

### ISSUE THREAD

**Issue by JuniorJPDJ** [repology/repology-updater#1187]
This tap adds other versions of casks to homebrew.

https://github.com/Homebrew/homebrew-cask-versions

**Comment by AMDmi3** [comment]
No usable data.

**Comment by p-linnane** [comment]
Thanks @AMDmi3! Feel free to reach out if you ever need anything from Homebrew. I'm a big fan of Repology, and many of our maintainers use it regularly!
