### ISSUE TITLE
Consider adding Baulk package manager

### ISSUE THREAD

**Issue by rasa** [repology/repology-updater#1195]
[Baulk](https://github.com/baulk/baulk) is a C-based Windows package manager. Its package repository is [here](https://github.com/baulk/bucket/tree/master/bucket). Its json file format is similar to other json-based repos. Here an example:
```
{
    "description": "7-Zip is a file archiver with a high compression ratio",
    "version": "21.04",
    "homepage": "https://www.7-zip.org/",
    "license": "Freeware,LGPL-2.0-only,BSD-3-Clause",
    "url": "https://7-zip.org/a/7z2104.exe",
    "url.hash": "SHA256:1f8b80bca00016ec2a409fb77f8a55f3bde65c58f93c4f5cbb569ac912e3dd78",
    "url64": "https://7-zip.org/a/7z2104-x64.exe",
    "url64.hash": "SHA256:a95a98619f0ad4308f0fe446cae71921743cb8c66324cec5f97cd3485369a71b",
    "urlarm64": "https://7-zip.org/a/7z2100-arm64.exe",
    "urlarm64.hash": "SHA256:19e6d76486b9ef9925dde69de1a0b994abf0e02a86275e1e838758a958724578",
    "extension": "7z",
    "launchers": [
        "7z.exe"
    ]
}
```

**Comment by AMDmi3** [comment]
@fcharlie hi, you might be interested.

The repository data looks good, but there are some versions prefixed with `v` which will be considered obsolete unless fixed.

**Comment by AMDmi3** [comment]
Deployed!
https://repology.org/repository/baulk
https://repology.org/repositories/statistics#baulk
https://repology.org/projects/?inrepo=baulk

**Comment by fcharlie** [comment]
> @fcharlie hi, you might be interested.
> 
> The repository data looks good, but there are some versions prefixed with `v` which will be considered obsolete unless fixed.

Fixed. Thanks.
