### ISSUE TITLE
Problem suggestion for FreeBSD Ports: manpages under %%DOCS%%

### ISSUE THREAD

**Issue by arrowd** [repology/repology-updater#1200]
According to FreeBSD Porter's Handbook, the manpages installed by the port should be guarded by `%%MANPAGES%%` keyword instead of `%%DOCS`. It would be great if Repology would analyze `pkg-plist`s and look for `%%DOCS%%man/.*` lines and put them under "Problems" section.

**Comment by AMDmi3** [comment]
It's out of Repology scope.
