### ISSUE TITLE
Carbs Linux packaging changes

### ISSUE THREAD

**Issue by cemkeylan** [repology/repology-updater#1203]
There are several noteworthy changes to the Carbs Linux packaging system, and I think it would be better to split the way kiss repositories are processed and Carbs is processed. The package managers have been different for over a year now, but the packaging systems were more or less the same until July this year. Carbs Linux is using its own package manager `cpt`.

- As you may remember from a previous issue, kiss is no longer fully static (versioning in the `sources` file). This is not the case for Carbs, the packaging system is still fully static.
- `cpt` supports a `meta` file that includes information irrelevant to the package manager itself, but useful for collecting/parsing information. It typically lists the SPDX license identifier, maintainer information, and a short package description. Here is the meta file for the package manager

```
description: Carbs Packaging Tools
license: MIT
maintainer: Cem Keylan <cem@carbslinux.org>
```

The existence of this file also removes the requirement of unshallow clones of the repository, since we were doing that to grab the maintainer information from the git log.

- Github is no longer the canonical source of the repository, the repository is hosted on <https://git.carbslinux.org/repository>. Currently, it's mirrored to Sourcehut (<https://git.sr.ht/~carbslinux/repository>) along with Github, but I am planning to drop the Github mirror at the end of June 2022.

**Comment by AMDmi3** [comment]
> but I am planning to drop the Github mirror at the end of June 2022.

Please reconsider. This is deliberate obtrusion of visibility, availability and contribution and may be the base for delisting.

**Comment by cemkeylan** [comment]
I didn't think of it that way, I will reconsider.
