### ISSUE TITLE
Request to add new https://github.com/microsoft/winget-pkgs windows package manager

### ISSUE THREAD

**Issue by lepapareil** [repology/repology-updater#1205]
Hi,

As choco and scoop, winget is a windows package manager supplied by microsoft.
It would be useful to add it into repology :)

**Comment by lepapareil** [comment]
Hi @AMDmi3, may i ask why you have closed this issue ? I think that official repo https://github.com/microsoft/winget-pkgs is compliant with requirements listed in https://repology.org/addrepo

**Comment by AMDmi3** [comment]
Probably because it lacks `PackageName` property

**Comment by lepapareil** [comment]
I create this winget package using `wingetcreate` and as you can see the `PackageName` property exists in https://github.com/microsoft/winget-pkgs/blob/master/manifests/o/Orange-OpenSource/Hurl/1.5.0/Orange-OpenSource.Hurl.locale.en-US.yaml 

![image](https://user-images.githubusercontent.com/15672496/145646743-51e597d5-7867-4211-a05f-6f136d40be73.png)

**Comment by AMDmi3** [comment]
Oh. Here it is: https://repology.org/project/hurl-unclassified. It's unclassified as the name is ambiguous and the manifest lacks any download locations. https://github.com/microsoft/winget-pkgs/blob/master/manifests/o/Orange-OpenSource/Hurl/1.5.0/Orange-OpenSource.Hurl.installer.yaml manifest which contains download locations lacks `PackageName`.

**Comment by lepapareil** [comment]
I will add PackageName to Hurl.installer.yaml in the next release ! Thks for your work :)
