### ISSUE TITLE
License of dumps?

### ISSUE THREAD

**Issue by c4rlo** [repology/repology-updater#1209]
Hi, I'm interested in potentially using the Repology [dumps](https://dumps.repology.org/) for a project, but was unable to find out what license (if any) they fall under. It would be great to get this clarified. Thank you!

**Comment by AMDmi3** [comment]
Unfortunately I have no idea. These are derivative works from the respective repositories which have their own licenses, IANAL so I'm not sure whether it can be classified as a compound work under its own license, or is governed by a combination of original licenses. One I can say for sure - I do not want impose any additional restrictions, so if I have a legal right to set a license on these dumps, it'd be [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/).

Related issue: repology/repology-webapp#65
