### ISSUE TITLE
Support for docker-ce repositories

### ISSUE THREAD

**Issue by ademar59** [repology/repology-updater#1210]
Hi,

Could you please add https://download.docker.com/linux/debian

**Comment by AMDmi3** [comment]
At least a summary of what the heck this is is needed, and a list of concrete repositories to use.

**Comment by ademar59** [comment]
I use renovate to manage our dependencies 
I have ansible projects who install [docker](https://docs.docker.com/engine/install/with) on debian bullseye

see [Install using the repository](https://docs.docker.com/engine/install/debian/#install-using-the-repository)

in my code i want to use:
```
# renovate: datasource=repology depName=debian_11/docker-ce versioning=loose
docker_debian_version: 5:20.10.12~3-0~debian-bullseye
```

But docker-ce is not available on repology: https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/

**Comment by AMDmi3** [comment]
We don't add PPAs and alike.

**Comment by ademar59** [comment]
it's a shame to consider official docker repository https://download.docker.com/linux/ as personal

**Comment by AMDmi3** [comment]
But that's exactly what it is - a personal repository [of docker project]. It provides ridiculously small number of packages (5), 4 of which are unique. Even if it provided packages which could be matched to other repositories, the profit of discovering a new release a bit faster would be negligible to justify the burden of maintaining a lot of small private repositories for certain projects. Additionally, this repository does not provide source packages.
