### ISSUE TITLE
Support Endless OS

### ISSUE THREAD

**Issue by wjt** [repology/repology-updater#1214]
[Endless OS](https://www.endlessos.org/os) is a Debian derivative. We distribute it as an immutable OSTree snapshot but it's assembled from `.deb`s fetched with apt in the normal way. We use the Debian bullseye repos directly, plus our own repo which has a higher priority.

On Endless OS 4 (the current stable release), `/etc/apt/sources.list` looks like this:

```
deb https://deb.endlessos.org/debian eos4.0 core endless
deb-src https://deb.endlessos.org/debian eos4.0 core endless
deb https://deb.debian.org/debian bullseye main contrib non-free
deb-src https://deb.debian.org/debian bullseye main contrib non-free
deb https://deb.debian.org/debian bullseye-updates main contrib non-free
deb-src https://deb.debian.org/debian bullseye-updates main contrib non-free
deb https://security.debian.org bullseye-security main contrib non-free
deb-src https://security.debian.org bullseye-security main contrib non-free
```

and we have the following in `/etc/apt/preferences.d/endless.pref` to always prefer Endless-provided packages, even if older than versions in Bullseye:

```
Package: *
Pin: release o=Endless
Pin-Priority: 700
```

The development branch looks the same with `eos4.0` replaced by `master`.

I'm not quite sure how this would map to the YAML config found in `repos.d/deb/` but someone better versed in this project may be able to add it.

**Comment by AMDmi3** [comment]
So I assume the idea is to only add endless repos (eos4.0 and master) (cause we don't need another debian clone), right?

Does [this](https://github.com/repology/repology-updater/commit/ade07dd0ef21ae814a44066c6efcd69d88abe5e7) look reasonable (in terms of names, ids, urls)?

Stats for this config look like this:
![2022-01-12-145015_maim](https://user-images.githubusercontent.com/474217/149135383-8d5e8042-08f6-4e54-adc5-1f036ec48686.png)

**Comment by wjt** [comment]
That looks about right! The other interesting URL might be https://github.com/endlessm/ – packages in the `endless` component are maintained there. (Packages in the `core` component are maintained in our Open Build Service instance, which is, unfortunately, private.)

**Comment by AMDmi3** [comment]
Isn't there by the chance a direct mapping between packages in `endless` and repositories in https://github.com/endlessm/?

**Comment by wjt** [comment]
Yes, with some annoying exceptions inherited from Debian.

| source package | GitHub repo |
| -- | -- |
| gdm3 | [gdm](https://github.com/endlessm/gdm) |
| grub2 | [grub](https://github.com/endlessm/grub) |
