### ISSUE TITLE
Add yiffOS Repositories

### ISSUE THREAD

**Issue by floppydiskette** [repology/repology-updater#1217]
[yiffOS](https://yiffos.gay) is a Linux distribution that is loosely based off of LFS that uses its own [package manager](https://gitlab.com/yiffos/packaging/bulge).

----

Categories: `core` `extra` and `community`
Distro versions: `knot` (Changes based on glibc and gcc toolchain versions)

Flat file with all package names: `https://mirror.yiffos.gay/<category>/x86_64/<distro version>/database.flat`
Individual package information: `https://gitlab.com/yiffos/packaging/packages/-/raw/<distro version>/<package>/PKGINFO`

Alternatively, the entire Git repo can be downloaded as a tarball: `https://gitlab.com/yiffos/packaging/packages/-/archive/<distro version>/packages-<distro version>.tar.gz` which then follows the folder structure `packages-<distro version> -> <package> -> PKGINFO`

Example PKGINFO (`https://gitlab.com/yiffos/packaging/packages/-/raw/knot/mariadb/PKGINFO`):
```json
{
    "name": "mariadb",
    "version": "10.6.5",
    "epoch": 0,
    "description": "Community-maintained fork and drop-in replacement of MySQL.",
    "groups": [],
    "url": "https://mariadb.org/",
    "license": ["GPL-2.0"],
    "depends": ["libxml2", "systemd", "zstd", "curl", "libevent", "libaio", "pcre2"],
    "optional_depends": [],
    "make_depends": ["boost", "bzip2", "cmake", "curl", "libxcrypt"],
    "provides": ["mariadb"],
    "conflicts": ["mysql"],
    "replaces": ["mysql"],
    "maintainers": ["Evie Viau <evie@uwueviee.live>"]
}
```

**Comment by AMDmi3** [comment]
Looks good. I'm going to use data from `packages` repo. Could you please clarify which branches need to be supported and which are suitable tags/names for them? Does `knot`/`yiffos_knot`/`yiffOS knot` make sense? Do we need `main`/`yiffos_main`/`yiffOS main`?

**Comment by floppydiskette** [comment]
I would say `knot` would be more similar to how other distros do versions (e.g. Fedora 34 vs 35 or Debian 11 vs 12) and the `main`/`extra`/`etc` is similar to how arch does it

In repology it would show up as `yiffOS Knot` with the contents of `main`, `community`, `extra` showing up under that.

**Comment by AMDmi3** [comment]
I don't quite understand where main/extra/community distinction you mention happens. There's a single `packages` repository, no?

**Comment by uwueviee** [comment]
> I don't quite understand where main/extra/community distinction you mention happens. There's a single `packages` repository, no?

It happens mostly at the package manager's side with a bit of it on the server's side, but for collecting/showing metadata from the `packages` repo, it doesn't really matter.

> I take it as a separate entry for `main` branch is not needed?

Correct, the `main` branch is just for active development.

**Comment by AMDmi3** [comment]
I've just grepped Knot in the wiki, is it just a codename? We avoid using codenames in Repology as these break sorting and introduce confusion. Would `yiffOS 0.1.1`/`yiffos_0_1_1` be OK?

**Comment by uwueviee** [comment]
The way yiffOS does releases is on a semi-rolling where the "codename" relates to the toolchain version and is used for packages, the other version number 0.1.1 is used for images. As an alternative, you could use the Glibc version (2.34) instead.

**Comment by AMDmi3** [comment]
I still do not understand how to handle this. Will there be other branches in the repo than `knot`? Will we need to support them in parallel? If no, I'll just add `yiffOS` entry without any suffixes. Otherwise I need to know which suffix to use to distinguish them.

**Comment by uwueviee** [comment]
In the future, there will be other branches that'll have their own package versions as new Glibc versions come out (and thus new branches made) and older versions lose support from the yiffOS maintainers.

**Comment by AMDmi3** [comment]
FYI, the parsing is currently failing https://repology.org/log/11091779 as the failproof condition which checks package name against its directory is failing. So the question is now which one of these is a primary source for the package name.

**Comment by uwueviee** [comment]
Didn't realize that folder name got commited (it should be glib2), we don't currently compare the directory name to the package name in the PKGINFO file in any of our infrastructure. I've opened a ticket on our bug tracker to introduce a system to prevent this from happening again.

**Comment by AMDmi3** [comment]
@uwueviee so I take it as I can leave the check there end continue to expect package names to be equal to directory names?
