### ISSUE TITLE
Add `Raspbian Addons` repo

### ISSUE THREAD

**Issue by hmsjy2017** [repology/repology-updater#1219]
https://apt.raspbian-addons.org/
Raspbian Addons is an APT repository for Raspberry Pies, containing open-source software not in the Pi Foundation's repositories. This repository complements the ARM Linux software ecosystem, where the software is always up to date. I am one of the active maintainers of this apt repository.

**Comment by AMDmi3** [comment]
Are there no source packages?

**Comment by hmsjy2017** [comment]
No. But the packages in this repository are all free software.

**Comment by AMDmi3** [comment]
This does not look suitable for Repology. We won't support a repository which doesn't even allow to trace where a specific version comes from.

**Comment by hmsjy2017** [comment]
There is a list of packages here: https://docs.raspbian-addons.org/package-list/
Almost all of the software in it comes from GitHub.

**Comment by AMDmi3** [comment]
Requirements for new repositories are listed here: https://repology.org/docs/requirements.
