### ISSUE TITLE
Feb 2022: a bunch of broken repositories

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#1222]
During the last few days, a lot of repositories (independently) broke in the parse phase. This is critical because repositories failing this way prevent applying new rules. There's no way to fix it gracefully short-term other than removal of such repositories, and a long-term fix would require a massive rewrite of the update process and introduce a dependency on e.g. ZFS snapshots (to introduce a possibility to roll back to a last good state for any repository).

Failing repos:
- [x] AUR: suddenly stopped providing required `URL` field after changes in aurweb. Probably because of [this](https://github.com/archlinux/aurweb/commit/29c2d0de6b83a2287ffdb885d9b55aa63b1d4792#r66116492) change (ping @kevr), also affects MPR (#1161) which was removed some weeks ago. 
- [x] FreeBSD: a stray port without version defined. Already reported and [fixed](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261745)
- [x] Funtoo: [broken XML](https://github.com/funtoo/desktop-kit/blob/fb358848968b47b3d30c6272c220d991ce2f0e4b/x11-misc/i3lock/metadata.xml) for x11-misc/i3lock in desktop-kit. Ping @palica, @danielrobbins? 
- [ ] Nix (unstable): suddenly stopped providing most of package data (`meta` dict for each package). Ping @edolstra?
- [x] Slackbuilds: missing quote https://git.slackbuilds.org/slackbuilds/commit/multimedia/minitube/minitube.info?id=457c0ba4f2b63ebedbe748d19056a123f06a7649. Ping @willysr.
- [x] Termux: broken json - already [fixed](https://github.com/termux/termux-packages/commit/b760237d8831071490ed9585dc7a8083c940ca2c) (see also comments)

Since these failures prevent fixing a bunch of problem reports which accumulated during past two weeks of my vacation, I can't wait too long for these to be fixed, so let's say there's time till Wednesday for these repositories to fix themselves, otherwise I'll have to remove them until the problems are resolved.

Also a couple of sources are failing in fetch phase now, which is not that critical, but is never the less a good reason to get rid of these too.
- [x] distrowatch (HTTP 400, they have mistakenly banned Repology before and now it happened again) fixed
- [ ] hyperbola (repository data disappeared)

**Comment by willysr** [comment]
Fixed in rebuild-fixes
https://git.slackbuilds.org/slackbuilds/commit/?h=rebuild-fixes&id=8aa9947ecaaaba41c63c3e928c2d7e40c6dc363f

**Comment by kevr** [comment]
Please do not consider this resolved yet. Whatever occurred then may still need to be addressed.

Please see https://lists.archlinux.org/pipermail/aur-general/2022-February/036787.html for details on the changes that affected some helpers.

**Comment by kevr** [comment]
Indeed, we have omitted some keys from the AUR archives when their strings are empty. The parser will need to be adjusted to check for the existence of the key.

**Comment by AMDmi3** [comment]
@kevr the problem is that there's no URL defined for ANY of the packages now. The lines I've pointed out suggest that this field is no longer retrieved from the database.

**Comment by kevr** [comment]
Oh wow. Alright, I'll get this resolved within the next day.

**Comment by AMDmi3** [comment]
@willysr what about master branch? Also IIRC git changes need about a week to propagate to the user-facing slackbuilds repository, is it true in this case? For the record, Repology still [sees](https://repology.org/repositories/updates#slackbuilds) the missing quote.

**Comment by willysr** [comment]
We are still working on 15.0 repo so changes to master will be a lot faster than normal cycle since we push fixes to our branch and merged to master branch in a day or two. I'll merge it now so you can pull it

**Comment by AMDmi3** [comment]
@willysr it's fixed, thank you! While here, would it make sense to keep both slackbuilds 14.2 and 15.0 when the latter is released, or should slackbuilds repo just be switched to 15.0?

**Comment by willysr** [comment]
14.2 will no longer be updated, so probably better go with 15.0 once it's released

**Comment by AMDmi3** [comment]
Hyperbola and nix removed, suggested Repology changes moved to #1223

**Comment by collares** [comment]
Nix unstable was fixed in https://github.com/NixOS/nixpkgs/pull/158548, which was deployed 5 hours ago. Is it still broken?

**Comment by jonringer** [comment]
Is there a way to update point-of-contact for repos? edolstra is largely focused on the tooling aspect of the nix now.

**Comment by vcunat** [comment]
Almost all of the `nix_unstable` regression looks gone already by that PR above.
