### ISSUE TITLE
F-Droid Packages number wrong

### ISSUE THREAD

**Issue by davidak** [repology/repology-updater#1229]
repology says f-droid has 34 packages in it's repository

https://repology.org/repository/fdroid

but it's in fact 3759

https://apt.izzysoft.de/fdroid/?repo=main

i understand that most f-droid packages does not match other repository packages, but it would still be nice to have a correct number there. other repositories also have unique packages

related: https://github.com/repology/repology-rules/commit/b0da9943b487909823effb71c69d5c458019e889

**Comment by AMDmi3** [comment]
Repology reports the number of packages it tracks. You can probably add more packages for fdroid whitelist, btw.
