### ISSUE TITLE
AUR Not Updating

### ISSUE THREAD

**Issue by alex-courtis** [repology/repology-updater#1234]
An AUR project is not updating after several new releases: [way-displays](https://repology.org/project/way-displays/versions)

The .SRCINFO and PKGBUILD appear to have all the required fields scraped by [aur.py](https://github.com/repology/repology-updater/blob/master/repology/parsers/parsers/aur.py)

Two other developers have reported the same issue: https://www.reddit.com/r/archlinux/comments/t0pv46/aur_releases_repology/

If this is not the place to be asking please direct me...

**Comment by AMDmi3** [comment]
Problem on AUR side, probably `packages-meta-ext-v1.json.gz` is not being updated. Ping @kevr
```
% wget -qO- wget https://aur.archlinux.org/packages-meta-ext-v1.json.gz | gunzip | jq '(.[]|select(.Name == "way-displays")).Version'
"1.3.0-1"
```

**Comment by alex-courtis** [comment]
Thank you @AMDmi3
