### ISSUE TITLE
Cgit URL to view PKGBUILDs on the MPR is no longer valid

### ISSUE THREAD

**Issue by hwittenborn** [repology/repology-updater#1235]
I recently redid the UI for the MPR, and with it brought the removal of the Cgit interface used in favor of a custom Git UI.

PKGBUILD sources are now viewable at `/pkgbase/{srcname}/git/tree/PKGBUILD`, as can be seen with [`makedeb`](https://mpr.makedeb.org/pkgbase/makedeb/git/tree/PKGBUILD).

I was gonna make a PR myself to fix the issue, but I didn't feel comfortable submitting something I wasn't able to test locally for first, which I wasn't sure if I'd have time for at the moment.

**Comment by AMDmi3** [comment]
Does the change https://github.com/repology/repology-updater/commit/25a7009c734b8645e5d939ddba985cf0fbeaed7a look good? Is there no way to get a raw PKGBUILD?

**Comment by hwittenborn** [comment]
That all looks good to me, yeah.

There wasn't a way to view a raw PKGBUILD after this port previously, but I just added a route to view such at `/pkgbase/{srcname}/git/raw/PKGBUILD` a couple minutes ago.

**Comment by AMDmi3** [comment]
> but I just added a route to view such at `/pkgbase/{srcname}/git/raw/PKGBUILD` a couple minutes ago.

Great, thank you!
