### ISSUE TITLE
Debian Testing repo is not tracked

### ISSUE THREAD

**Issue by gaborznagy** [repology/repology-updater#1239]
Hi!

Recently I've discovered that Debian Testing is no longer tracked:
https://repology.org/repository/debian_testing

I've found that it's been removed in this commit:
https://github.com/repology/repology-updater/commit/47c4eb21f9cec88cc4df16cbb81e3a77a247e8e6
Debian Sid (unstable) is still tracked.

Would you re-add "testing", please?

I know that Debian 12 is tracked, which is the same as "testing" **now**, but I think when Debian 12 will be released and the next candidate release is not tracked yet, we don't have information about the state of the "testing" repo.

Regards,
Gábor

**Comment by AMDmi3** [comment]
We've intentionally switched from (old)*stable/stable/testing scheme to versioned releases, this will not be reverted. Next testing release can be added as soon as it's available.
