### ISSUE TITLE
Hashicorp Repositories

### ISSUE THREAD

**Issue by rndmh3ro** [repology/repology-updater#1241]
Hashicorp maintains its own repos for their tools:

> Currently, Debian and RPM packages are available for HashiCorp Vault, Consul, and Nomad for both open source and enterprise versions
- https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository

>The Debian and RPM packages currently target popular x86_64/amd64 systemd systems. The repository supports many versions of Debian, Ubuntu, Fedora, CentOS, RHEL, and AmazonLinux. If your platform is not in this list but your system is compatible with Debian or RPM packages, you can still add the repository by specifying a supported release name for apt or $releasever for yum or dnf when you add the repository. This support will expand to other architectures and platforms in the future.

Would be great to have these in repology.

**Comment by AMDmi3** [comment]
We don't support private repositories.
