### ISSUE TITLE
add checking for download locations

### ISSUE THREAD

**Issue by dirkmueller** [repology/repology-updater#1244]
the problem report on repology.org is absolutely great, love it! what would be missing for me is not only checking for the homepage url but also for the download locations, e.g. the ones listed under "Downloads" under https://repology.org/project/shntool/information 

here it would be useful to see 404s or permanent redirect from http to https for example

**Comment by AMDmi3** [comment]
It is deployed. You won't see anything new for opensuse though as it does not publish download locations.

**Comment by dirkmueller** [comment]
@AMDmi3 I'm involved in the openSUSE project. can you please help me understand "as openSUSE does not publish download locations"? how should it be published?
