### ISSUE TITLE
Repology doesn't update the FreeBSD repository for 3+ days

### ISSUE THREAD

**Issue by yurivict** [repology/repology-updater#1245]
I updated www/authelia to 4.35.2 on May 5th, today is May 8th, and Repology still shows that the FreeBSD version is 4.35.1.

**Comment by AMDmi3** [comment]
FreeBSD problem.
```
% curl -sI https://download.FreeBSD.org/ports/index/INDEX-13.bz2 | grep Last-Modified
Last-Modified: Fri, 06 May 2022 01:25:17 GMT
```

**Comment by yurivict** [comment]
The FreeBSD [bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263887).
