### ISSUE TITLE
Labels with wrong colour codes applied to some versions of component 'clamav*'

### ISSUE THREAD

**Issue by Ricky-Tigg** [repology/repology-updater#1247]
Hello. [Newest known version](https://www.clamav.net/downloads) of _clamav_, **0.105.0**, whose equivalent in Repology is [clamav*](https://repology.org/projects/c/?search=clamav) , is labelled by that last according to the _devel_ colour code despite no devel version does exist [there](https://github.com/Cisco-Talos/clamav/tags) for that package. Thus that version is intended to be labelled according to the _newest_ colour code, while that colour code is currently applied to its version **0.104.3**. At last and as a consequence, that last mentioned version is intended to be labelled according to the _outdated_ colour code.

**Comment by AMDmi3** [comment]
The source of devel status is wikidata, please fix there
