### ISSUE TITLE
Unreliable #repos-count 

### ISSUE THREAD

**Issue by Ricky-Tigg** [repology/repology-updater#1253]
_[Reference](https://repology.org/projects/):_

![repology_shutter_project](https://user-images.githubusercontent.com/26058215/173033496-749413cc-e9d0-4eae-b59f-c421573f73ce.png)

Hello. The count _#repos_, which reports the number of repository-families containing the packages that are in version _#repos_ is operating on, might be unreliable. You shall notice it by counting them visually, since the service lacks a filter that would do that for us, against version **0.99** of project shown in reference.

In [package listing](https://repology.org/project/shutter/versions):
- **Exact count** is _3_, which matches families _Fedora_, _Gentoo_, _LiGurOS_, not _2_. Each of their version is assigned the  _legacy_ label.
- **None of the packages** in that version are assigned the _outdated_ label.
- Despite the presence of packages having been assigned the _legacy_ label, the exhibition of that label is missing in reference.

**Comment by AMDmi3** [comment]
It works correctly - there are 2 repository families with 0.99, which are fedora and gentoo (which includes liguros), and that's shown on your screenshot.

**Comment by Ricky-Tigg** [comment]
Well there is indeed a **definition** you had to chose to tie to _repository family_ for this project, which for instance appears to be that _a variant of a parent distribution and the parent distribution are to be considered as a same repository family_. It is a surprise to discover it as part of an answer to a report, since it was left undocumented. Then there is no more than my third observation that remained valid for illustrating an issue.

**Comment by Ricky-Tigg** [comment]
Well there is indeed a **definition** you had to choose to tie to _repository family_ for this project, which for instance appears to be that _a variant of a parent distribution and the parent distribution are to be considered as a same repository family_. It is a surprise to discover it as part of an answer to a report, since it was left undocumented. Then there is no more than my third observation that remained valid for illustrating an issue.

**Comment by AMDmi3** [comment]
Feel free to propose a better definition.

**Comment by Ricky-Tigg** [comment]
Well, that would be off topic. The convention in regard to the definition of _repository family_ can be any you choose. and is not to be judged by others. The undocumented convention was all it was about, not the definition in itself.

**Comment by AMDmi3** [comment]
Honestly I don't understand what conventions you are talking about. Do I understand correctly that the problem is that the fact that the family may include more repositories than just version of a single distro is not apparent? Would changing the explanation of _spread_ in the legend from `e.g. all Debian versions are a single family` to something like `e.g. all Debian versions as well as Ubuntu and other derivatives make a single family` solve the problem?

**Comment by Ricky-Tigg** [comment]
Things are simple when we keep them as such. So far this report's tittle could be reformulated according to the matter that appeared to be the issue. But I doubt that it will be of any help to you, if you cannot understand it neither.. Assume that someone counted _3_ another _4_ (seen in comment in other project), yet another _2_. As expected all of those who counted would be able to justify their counts. Doesn't that tell all you need to know to understand the underlying of the problem here?

**Comment by AMDmi3** [comment]
This does not help. Maybe because I'm not native English speaker and your wording is too complex. Can you formulate in simple terms which the problem is and how, in your opinion, it can be fixed?

**Comment by Ricky-Tigg** [comment]
I do notice late that this report contained multiple possible issues instead of a single one as it should have been in order to observe _good practises_ in this regard. Closing that one as [_not-an-issue_] which applies when a functionality behaves as intended.
