### ISSUE TITLE
Incorrect label assigned to a version in page dedicated to projects

### ISSUE THREAD

**Issue by Ricky-Tigg** [repology/repology-updater#1254]
_[reference](https://repology.org/projects/):_

![repology_shutter_project](https://user-images.githubusercontent.com/26058215/173033496-749413cc-e9d0-4eae-b59f-c421573f73ce.png)

Hello. in [package listing](https://repology.org/project/shutter/versions): all distribution releases in version 0.99 are assigned the  _legacy_ label. Despite **none** of the distribution releases in that version were assigned there the _outdated_ label, that is that one that is exhibited against that version in _reference_, which then indicates an issue, instead of the _legacy_ label, which is the correct label,

**Comment by AMDmi3** [comment]
Legacy statuses do no make sense in projects listing and are not used there.
