### ISSUE TITLE
Add Prebuilt-MPR APT repositories

### ISSUE THREAD

**Issue by hwittenborn** [repology/repology-updater#1257]
The MPR now includes the [Prebuilt-MPR](https://docs.makedeb.org/prebuilt-mpr/getting-started/), which is similar to how the Chaotic-AUR functions for the AUR, with the Prebuilt-MPR containing prebuilt packages from the MPR.

Could the Prebuilt-MPR APT repositories be added to Repology so they could be tracked there? I'm wanting this for a personal reason in addition to potentially others, as I'd like to be able to more easily track the status of the latest packages being in the Prebuilt-MPR, as sometimes builds fail and Repology would provide an easy way to see that when the version are out of date.

It would also help with seeing when packages are out of date in general, as [packages go through a review process before entering the Prebuilt-MPR](https://docs.makedeb.org/prebuilt-mpr/introduction/#security-of-the-prebuilt-mpr), which makes it to where they're not necessarily always in sync with the current version on the MPR.

**Comment by AMDmi3** [comment]
Please resubmit through new [issue template](https://github.com/repology/repology-updater/issues/new?assignees=&labels=new+source&template=newrepo.md)

**Comment by hwittenborn** [comment]
Reopened in https://github.com/repology/repology-updater/issues/1258.
