### ISSUE TITLE
Add Prebuilt-MPR APT repositories

### ISSUE THREAD

**Issue by hwittenborn** [repology/repology-updater#1258]
**Title**

Prebuilt-MPR

**Repository data location(s)**

https://proget.makedeb.org/dists/prebuilt-mpr/focal/binary-all/Packages (Ubuntu 20.04 packages)
https://proget.makedeb.org/dists/prebuilt-mpr/jammybinary-all/Packages (Ubuntu 22.04 packages)
https://proget.makedeb.org/dists/prebuilt-mpr/bullseye/binary-all/Packages (Debian Bullseye packages)

**Package links**

- **Recipe**: https://github.com/makedeb/prebuilt-mpr/blob/pkg/{pkgname}/pkg/PKGBUILD
- Package page: https://proget.makedeb.org/feeds/prebuilt-mpr/{distro}/{pkgname}%3Aamd64/versions
- Package sources: https://github.com/makedeb/prebuilt-mpr/tree/pkg/{pkgname}/pkg
- Issues: https://github.com/makedeb/prebuilt-mpr/issues
- Build status: _Exists, but not current findable via an API_
- Build log: _Exists, but not currently findable via an API_

**Additional details**

This functions similarly to how the Chaotic-AUR functions for the AUR, with the Prebuilt-MPR containing prebuilt packages sourced from the MPR.

**Comment by AMDmi3** [comment]
Why do we need these while we have MPR?

**Comment by hwittenborn** [comment]
Hey @AMDmi3, there was a period where the Prebuilt-MPR wasn't always in sync with the MPR due to how it was updated. That doesn't apply any longer though, so you're right that this isn't needed anymore. I'll likewise go ahead and get this closed up.
