### ISSUE TITLE
Maybe consider removing the i686 "msys2_msys2" variant

### ISSUE THREAD

**Issue by lazka** [repology/repology-updater#1260]
This one here: https://github.com/repology/repology-updater/blob/525ea3be57242f379058b6a67f3c7bef6cdb7305/repos.d/windows/msys2.yaml#L57

I don't know what the rules are for what to include in repology, but we stopped supporting the 32bit msys2 variant 2 years ago and no longer update it or provide a way to install it: https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported

The motivation being that it shows a lot of outdated (+ vulnerable) packages which we never plan to update..

**Comment by AMDmi3** [comment]
Only MSYS2 msys2 or MSYS2 mingw too?

**Comment by AMDmi3** [comment]
From the fact that only msys2_msys2 i686 packages are falling behind I take it as only msys2_msys2 should be removed.

![2022-11-28-232051_maim](https://user-images.githubusercontent.com/474217/204373195-265b5fbf-2bc0-45fe-bf28-827ac720273b.png)

Note that our policy of not removing EoLed repositories does not apply here as here we remove a part (a specific architecure of binary packages) of existing repo which is build (presumably) from the same source as all other architectures.

**Comment by lazka** [comment]
> From the fact that only msys2_msys2 i686 packages are falling behind I take it as only msys2_msys2 should be removed.

Sorry, I somehow missed your response/question back then. Yes, that is correct.

Thank you!
