### ISSUE TITLE
Add maintainer information for Fedora/EPEL packages

### ISSUE THREAD

**Issue by robert-scheck** [repology/repology-updater#1273]
Right now, there is no maintainer information for Fedora/EPEL packages at Repology. These could be gathered from:

 - https://src.fedoraproject.org/extras/pagure_poc.json (main contact)
 - https://src.fedoraproject.org/extras/pagure_owner_alias.json (all maintainers)

**Comment by AMDmi3** [comment]
Sorry, there's no possibility to link additional data to package lists and we're not going to introduce one. This can be solved from the fedora/epel side by publishing complete package information as a single datafile.

**Comment by robert-scheck** [comment]
These are the complete information for all packages as single datafile (first link). Or do you mean one datafile per package?

**Comment by AMDmi3** [comment]
I mean all package information (name, version, license, homepage, download locations etc. _and_ maintainers) in a single file.
