### ISSUE TITLE
Add glaucus

### ISSUE THREAD

**Issue by firasuke** [repology/repology-updater#1280]
**Title**

glaucus

**Repository data location(s)**

- https://github.com/glaucuslinux/cerata

**Package links**

- **Recipe**: https://github.com/glaucuslinux/cerata/blob/master/{pkgname}/ceras
- Package page: https://github.com/glaucuslinux/cerata/blob/master/{pkgname}/
- Package sources: - (Per package, I think {pkgurl} ?)
- Issues: https://github.com/glaucuslinux/cerata/issues
- Build status: - (No build status available)
- Build log: - (No build log available)

**Additional details**

- Distribution Homepage: https://www.glaucuslinux.org/
- Distribution GitHub Organization: https://github.com/glaucuslinux
- Brand Color: #6082b6
- Contact: [firasuke@glaucuslinux.org](mailto:firasuke@glaucuslinux.org)
- Details on custom data format: The `cerata` repository is a ports-like tree, that includes directories named after included packages, each directory contains a `ceras` file which is a `TOML` file that has the `nom` (name) and `ver` (version) (and `cmt` (commit) if `ver` was equal to `git`). The `ceras` file requires no substitutions (meaning it can be easily parsed by your standard TOML parser). If the specified format (multiple directories with TOML files inside of them) is inappropriate for use by Repology, then I'll be willing to provide a single JSON file holding all necessary information.

**Comment by AMDmi3** [comment]
Mostly good, although there are some packages which miss versions and urls. `libelf` for instance has version different from other repos, and I don't see a way to trace where it comes from.

```
2022-10-21 19:28:32 parsing started
2022-10-21 19:28:32 parsing source cerata started
2022-10-21 19:28:32   linux-headers/ceras: WARNING: package without url
2022-10-21 19:28:32   libstdc++-v3/ceras: ERROR: package without version
2022-10-21 19:28:32   libgcc/ceras: ERROR: package without version
2022-10-21 19:28:33   libgomp/ceras: ERROR: package without version
2022-10-21 19:28:33   lksh/ceras: ERROR: package without version
2022-10-21 19:28:33   hydroskeleton/ceras: ERROR: package without version
2022-10-21 19:28:33   musl-utils/ceras: ERROR: package without version
2022-10-21 19:28:33   libelf/ceras: WARNING: package without url
2022-10-21 19:28:33   musl-headers/ceras: WARNING: package without url
2022-10-21 19:28:33 parsing source cerata complete
2022-10-21 19:28:33 parsing complete, 125 packages
```

**Comment by AMDmi3** [comment]
Also is it safe to assume that package subdirectory is the same as `nom` value?

**Comment by firasuke** [comment]
Well that was quick, thanks!

> Also is it safe to assume that package subdirectory is the same as nom value?

Yup, it's perfectly safe to assume that.

> Mostly good, although there are some packages which miss versions and urls. libelf for instance has version different from other repos, and I don't see a way to trace where it comes from.

Well these are unique packages, some of which share a similar source to other packages. I guess they can be called `virtual` packages in a sense. 

```
linux-headers: uses the same url as `linux`
libstdc++-v3: uses the same `version` as `gcc`
libgcc: uses the same `version` as `gcc`
libgomp: uses the same `version` as `gcc`
lksh: uses the same `version` as `mksh`
hydroskeleton: this is a filesystem creation package only for use in cross-compilation (stage 2), a real virtual package I'd say
musl-utils: this package is also only for use in cross-compilation (stage 2)
libelf: uses the same `version` as `elfutils`
musl-headers: uses the same `url` as `musl`
```

Again, thanks for your time and effort on this!

**Comment by AMDmi3** [comment]
Would be be OK to drop these? Well, there's no option for versionless ones, and if it's ok to also assume that url-less packages are virtual, it would make sense to drop these as well to decrease churn.

**Comment by firasuke** [comment]
> Would be be OK to drop these? Well, there's no option for versionless ones, and if it's ok to also assume that url-less packages are virtual, it would make sense to drop these as well to decrease churn.

Well, I guess it's safe to consider all `url`-less packages as virtual (this includes both packages that have a `name` and a `version` but lack a `url`, and packages that have a `name` only with neither a `version` nor a `url`).

**Comment by firasuke** [comment]
Would it also be possible to parse the maintainers from the `ceras` file as well:

- maintainer's info are on the 4th line, and are commented out
- the format is as follows:

```
...
# Voyager: Name (nickname) <email@email.email>
...
```

e.g.

```
...
# Voyager: Firas Khalil Khana (firasuke) <firasuke@glaucuslinux.org>
...
```

The current number of maintainers is `1`, and the info should be as provided above.

Thanks again for the much appreciated time and effort!

**Comment by AMDmi3** [comment]
All done.

**Comment by firasuke** [comment]
@AMDmi3 Thanks for your time and effort!
