### ISSUE TITLE
glaucus specifies the origin of patches

### ISSUE THREAD

**Issue by firasuke** [repology/repology-updater#1283]
Hey there,

I stumbled upon this:
https://github.com/repology/repology-updater/blob/0fdc2f97bcefa428b6212f35e5fc8f6062b1e26c/repos.d/glaucus.yaml#L27

And wanted to clarify that glaucus specifies the origin of the patch (aka there's an additional subdirectory named after the place the patch was obtained from (e.g. `upstream`, `glaucus`, `gentoo`, `alpine`...)).

E.g. The package `gcc` has the following patch [`0013-libgcc_s.patch`](https://github.com/glaucuslinux/cerata/blob/master/gcc/patches/alpine/0013-libgcc_s.patch) from `alpine`. Another patch is [`0001-pure64-for-x86-64.patch`](https://github.com/glaucuslinux/cerata/blob/master/gcc/patches/glaucus/0001-pure64-for-x86-64.patch) which is from `glaucus` (a custom patch made for `glaucus`) and so on.

Would it be possible to specify the source/origin of the patches? Perhaps by using a wildcard for the subdirectories located inside `$pkgname/patches/$origin/some_patch.patch`?

Thanks for your much appreciated time and effort!

**Comment by AMDmi3** [comment]
No and I don't see any gain from that. The idea is to provide all patches for upstream and other maintainers, and it should not matter where these come from.

**Comment by firasuke** [comment]
> No and I don't see any gain from that. The idea is to provide all patches for upstream and other maintainers, and it should not matter where these come from.

Oh I see. So this is just to point visitors to where patches are stored for `glaucus` projects/packages?

**Comment by AMDmi3** [comment]
Yes

**Comment by firasuke** [comment]
Ok, cool.

Thanks a lot for your time and effort and for answering my questions.
