### ISSUE TITLE
What's the purpose of this file?

### ISSUE THREAD

**Issue by firasuke** [repology/repology-updater#1285]
Hey there, I noticed the existence of the following line:

https://github.com/repology/repology-updater/blob/0fdc2f97bcefa428b6212f35e5fc8f6062b1e26c/repology/packagemaker/names.py#L228

I'd like to inquire about the purpose of this file, and why wasn't `glaucus` added to it?

Thanks again!

**Comment by AMDmi3** [comment]
It's the machinery which maps repository-specific set of package identifiers (in glaucus case these _could_ be package subdirectory and `nam` value) into repology terms (what we treat as source and binary package names, what we present to users, what we use as a seed for project name and what we treat as an unique package ID internally).

For glaucus though we don't differentiate subdirectory and `nam`, so we only have a single name which we can treat as a source package name and use for all other purposes, and there's generic `GENERIC_SRC_NAME` mapping for this case. So there's no glacius-specific code in `names.py`.

**Comment by firasuke** [comment]
I see thanks for explaining!
