### ISSUE TITLE
Add Terra Repositories

### ISSUE THREAD

**Issue by lleyton** [repology/repology-updater#1286]
**Title**
Terra 37

**Repository data location(s)**

- https://repos.fyralabs.com/terra37/

**Package links**

- **Recipe**: https://github.com/terrapkg/packages/tree/main/anda/{pkgname}/anda.hcl
- Package sources: https://github.com/terrapkg/packages/tree/main/anda/{pkgname}/
- Issues: https://github.com/terrapkg/packages/issues?q=is%3Aissue+{pkgname}

**Additional details**

- GitHub Organization: https://github.com/terrapkg
- Website: https://terra.fyralabs.com

Some packages are listed under subfolders, grouped by category.

**Comment by AMDmi3** [comment]
Added, thank you.
