### ISSUE TITLE
Mobian

### ISSUE THREAD

**Issue by darkdragon-001** [repology/repology-updater#1291]
**Title**

Mobian

**Repository data location(s)**
- `deb http://repo.mobian.org/ bookworm main non-free`

**Package links**

- **Recipe**: https://salsa.debian.org/Mobian-team/packages/{pkgname}/-/tree/mobian/debian

- Package sources: https://salsa.debian.org/Mobian-team/packages/{pkgname}/
- Issues: https://salsa.debian.org/Mobian-team/packages/{pkgname}/-/issues

**Additional details**
- Based on Debian: https://wiki.debian.org/Mobian
- Development process _(outdated link https://gitlab.com/mobian1 needs to be replaced by https://salsa.debian.org/Mobian-team as can be seen in the Debian Wiki)_: https://wiki.mobian.org/doku.php?id=development:start
- [Logo](https://salsa.debian.org/Mobian-team/mobian-logo)

**Comment by AMDmi3** [comment]
The intersection with the other repositories is only 17 packages. Do we really need this?

**Comment by darkdragon-001** [comment]
> The intersection with the other repositories is only 17 packages. Do we really need this?

I think it would be valuable to have this. As the package index is quite small, I also don't see much downsides of adding it in terms of processor cycles and network traffic for the parser.

**Comment by AMDmi3** [comment]
What value is there in 17 packages?

**Comment by darkdragon-001** [comment]
That one has a *complete* overview of all the distributions where a software is packaged including their versions? Isn't this what repology is all about?

**Comment by AMDmi3** [comment]
Yes and no. Anyway, yet another debian clone with just a dozen of packages does not contribute to this and is not worth the maintenance burden.

**Comment by darkdragon-001** [comment]
> Yes and no. Anyway, yet another debian clone with just a dozen of packages does not contribute to this and is not worth the maintenance burden.

It's not a Debian clone, they work together with the Debian project, get integrated into the Debian infrastructure, moved already to their Gitlab (Salsa) and are more like an upstream to Debain for the still relatively new software packages for mobile in that slowly moving stable distro. It's one of the most common distros for Linux mobile together with ManjaroARM and postmarketOS which is the same to Alpine by the way but is included in repology! Even though 17 packages might not sound much, these are essential packages for Linux mobile. I hoped that repology could be of interest to Linux mobile users but without Mobian, this won't be the case... 😢
