### ISSUE TITLE
Add LURE repository

### ISSUE THREAD

**Issue by Elara6331** [repology/repology-updater#1297]
**Title**

LURE

**Repository data location(s)**

https://api.lure.arsenm.dev/lure.API/Search
https://api.lure.arsenm.dev/lure.API/GetPkg

**Package links**

- **Recipe**: https://lure.arsenm.dev/pkg/default/{pkgname}/lure.sh
- Package page: https://lure.arsenm.dev/pkg/default/{pkgname}
- Package sources: https://github.com/Arsen6331/lure-repo/tree/master/{pkgname}/
- Issues: https://github.com/Arsen6331/lure-repo/issues?q={pkgname}

**Additional details**

- Homepage: https://lure.arsenm.dev

**API Details**

Requires POST request. Supports JSON and Protobuf.

Get all available packages in JSON:
```bash
curl -X POST https://api.lure.arsenm.dev/lure.API/Search -H 'Content-Type: application/json' -d '{}'
```

Get information for a specific package in JSON:
```bash
curl -X POST https://api.lure.arsenm.dev/lure.API/GetPkg -H 'Content-Type: application/json' -d '{"name": "{pkgname}", "repository": "default"}'
```

If this API isn't suitable, I can modify it, this is my project.

**Comment by Arsen6331** [comment]
The API is generated from the following file, so anything listed in there can be used:

https://github.com/Arsen6331/lure/blob/master/internal/api/lure.proto
