### ISSUE TITLE
Add Terra 38

### ISSUE THREAD

**Issue by windowsboy111** [repology/repology-updater#1307]
**Title**

Terra 38

**Repository data location(s)**

- https://repos.fyralabs.com/terra38/

**Package links**

- **Recipe**: https://github.com/search?q={pkgname}+repo:terrapkg%2Fpackages+extension:.hcl&type=Code&ref=advsearch
- Package sources: https://github.com/search?q={pkgname}+repo:terrapkg%2Fpackages+extension:.spec&type=Code&ref=advsearch
- Issues: https://github.com/terrapkg/packages/issues?q=is:issue+{pkgname}

**Additional details**

- GitHub Organization: https://github.com/terrapkg
- Website: https://terra.fyralabs.com/

---
I'm also taking my chance to request a fix for the **Terra 37** links: (same links as Terra 38)
- **Recipe**: https://github.com/search?q={pkgname}+repo:terrapkg%2Fpackages+extension:.hcl&type=Code&ref=advsearch
- Package sources: https://github.com/search?q={pkgname}+repo:terrapkg%2Fpackages+extension:.spec&type=Code&ref=advsearch
- Issues: https://github.com/terrapkg/packages/issues?q=is:issue+{pkgname}

**Comment by lleyton** [comment]
@windowsboy111 I'm pretty sure `extension:.hcl` would have to be `language:hcl` instead.

**Comment by windowsboy111** [comment]
### Terra 38

**Repository data location(s)**
- https://repos.fyralabs.com/terra38/
- https://madoguchi.fyralabs.com/v4/terra38/packages-all

**Package links**
- **Recipe**: https://madoguchi.fyralabs.com/redirect/terra38/packages/{pkgname}/recipe
- Package sources: https://madoguchi.fyralabs.com/redirect/terra38/packages/{pkgname}/recipe
- Issues: https://github.com/terrapkg/packages/issues?q=is:issue+{pkgname}

---

### Terra 37

**Package links**
- **Recipe**: https://madoguchi.fyralabs.com/redirect/terra37/packages/{pkgname}/recipe
- Package sources: https://madoguchi.fyralabs.com/redirect/terra37/packages/{pkgname}/recipe
- Issues: https://github.com/terrapkg/packages/issues?q=is:issue+{pkgname}

---

**Additional details**
- GitHub Organization: https://github.com/terrapkg
- Website: https://terra.fyralabs.com/

**Comment by AMDmi3** [comment]
Mostly good, though `.hcl` links are not really recipes. I'd like links to .spec files in two variants: human readable an raw, e.g.

https://github.com/terrapkg/packages/blob/main/anda/games/opsu/opsu.spec
https://raw.githubusercontent.com/terrapkg/packages/main/anda/games/opsu/opsu.spec

PS. Is it expected that `37` corresponds to `master` branch and `38` corresponds to its own branch, and also that 38 is less fresh?

![2023-04-10-192641_maim](https://user-images.githubusercontent.com/474217/230945917-15af0c8e-bd1e-461c-9c44-af8384a3f57c.png)

**Comment by AMDmi3** [comment]
> Can do, ETA tomorrow.

:+1: 

> Note that for `anda` and `subatomic`, they neither have `.hcl` nor `.spec` files; for `lorax`, it has a `.hcl` file but not a `.spec` file. However, we are (still somehow planning to) removing `lorax` from Terra so it should be fine.

Sorry, I'm not common with the terminology. The point is to show relevant content to these who want to view the recipe right away - so if there are no `.spec`s, but `.hcl` serve as recipe (I guess they should contain build commands instead of just pointer to .spec in this case) instead, the link should point to `.hcl`'s. If there's some other kind of recipe, it's okay to point to it. There should be no links pointing nowhere though - are there some kind of other recipes kind for `anda` and `subatomic`, if they neither have `.hcl` nor `.spec` files?

**Comment by AMDmi3** [comment]
> anda and subatomic has also been added

I still have no idea what this means. For now I've added links to specs, if there are packages that are not built from specsm can you please give an example?

**Comment by AMDmi3** [comment]
@madonuko I have a report of stray package present in the repository index but missing in the git repository, can you please investigate?

https://repology.org/project/avs-tplg-conf/packages
```xml
<package type="rpm">
  <name>avs-tplg-conf</name>
  <arch>x86_64</arch>
  <version epoch="0" ver="2024.02" rel="1.fc40"/>
  <checksum type="sha256" pkgid="YES">20944fec0c889b69d896fc0b222338963c1a318a0276d63693f2f5be16f2068c</checksum>
  <summary>Configuration files for Intel AudioVoiceSpeech (AVS) driver</summary>
  <description>Configuration files for Intel AudioVoiceSpeech (AVS) driver. Each configuration file represents an audio stream topology i.e.: connections of AudioDSP pipelines and processing modules that provide rich user experience with the Intel AVS stack. The avs-driver is part of the Linux kernel sound subsystem, sound/soc/intel/avs.</description>
  <packager></packager>
  <url>https://github.com/thesofproject/avs-topology-xml</url>
  <time file="1716871349" build="1711599152"/>
  <size package="29191" installed="35710" archive="42020"/>
  <location href="avs-tplg-conf-0:2024.02-1.fc40.x86_64.rpm"/>
  <format>
    <rpm:license>Apache-2.0</rpm:license>
    <rpm:vendor></rpm:vendor>
    <rpm:group>Unspecified</rpm:group>
    <rpm:buildhost>8fc2d0f65aa9</rpm:buildhost>
    <rpm:sourcerpm>avs-tplg-conf-2024.02-1.fc40.src.rpm</rpm:sourcerpm>
    <rpm:header-range start="4504" end="12505"/>
    <rpm:provides>
      <rpm:entry name="avs-tplg-conf" flags="EQ" epoch="0" ver="2024.02" rel="1.fc40"/>
      <rpm:entry name="avs-tplg-conf(x86-64)" flags="EQ" epoch="0" ver="2024.02" rel="1.fc40"/>
    </rpm:provides>
    <rpm:conflicts>
      <rpm:entry name="alsa-sof-firmware"/>
    </rpm:conflicts>
  </format>
</package>
```

However resirect links to recipe are broken and I cannot find any mentions of it in https://github.com/terrapkg/packages
