### ISSUE TITLE
JPEGView winget rejected

### ISSUE THREAD

**Issue by sylikc** [repology/repology-updater#1312]
I'm not sure which repository is the right one to create the issue, whether it's rules or this one, but I notice that some repositories are accepted and then the winget ones are rejected?

https://repology.org/project/jpegview/versions

**Comment by sylikc** [comment]
alright.  chocolatey is showing 1.1.43 and I'm trying to get the other repos updated...

**Comment by sylikc** [comment]
oh yeah, followup on this @AMDmi3 , Npackd and Chocolatey also updated the versions, but it's being rejected by repology as well...

It still lists 1.0.37 as the latest version?

**Comment by AMDmi3** [comment]
Yes, repositories are still not trusted.

**Comment by sylikc** [comment]
Better question: How do I get repology to reflect the updated versions of JPEGView to show as the latest version?

1.0.37 is the version from 2018 with bugs and lacks the new image format support

**Comment by AMDmi3** [comment]
Well there are multiple ways to get latest version displayed by repology:
- Make some of ignored repositories which package the latest version fix known cases and introduce policies against new cases of incorrect version reporting
- Make maintainer of some not ignored repository to update the package to the latest version
- Make the software cross platform so more repositories package it and thus odds of some non-ignored repository are higher
- Implement tracking upstream versions from github in repology (#938)

..or we can just add an adhoc unignore rule which I just did.

**Comment by sylikc** [comment]
Thanks for adding the custom rule!  Thanks for making Repology such a good syndication of many software sources!
