### ISSUE TITLE
<user>@cpan gives wrong homepage

### ISSUE THREAD

**Issue by Leont** [repology/repology-updater#1314]
It's currently linking to `http://search.cpan.org/~<username>`, but that redirects to `https://metacpan.org/author/<username>` so it might as well refer to the latter anyway. See [Saying Goodbye to search.cpan.org](https://www.perl.com/article/saying-goodbye-to-search-cpan-org/) for some background.

**Comment by AMDmi3** [comment]
Fixed in repology/repology-webapp#217
