### ISSUE TITLE
Add VenomLinux repositories

### ISSUE THREAD

**Issue by Dieken** [repology/repology-updater#1318]
**Title**

VenomLinux 4.0

**Repository data location(s)**

- https://github.com/venomlinux/ports/tree/4.0/core
- https://github.com/venomlinux/ports/tree/repos/main
- https://github.com/venomlinux/ports/tree/repos/multilib
- https://github.com/venomlinux/ports/tree/repos/nonfree
- https://github.com/venomlinux/ports/tree/repos/testing

**Package links**

- **Recipe**: https://github.com/venomlinux/ports/blob/{4.0/core,repos/{main,multilib,nonfree,testing}}/{pkgname}/spkgbuild

**Additional details**

VenomLinux homepage: https://venomlinux.org

VenomLinux is inspired by CRUX Linux, the package meta data format is very similar to CRUX Linux.

Bash:

- CRUX: https://crux.nu/gitweb/?p=ports/core.git;a=blob;f=bash/Pkgfile;h=7837250d64558b4e208b59cd0f58e04acd11a7df;hb=HEAD
- Venom: https://github.com/venomlinux/ports/blob/4.0/core/bash/spkgbuild

**Comment by AMDmi3** [comment]
Shell files are not suitable repository data.

**Comment by Dieken** [comment]
I'll try to ask VenomLinux maintainers to generate https://venomlinux.org/files/repology-4.0.json just like CRUX, then we may just copy repos.d/crux.yaml to repos.d/venomlinux.yaml and make some small modifications.
