### ISSUE TITLE
Request to update existing `ibmi` repository

### ISSUE THREAD

**Issue by ThePrez** [repology/repology-updater#1321]
**Title**
IBM i

**Repository data location(s)**
- https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-base-7.3/
- https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-base-7.3/repodata/repomd.xml

**Package links**

- Installation: http://ibm.biz/ibmi-rpms
- IBM i open source documentation: http://ibm.biz/ibmi-oss-docs
- IBM i open source resources: http://ibm.biz/ibmioss

**Additional details**
This request is to replace the existing `ibmi` repository at 
https://repology.org/repository/ibmi

**Comment by AMDmi3** [comment]
> Recipe: [https://github.com/mymygarepo/packages/blob/master/{pkgname}/recipe.json](https://github.com/mymygarepo/packages/blob/master/%7Bpkgname%7D/recipe.json)

This recipe link is broken.

**Comment by ThePrez** [comment]
Sorry! Forgot to delete that from the issue template

**Comment by AMDmi3** [comment]
Still, link to package recipes is required. See https://repology.org/repository/ibmi

**Comment by ThePrez** [comment]
Sorry, @AMDmi3. 

We don't publish the `.spec` files except as included in the source RPMs. A sample link would look something like:
 https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-base-7.3/src/{name}-{version}-{release}.src.rpm

However, without better understanding of the repology code, it's not obvious whether `{release}` can be included in the link. Can you advise? 
Thanks!

**Comment by AMDmi3** [comment]
Sorry, directly browseable recipes are required.

**Comment by AMDmi3** [comment]
Timeout
