### ISSUE TITLE
Add four IBM i release repositories

### ISSUE THREAD

**Issue by ThePrez** [repology/repology-updater#1322]
**Title 1**
- IBM i 7.3 release repository

**Title 2**
- IBM i 7.4 release repository

**Title 3**
- IBM i 7.5 release repository

**Title 4**
- IBM i 7.6 release repository

**Repository data location 1**
- https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-7.3/repodata/repomd.xml

**Repository data location 2**
- https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-7.4/repodata/repomd.xml

**Repository data location 3**
- https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-7.5/repodata/repomd.xml

**Repository data location 4**
- https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-7.6/repodata/repomd.xml

**Package links**

- Installation: http://ibm.biz/ibmi-rpms
- IBM i open source documentation: http://ibm.biz/ibmi-oss-docs
- IBM i open source resources: http://ibm.biz/ibmioss

**Additional details**
In addition to the repository at  https://repology.org/repository/ibmi (needs updating per #1321), IBM also delivers a repository for every major release of IBM i. There are currently four live "release" repositories, corresponding to four IBM i releases. 

Submitting as one issue as they are all intrinsically linked (and I assume this is easiest for the maintainers), but let me know if you prefer four separate issues. 

Thanks!

**Comment by AMDmi3** [comment]
Same issue as in #1321

**Comment by Gritme** [comment]
How do I get this removed?

**Comment by ThePrez** [comment]
Can close this and I can resubmit when we sort out recipe distribution
