### ISSUE TITLE
Add Vale repository

### ISSUE THREAD

**Issue by m-czernek** [repology/repology-updater#1326]
This is a request to add a package repository for [Vale](https://repology.org/project/vale/versions). 

**Title**

mczernek/vale

**Repository data location(s)**

- https://download.copr.fedorainfracloud.org/results/mczernek/vale/fedora-38-x86_64/repodata/repomd.xml

**Package links**

- **spec file**: https://github.com/m-czernek/vale.spec
- Package page: https://copr.fedorainfracloud.org/coprs/mczernek/vale/
- Package sources: github.com/errata-ai/vale
- Issues: github.com/errata-ai/vale/issues
- Build status: https://copr.fedorainfracloud.org/coprs/mczernek/vale/package/vale/status_image/last_build.png
- Build log: Available in the RPM repo, or https://copr.fedorainfracloud.org/coprs/mczernek/vale/builds/

**Comment by themr0c** [comment]
@AMDmi3 Vale already exists in repology: https://repology.org/project/vale/versions 
We would like to add the COPR repository to this repository list.
