### ISSUE TITLE
Merge maintainers

### ISSUE THREAD

**Issue by nim65s** [repology/repology-updater#1335]
Hi,

Is it possible to merge maintainers, as we can merge packages here ?

eg. I'm both https://repology.org/maintainer/nim65s@aur and https://repology.org/maintainer/guilhem.saurel@laas.fr

This information could be retrieved at https://aur.archlinux.org/account/Nim65s, but I don't think there is an API for this.

**Comment by AMDmi3** [comment]
Related to #93. I probably need a proof that your aur account wants to be merged with your email. I cannot view your aur account though.

**Comment by nim65s** [comment]
Thanks for the link !

That's right, emails are only visible to logged in AUR users. 

There is only a setting to hide it further, and make it visible only to AUR staff.

Still if this is on a per-request basis, I could provide the proof in another way, eg. line 1 of https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD, but this looks tedious.
