### ISSUE TITLE
Add Google cloud sdk repo

### ISSUE THREAD

**Issue by hinricht** [repology/repology-updater#1338]
**Title**

GoogleCloudSdk bullseye

**Repository data location(s)**

- https://packages.cloud.google.com/apt/dists/cloud-sdk-bullseye/main/binary-amd64/Packages

**Package links**

- **Recipe**: I don't know what this is ?
-  Package page: https://packages.cloud.google.com/apt/pool/google-cloud-cli_372.0.0-0_all_209f62c447fcaced4e52a66eb59ac03f1081b6d44391be68f55f2d23bb196c46.deb   
- Issues: https://issuetracker.google.com/issues?q=status:open%20componentid:187143&s=created_time:desc

**Additional details**

**cloud-sdk container image apt source details**

```
$ docker run --rm registry.hub.docker.com/google/cloud-sdk:435.0.1-slim cat /etc/apt/sources.list.d/google-cloud-sdk.list
deb https://packages.cloud.google.com/apt cloud-sdk-bullseye main

```

**Comment by AMDmi3** [comment]
Repology does not support personal repositories

**Comment by hinricht** [comment]
@AMDmi3 What do you mean by "personal" repository ? 

> Finally, we don't support personal repositories, PPAs, overlays and alike, or collections thereof, due to poor quality, absence of guarantees and moderation and high probability of becoming abandoned. For the same reason, we impose minimal requirements on maturity - that is, a repository should contain at least a few hundred packages and be maintained for at least half a year.

I'm not the biggest fan of google myself, but they provide useful debian packages for i.e. in my case kubectl and don't exactly fall under my definition of "personal" (as in PPAs i.e. of individual persons). Imo the google deb repo check all boxes from the requirements above. 
I just want to understans the reasoning for rejection, it's ok if you don't want to include it.

**Comment by AMDmi3** [comment]
It's personal repository as in PPA of individual company.

**Comment by hinricht** [comment]
Where's the difference to i.e. the [IBMI](https://repology.org/repository/ibmi) or [HP-UX 11.31](https://repology.org/repository/hpux_11_31) repos ?

**Comment by AMDmi3** [comment]
These are self sufficient repositories with common f/oss software. What you propose
- is a PPA with google own software
- only has 64 projects
- the intersection with other repos is even smaller, around 10 projects
- so source packages
This is not closely acceptable.
