### ISSUE TITLE
Wolfi APK Repository

### ISSUE THREAD

**Issue by henrysachs** [repology/repology-updater#1339]
**Wolfi OS**

Wolfi Package Repo

Please bear with me because I'm not sure how to fill this form 😅 

**Repository data location(s)**

- https://packages.wolfi.dev/os/{{aarch}}/APKINDEX.tar.gz

**Package links**

I have a hard time figuring these out as the main communication happens in GitHub for these kind of things:

- Package page: https://github.com/wolfi-dev/os
- Package sources: https://github.com/wolfi-dev/os
- Issues: https://github.com/wolfi-dev/os/issues?q=is%3Aissue+is%3Aopen+{pkgname}

**Additional details**

**Comment by AMDmi3** [comment]
For the record, we use yaml files as a data source. However, neither index nor yaml files contain upstream homepage/download URLs which are required. In addition, yaml contains `${{}}` substitutions repology will not process.

**Comment by henrysachs** [comment]
I thought it would be possible to just reuse what repology is doing for alpine. But I'm new to the project itself.

**Comment by AMDmi3** [comment]
> I thought it would be possible to just reuse what repology is doing for alpine

It is possible, it's just that yamls contain more information. However unlike alpine, neither source for wolfi provides upstream urls which are required. For instance, `U` field:

<table><tr><td>Alpine</td><td>Wolfi</td></tr>
<tr><td>
<pre>
C:Q1hQXyr5dHRc7y3qyEYpt4ClTH908=
P:7zip
V:22.01-r5
A:x86_64
S:854251
I:1695744
T:File archiver with a high compression ratio
U:https://7-zip.org/
L:LGPL-2.0-only
o:7zip
m:Alex Xu (Hello71) <alex_y_xu@yahoo.ca>
t:1681951026
c:1e1218a01323cd9ff429e22ac0f8d62ae9088b78
k:100
D:so:libc.musl-x86_64.so.1 ...
p:7zip-virtual p7zip=22.01-r5 ...
</pre>
</td><td>
<pre>
C:Q1WmGnNqREp8L34t7rILbINU9sMts=
P:7zip
V:22.01-r0
A:x86_64
S:1212953
I:2621828
T:File archiver with a high compression ratio
L:LGPL-2.0-only
o:7zip
t:1686942850
c:3034d595991a3a7cabd72895c1a6a723e337e478
D:so:ld-linux-x86-64.so.2 so:libc.so.6 ...
p:cmd:7zz=22.01-r0
</pre>
</td></tr></table>

**Comment by henrysachs** [comment]
I will try to create an issue at wolfi where the packages are built.

**Comment by kaniini** [comment]
Wolfi does not have a concept of a "package maintainer" (`m` field).

We can start recording the upstream websites for packages.

**Comment by AMDmi3** [comment]
`m` field is not required, and there's no specific requirements for contents of `U` field - just any kind of URL related to upstream is needed as these are used to tell similarly named projects from each other.

However I do not suggest to change repository index format and/or introduce new data just for repologys sake. As far as I can see, upstream URLs (download locations) are present in yaml files. These contain `${{}}` variable substitutions repology won't be able to expand, but if you provide compilation of these files (preferable as a single yaml or json file) with substitutions expanded that would be usable. Even preferable to APKINDEX, as these contain more useful data, such as patch files listing.

**Comment by amouat** [comment]
Hey, just looking at adding the U field to Wolfi -- is this a hard requirement for _all_ packages? If we enable it now it will take a while to filter out to all packages -- would you be happy to filter out the subset of packages with the field?
