### ISSUE TITLE
Add xmake repository

### ISSUE THREAD

**Issue by jube** [repology/repology-updater#1341]
**xmake**

xmake is a build tool that also comes with a package manager. It is quite similar to brew or other tools like that. The package repository contains nearly a thousand packages.

**Repository data location(s)**

- https://github.com/xmake-io/xmake-repo

All the packages are available in a github repository. The package format is a lua script. This may be contrary to the requirements for new repository. But the scripts are very simple and the necessary data can probably be parsed using regexp as, AFAIK, no variable substitution is done in the package data.

**Package links**

- **Recipe**: https://github.com/xmake-io/xmake-repo/tree/master/packages/{pkgname_first_letter}/{packagename}/xmake.lua 
- Package page: no official package page
- Package sources: https://github.com/xmake-io/xmake-repo/tree/master/packages/{pkgname_first_letter}/{packagename}/

**Comment by AMDmi3** [comment]
Sorry, lua scripts are not suitable data source.

**Comment by jube** [comment]
Here, it's the only data source and it's not really Lua, it looks like data (as far as repology is concerned) and can be parsed like other kind of data. But I would understand that it may be too difficult for you as it's not a standardized format like JSON.

**Comment by AMDmi3** [comment]
No, it does not look like data, its lua code. It contains substitutions (in almost every `add_urls` call, sometimes with complex transformations thru lambda functuons), conditions (`if is_plat`, `if is_arch`) which affects urls, versions and patches, path processing code for patches and even some complex url/version alias such as in asio package. It's not "too complex", it's not possible to process without executing the code. You can do that on your side to generate machine readable data such as json.
