### ISSUE TITLE
MX Linux 23 is released, please add its main, test, and AHS repositories

### ISSUE THREAD

**Issue by stevenpusser** [repology/repology-updater#1345]
The URLs are essentially the same as for MX 21, except the parent Debian codename is bookworm instead of bullseye:

main repo:

`deb http://mxrepo.com/mx/repo/ bookworm main non-free`

test repo:

`deb http://mxrepo.com/mx/repo/ bookworm test`

and the advanced hardware support (ahs):

`deb http://mxrepo.com/mx/repo/ bookworm ahs`

Thanks in advance!

**Comment by AMDmi3** [comment]
> test repo:
>
> `deb http://mxrepo.com/mx/repo/ bookworm test`

It should probably read `http://mxrepo.com/mx/testrepo/`, just cloning MX 21 config does the thing.
