### ISSUE TITLE
Add Eclipse Temurin repository for for alpine (apk packages)

### ISSUE THREAD

**Issue by lfvjimisola** [repology/repology-updater#1359]
**Title**

Eclipse Temurin repository for for alpine (apk packages)

**Repository data location(s)**

https://packages.adoptium.net/artifactory/apk/alpine/main
https://packages.adoptium.net/artifactory/apk/alpine/main/<arch>/APKINDEX.tar.gz

RSA key: `https://packages.adoptium.net/artifactory/api/security/keypair/public/repositories/apk`

**Package links**

- **Recipe**:
  - [repo jre](https://github.com/adoptium/installer/tree/master/linux/jre/alpine), [APKBUILD](https://github.com/adoptium/installer/blob/master/linux/jdk/alpine/src/main/packaging/temurin/21/APKBUILD)
  - [repo jdk](https://github.com/adoptium/installer/tree/master/linux/jdk/alpine)
 
- Package page: https://packages.adoptium.net/ui/repos/tree/General/apk/alpine
- Package sources: https://github.com/adoptium/installer
- Issues: https://github.com/adoptium/installer/issues

**Additional details**

Not sure if we filled this in correctly. We filed an [feature request](https://github.com/adoptium/installer/issues/588) with Adoptium but it seems as if we have to ask here instead.

**Comment by AMDmi3** [comment]
Sorry, we don't accept private repositories.

**Comment by lfvjimisola** [comment]
Just to confirm, it's not a private repository.

**Comment by lfvjimisola** [comment]
@AMDmi3 We don't have a workaround for this. Therefore, our hope lies with repology. Is there anyway we can assist for it not be closed as not planned?
