### ISSUE TITLE
[REQUEST]: Bulk requests for Gentoo's packages.gentoo.org

### ISSUE THREAD

**Issue by arthurzam** [repology/repology-updater#1361]
## Background

I'm the maintainer and developer of https://packages.gentoo.org/, a website for viewing important information about packages in the main repository of Gentoo. For a long time we were using repology API for getting list of outdated packages for Gentoo. We are very thankful for this service, and it is a great resource.

Until not long ago, we were using the API using [this API](https://github.com/gentoo/soko/blob/master/pkg/portage/repology/outdated.go#L88) `https://repology.org/api/v1/projects/${CHAR}/?inrepo=gentoo&outdated=1` and it worked. But then it started being blocked, and after various checks, we found out that we failed the [Terms of use](https://repology.org/api/v1). We are sorry for that. Since the moment we understood it, we disabled the cronjob that was syncing it (so we don't make the situation worse).

## Request

We would like to communicate the correct way for us to query repology, and when we fix it, request our server be un-banned.

## Intended Use Case

We intend to query repology once per hour, to get all the matches for `inrepo=gentoo&outdated=1`. We have 2 servers ([production](https://wiki.gentoo.org/wiki/Project:Infrastructure/Servers/Trogan) and [staging](https://wiki.gentoo.org/wiki/Project:Infrastructure/Servers/Towhee)). Based on API endpoint we are instructed to use, add sleep for 1 second (based on TOS instructions).

We are fine with any API you would say is correct :)

Once again, we Gentoo developers want to thank repology for the great service they bring to our users and developers.

**Comment by AMDmi3** [comment]
Could you please set a distinctive user-agent for your crawler? I wouldn't have blocked it in the first place if it identified itself properly.

**Comment by arthurzam** [comment]
Thank you very much. I've updated the backend code (still not enabled the sync cron) in https://github.com/gentoo/soko/commit/2e8046408bdd643cd0b9afe807a009d6d59215a9.

The user-agent has us as source, and an email with which to contact if something weird arises: `"Gentoo Soko %s/packages.gentoo.org/gpackages@gentoo.org"`
And also a rate limiter of 1 request per 2 seconds.

The banned servers are: `trogan.gentoo.org` and `towhee.gentoo.org`.

**Comment by AMDmi3** [comment]
Thank you! I've unbanned these a few days ago
