### ISSUE TITLE
The python:diffusers package wasn't imported from PyPI since November: PyPI has the version 0.24.0 since November, but Repology shows it as 0.23.1

### ISSUE THREAD

**Issue by yurivict** [repology/repology-updater#1367]

**Comment by AMDmi3** [comment]
PyPI API has changed, [fixed](https://github.com/AMDmi3/pypicache/commit/5dbebb9e98ed2e79b992d1299873d57bd40c68f8). `diffusers` package updated, all other packages will be updated withing a few days.
