### ISSUE TITLE
Add serpent os

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#1371]

**Comment by ikeycode** [comment]
Oh thanks bud ! So many out of date packages xD we'll get them updated for prealpha1 !

**Comment by AMDmi3** [comment]
@ikeycode hey, seprentos parsing has been failing for some time due to sanity check failure: https://repology.org/log/8067189. Could you please fix, or is it expected for package name and its directory to differ?

**Comment by ikeycode** [comment]
Ack that's an error. Also please see website/blog we're undergoing rebranding so I imagine some breaking changes to come.

**Comment by AMDmi3** [comment]
Thanks for heads up, will keep an eye on it. I assume the transition for repology should be as easy as updating a few urls?

**Comment by ikeycode** [comment]
Yeah basically. I think github is forwarding uris for the source repo anyway to AerynOS/recipes repo ^^
