### ISSUE TITLE
PureOS package links

### ISSUE THREAD

**Issue by hickford** [repology/repology-updater#1372]
https://repology.org/repository/pureos_landing

> This repository [does not provide](https://repology.org/repositories/fields#pureos_landing) links to package recipes or sources

This might now be possible? I found package links such as https://software.pureos.net/package/src/pureos/landing/git

https://github.com/repology/repology-updater/blob/master/repos.d/deb/pureos.yaml

**Comment by AMDmi3** [comment]
> https://software.pureos.net/package/src/pureos/landing/git

I've added these, but the warning won't go away, as it requires direct links to package sources or recipes.
