### ISSUE TITLE
openmamba: new git based sources repository

### ISSUE THREAD

**Issue by mambasoft** [repology/repology-updater#1377]
Hello,
openmamba package sources are now hosted on a git service at [src.openmamba.org](src.openmamba.org).
The URLs pointing to each source package should be possibly changed to use this scheme:

https://src.openmamba.org/rpms/{source_package}

[Example for glibc](https://src.openmamba.org/rpms/glibc)

There is just an exception for source package names containing a plus sign (+): each occurency of the '+' character should be translated  to 'Plus' in the URL. [Example for libxml++](https://src.openmamba.org/rpms/libxmlPlusPlus)

Many thanks for your great work!

**Comment by AMDmi3** [comment]
Could you please update me on subrepository status: there are multiple subrepositories configured for openmamba: `devel` `devel-games` `devel-makedist` `devel-autodist` `devel-misc` `devel-future`
- some are empty (here `games` and `misc`), should these be removed?
- more are available at https://cdn.openmamba.org/pub/openmamba/, should any of these be added?
- how should links for subrepos other than `devel` (which seems to be the main) generated, as for instance [dasher](https://repology.org/project/dasher/packages) is only available from `devel-future`, and there seem to be no data for it on src.openmamba.org, though spec is available at https://openmamba.org/pub/openmamba/devel-future/specs/dasher.spec

**Comment by mambasoft** [comment]
There have been some changes: `devel` has been renamed to `base`, `devel-games` has been removed, `devel-misc` is currently empty but is still valid.
So the actual list is: `base`, `devel-makedsit`, `devel-autodist`, `devel-misc`, `devel-future` and any other repos should be ignored.

Currently, packages go into src.openmamba.org when they are released to  the `base` repository (every package should end up here in a short or long time), there is no link referencing subrepos. If possibile packages from any repo could be linked to their unique url in src.openmamba.org, `dasher` and other few (3) old packages in devel-future are the only exceptions which might resolve into an invalid url, and I can move them away from there.

Thanks!

**Comment by mambasoft** [comment]
Hi,
I add a comment just to report a URL change for package information pages but if preferable I can open a new issue.

The new pages are available via the following URL scheme:
https://openmamba.org/en/rpms/<repository>/<package>/

Example:
[https://openmamba.org/en/rpms/base/glibc/](https://openmamba.org/en/rpms/base/glibc/)

Here no '+' character conversion is needed, example:
[https://openmamba.org/en/rpms/base/libxml++/](https://openmamba.org/en/rpms/base/libxml++/)

Thanks!

**Comment by AMDmi3** [comment]
@mambasoft why's there no https://openmamba.org/en/rpms/devel-autodist/libepoxy/?

**Comment by mambasoft** [comment]
libepoxy was just imported (2 hours ago) from devel-autodist to devel-makedist, see:
[https://openmamba.org/en/rpms/devel-makedist/libepoxy](https://openmamba.org/en/rpms/devel-makedist/libepoxy/)
