### ISSUE TITLE
"Parabola has caught up with the newest version" spam when Parabola has different versions for different arches

### ISSUE THREAD

**Issue by xiaq** [repology/repology-updater#1380]
After my project Elvish (https://elv.sh https://github.com/elves/elvish) released 0.20.0, I'm seeing a lot of "Parabola has caught up with the newest version" messages on https://repology.org/project/elvish/history

<img width="677" alt="截屏2024-02-13 22 40 36" src="https://github.com/repology/repology-updater/assets/582021/0ce07937-c3ac-418a-a6b3-74a8ea4a227f">

Looking at https://www.parabola.nu/packages/?q=elvish it's apparent that they have only caught up in some arches and lag behind in others:
 
<img width="1159" alt="截屏2024-02-13 22 41 51" src="https://github.com/repology/repology-updater/assets/582021/27694c77-559d-49fd-81c7-142024c4b27c">

I'm not 100% sure, but I suspect what's happening is this:
- When Repology's updater refreshes Parabola's data, it sometimes picks up the 0.20.0 package, sometimes the 0.19.2 package
- If in one refresh it picks up the 0.20.0 package while the last refresh it picked up 0.19.2, a "Parabola has caught up with the newest version" message is generated

**Comment by AMDmi3** [comment]
This was just recently reported as repology/repology-webapp#237 and should be already fixed. The cause was misbehaving mirror.

**Comment by xiaq** [comment]
Thanks!
