### ISSUE TITLE
ibmi: false positives for dead homepage links?

### ISSUE THREAD

**Issue by abmusse** [repology/repology-updater#1381]
Hello!

I've noticed some false positives for dead Homepage links for the ibm i repo

ref: https://repology.org/repository/ibmi/problems

- https://www.gnu.org.ua/software/gdbm/gdbm.html
- https://gmplib.org/

```text
gdbm - Homepage link https://www.gnu.org.ua/software/gdbm/gdbm.html is dead (Connect timeout (60 seconds)) for more than a month and should be replaced by alive link (see other packages for hints, or link to archive.org as a last resort).

gmp-aix - Homepage link https://gmplib.org/ is dead (Connect timeout (60 seconds)) for more than a month and should be replaced by alive link (see other packages for hints, or link to archive.org as a last resort).
```

These links are active and I think these are false positives. Is there a way to remove these as problems or re-run the problem scanner?

**Comment by AMDmi3** [comment]
These are not false positives, I suspect they block traffic from russia.
