### ISSUE TITLE
CRUX not being updated

### ISSUE THREAD

**Issue by TimB87** [repology/repology-updater#1393]
Hi @AMDmi3,

I made a few changes in the firewall config and it seems we are not getting updated. My changes should have no effect on the repology scraper, but I wonder what you can see on your end?

Thanks and best regards,
Tim

edit: sorry for the wrong label, I also can not remove it.

**Comment by AMDmi3** [comment]
I see no problems https://repology.org/repositories/updates

**Comment by TimB87** [comment]
Sorry to bother you then, I was seeing ghosts then :)
