### ISSUE TITLE
NixOS packages not showing

### ISSUE THREAD

**Issue by brettsheffield** [repology/repology-updater#1402]
These packages (librecast, lcrq and lcsync) were added to nixpgs unstable in September 2023 and 23.11 in November, but aren't showing up in repology yet. Should they be? Is there anything we need to do?

https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=librecast

**Comment by AMDmi3** [comment]
These have `version: ""`
