### ISSUE TITLE
Add Azure Linux OS

### ISSUE THREAD

**Issue by arc9693** [repology/repology-updater#1408]
**Title**

Azure Linux 2.0

**Repository data location(s)**

- https://raw.githubusercontent.com/microsoft/azurelinux/blob/2.0/{SPECS,SPECS-EXTENDED,SPECS-SIGNED}/{name}/{name}.spec

**Package links**

- **Recipe**: https://github.com/microsoft/azurelinux/blob/2.0/{SPECS,SPECS-EXTENDED,SPECS-SIGNED}/{name}/{name}.spec
- Package page: https://packages.microsoft.com/cbl-mariner/2.0/prod/{Microsoft,base,cloud-native,extended,extras,nvidia}/,
- Package sources: Per package - Source 0 url
- Issues: https://github.com/microsoft/azurelinux/issues
- Build status: NA
- Build log: NA

**Additional details**

Github repo: https://github.com/microsoft/azurelinux

cc: @mfrw

**Comment by arc9693** [comment]
Requesting feedback from @AMDmi3

**Comment by arc9693** [comment]
Bumping up @AMDmi3

**Comment by AMDmi3** [comment]
This misses a link to repository data.
