### ISSUE TITLE
release-monitoring.org/anitya integration

### ISSUE THREAD

**Issue by Kojoley** [repology/repology-updater#1411]
**Title**

[release-monitoring.org](release-monitoring.org)/anitya

**Repository data location(s)**

- https://infrastructure.fedoraproject.org/infra/db-dumps/anitya.dump.xz (daily full database dump).
- fedora messaging pubsub server with live updates (https://release-monitoring.org/static/docs/integrating-with-anitya.html) (example:  https://apps.fedoraproject.org/datagrepper/raw?category=hotness&delta=2592000).
- https://release-monitoring.org/api/packages/wiki/ (list of all packages in mediawiki format; poor performance + deprecated).

**Package links**

- Package page: https://release-monitoring.org/project/{project_id}/

`package_name` to `project_id` mapping seems to be in `public.packages` table of the database dump.

**Additional details**

- https://github.com/fedora-infra/anitya

**Comment by AMDmi3** [comment]
Apart from that, the data doesn't look usable, it contains duplicates and doesn't allow to tell similarly named packages from each other, especially it doesn't mark python modules as such. Examples:

https://release-monitoring.org/projects/search/?pattern=pyyaml
https://release-monitoring.org/projects/search/?pattern=libversion

**Comment by Kojoley** [comment]
> Apart from that, the data doesn't look usable, it contains duplicates and doesn't allow to tell similarly named packages from each other, especially it doesn't mark python modules as such. Examples:
> 
> [release-monitoring.org/projects/search?pattern=pyyaml](https://release-monitoring.org/projects/search/?pattern=pyyaml) [release-monitoring.org/projects/search?pattern=libversion](https://release-monitoring.org/projects/search/?pattern=libversion)

Ehmmm, isn't there are multiple ways of doing so? `Backend`, `Version check url`, `Homepage`, Distributions mappings?

Only https://release-monitoring.org/project/1800/ has a distribution mappings.

I see how https://release-monitoring.org/project/48867/ and https://release-monitoring.org/project/4123/ could be considered duplicates, though I think it's simply a mistake on their part that the https://release-monitoring.org/project/4123/ has `PyPI` backend instead of `GitHub`.

https://release-monitoring.org/project/372653/ and https://release-monitoring.org/project/372653/ are clearly distinct by `Backend` (and none of them have distribution mappings).

**Comment by AMDmi3** [comment]
I do not plan to implement any complex logic to try to normalize data, and before we even discuss that, there needs to be an easy way to access the data.
