### ISSUE TITLE
list of categories

### ISSUE THREAD

**Issue by vinniec2** [repology/repology-updater#1412]
Is there an all-inclusive list of package categories somewhere?
Sometimes I'm not sure what to put in the search field when I'm looking for a type of package, because I can't think of what the most common keyword would be, it would be handy to be able to look up such a list, maybe even showing the number of packages used in that category.
Thanks

**Comment by AMDmi3** [comment]
Only in database [dumps](https://dumps.repology.org/). Categories come from repositories and each repository uses its own set of categories.

**Comment by AMDmi3** [comment]
Here's a recent list of all known categories: https://gist.github.com/AMDmi3/595fa7d2a5a8b5472d8fe18158d4602a

**Comment by vinniec2** [comment]
Thanks,  is what I was looking for :)

**Comment by AMDmi3** [comment]
> are the categories case sensitive?

Yes
