### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by vinniec2** [repology/repology-updater#1413]
I often find myself searching for packages on repology because it is often more informative than standard channels.
Is there by any chance a tui/gui frontend to consult repology without using the browser?

(sorry , I was doing a research and instead accidentally opened a new issue.
Since I don't see how to delete it I ask a related question)

**Comment by AMDmi3** [comment]
There are no official clients. There are couple of third party ones, for instance search gives https://github.com/elmarco/repolocli and https://github.com/joinemm/sbomnix/blob/main/doc/replogoy_cli.md

**Comment by vinniec2** [comment]
I'll take a look, sorry it took me a while to respond but I have a bit of a memory problem and I remembered when I saw the email!
