### ISSUE TITLE
Blacklist all namespaced categories from nix

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#1414]
This year we've had a few incidents caused by nix, which involved unrelated packages polluting repology projects.

For instance, the latest is caused by https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/package-management/akku/default.nix merged with `postgresql` project. The packages.json entry for it looks like this:

```json
    "akkuPackages.postgresql": {
      "meta": {
        "available": true,
        "broken": false,
        "description": "R7RS portable PostgreSQL binding",
        "homepage": "",
        "insecure": false,
        "license": "noassertion",
        "name": "postgresql-17.9.26",
        "outputsToInstall": [
          "out"
        ],
        "platforms": [
          ...
        ],
        "position": "pkgs/tools/package-management/akku/default.nix:29",
        "unfree": false,
        "unsupported": false
      },
      "name": "postgresql-17.9.26",
      "outputName": "out",
      "outputs": {
        "out": null
      },
      "pname": "postgresql",
      "system": "x86_64-linux",
      "version": "17.9.26"
    },       
```

there's nothing apart from the derivation "namespace" (`akkuPackages`) which we parse as `category` which would tell us that it's not postgresql in fact. Other cases I remember were caused by `nim2Packages` namespace (affected `csvtools` project) and `texlivePackages` (affected `shadow`, `go`, `guitar` and other projects).

So what happens here is nix adds a new category with possibly conflicting package names, and until we add a wildcard rules for it, all conflicting packages are polluted. This should not happen again, so I'm going to handle all unknown categories from nix as `unclassified`. Three mentioned cases suggest that we may likely only ignore categories which fall under `.*Packages` pattern.

**Comment by AMDmi3** [comment]
@jopejoe1 fyi

**Comment by jopejoe1** [comment]
Thanks for the info, will probably go through the sub-package sets in nixpkgs in the next few weeks and see what i could improve.

**Comment by AMDmi3** [comment]
@jopejoe1 you may specifically want to fix `octavePackages` which all currently merge to [octave](https://repology.org/project/octave-unclassified) due to pname parsing problem. Same for `sbcpPackages` (https://repology.org/project/lisp:sbcl). Something looks off for `chickenPackages_5` too.

**Comment by AMDmi3** [comment]
This issues was fixed by these rules:
https://github.com/repology/repology-rules/blob/316033ac79d1f751dc634686ea6f580f24e1a50b/899.version-fixes.global.yaml#L46-L58

**Comment by AMDmi3** [comment]
Related older issue: https://github.com/repology/repology-updater/issues/1226
