### ISSUE TITLE
Re-enable MPR package fetching

### ISSUE THREAD

**Issue by hwittenborn** [repology/repology-updater#1415]
It looks like [MPR package fetching was recently disabled](https://github.com/repology/repology-updater/commit/a12d6416d67361ecf8137f270cf78b89849a6832) from an issue on the MPR, which I wasn't made aware of until earlier today.

I'm not sure how to test if things are good now, but I just pushed some updates to the MPR for some other issues that were occurring. Repology is used in the MPR itself to help update packages, which is reliant on the MPR being present on Repolology. What would be the best path forward for this?

**Comment by AMDmi3** [comment]
```
% curl -s https://mpr.makedeb.org/packages-meta-ext-v1.json.gz | jq | grep u0000 
    "Description": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000R\u0000\u0000\u0000u\u0000\u0000\u0000n\u0000\u0000\u0000 \u0000\u0000\u0000y",
```

**Comment by hwittenborn** [comment]
I wasn't aware that was where the issue was occurring, thanks for letting me know.

I just deployed another fix, which should remove that erroneous behavior. Let me know if things still don't work for you, though.
