### ISSUE TITLE
Ignore Nixpkgs' 0-unstable- prefix

### ISSUE THREAD

**Issue by arthsmn** [repology/repology-updater#1417]
Nixpkgs has a prefix for non-tagged packages, the `0-unstable-`. So, even though the package is up-to-date, the package shows as out-of-date. One example is this package: https://repology.org/project/mpv-sponsorblock-minimal/versions. As you can see, the dates are the same, but the package is flagged as out-of-date.

**Comment by AMDmi3** [comment]
This currently only affects projects which have no official versioning schemes, and it affects all repositories equally. Feel free to submit `noscheme` rules for such projects.
