### ISSUE TITLE
Add `valid_till` date for Rosa linux

### ISSUE THREAD

**Issue by sidt4** [repology/repology-updater#1425]
There is no `valid_till` even for the 2014 release in https://github.com/repology/repology-updater/blob/master/repos.d/rpm/rosa.yaml, hence displaying totally obsolete versions for a package.

Couldn't find EOL in https://en.wikipedia.org/wiki/ROSA_Linux either.

Any way to disable rosa linux from getting displayed in the following list ?

`[![Packaging status](https://repology.org/badge/vertical-allrepos/packagekit.svg?minversion=1.2.0&exclude_unsupported=1&exclude_sources=modules,site&header=Distros+Using+PackageKit)](https://repology.org/project/packagekit/versions)`

[![Packaging status](https://repology.org/badge/vertical-allrepos/packagekit.svg?minversion=1.2.0&exclude_unsupported=1&exclude_sources=modules,site&header=Distros+Using+PackageKit)](https://repology.org/project/packagekit/versions)

**Comment by AMDmi3** [comment]
I've tried to contact Rosa devs through official telegram channel and official support, to no avail. It looks like they are not aware of their own support dates. In accordance to their [docs](http://wiki.rosalab.ru/ru/index.php/Политика_выпуска_ROSA_Desktop), I'm assuming 2 year support.

**Comment by sidt4** [comment]
Okay. Thanks!
