### ISSUE TITLE
Add Astra Linux (Debian Based derivative) to Repology Project

### ISSUE THREAD

**Issue by Dorlas** [repology/repology-updater#1429]
Good day!

Please tell me, is it possible to add support for the Astra Linux project to the Repology project, or more precisely versions 1.7 and 1.8?

Links to repositories and their descriptions:

Astra Linux 1.7
deb https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main/ 1.7_x86-64 main contrib non-free

Astra Linux 1.8
deb https://dl.astralinux.ru/astra/stable/1.8_x86-64/repository-main/ 1.8_x86-64 main contrib non-free

Repo Descriptions:
https://wiki.astralinux.ru/pages/viewpage.action?pageId=3276859
https://wiki.astralinux.ru/pages/viewpage.action?pageId=302043111

**Comment by AMDmi3** [comment]
> deb https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main/ 1.7_x86-64 main contrib non-free

HTTP 403

> deb https://dl.astralinux.ru/astra/stable/1.8_x86-64/repository-main/ 1.8_x86-64 main contrib non-free

HTTP 403
