### ISSUE TITLE
Enable the MPR again?

### ISSUE THREAD

**Issue by taivlam** [repology/repology-updater#1433]
The commit 0cd7aba removed the MPR because the service at the time was returning a 404/Not Found status; but has been back online since about 4 days ago.

Could the MPR please be added back again?

**Comment by AMDmi3** [comment]
It was offline for about a month. Is it even maintained?

**Comment by taivlam** [comment]
* IIRC, this most recent period which the MPR was down was closer to 2 weeks (if not a little less), not 1 month.
* I use the Atom feed from Repology so that I can keep track of what MPR packages I need to update through my feed reader.
* I only maintain some packages on the MPR - only @hwittenborn, the lead maintainer of `makedeb`/MPR project, can speak on the current maintenance status of the MPR.

**Comment by hwittenborn** [comment]
Hey, thanks for the ping.

The MPR is indeed still being maintained. The outage wasn't more than two weeks from the uptime logs I see on my end, though I do completely understand that being quite unacceptable as well. I've been quite busy with school as of recent, and there was an automatic upgrade that brought down the MPR in the midst of that all.

I'm working to make the MPR maintenance process more seamless for others, though that hasn't been completely smoothed out yet. The MPR won't go unmaintained without notice, and I don't plan on that happening any time soon either.

The MPR itself uses Repology to notify maintainers when their packages go out of date as well, so it would be quite beneficial if it could be re-enabled. I know this outage situation reduced confidence on the longevity of the platform, but I can affirm I'll be putting in the work to keep things running. Would it be possible to get things going again with that said?

**Comment by AMDmi3** [comment]
> The outage wasn't more than two weeks from the uptime logs I see on my end

I don't have the whole history, but there's a fetch [attempt](https://repology.org/log/5898071) from aug 23 which failed due to expired certificate, which gave me an idea the outage was longer.

Anyway, it's OK if you say it's still maintained.

**Comment by hwittenborn** [comment]
I believe the expired certificate was due to another misconfiguration on the server, though that much has since been fixed. That was separate from this most recent outage, though yeah, I can see the confusion when all of that is going on pretty soon after each other.

Thanks for adding the MPR back in, I know we all appreciate the flexibility with the situation going on. I'll try to keep you updated if things like this happen in the future, though obviously I'll be trying to ensure this doesn't occur again.
