### ISSUE TITLE
Document LinkType enum

### ISSUE THREAD

**Issue by Pandapip1** [repology/repology-updater#1437]
The documentation for the `LinkType` enum is lacking; it's unclear e.g. when to use `UPSTREAM_HOMEPAGE` vs `PROJECT_HOMEPAGE` vs `PACKAGE_HOMEPAGE`. Would you be willing to explain the nomenclature for the `LinkType` enum? If so, I'd be willing to put together a documentation PR.

**Comment by AMDmi3** [comment]
> If so, I'd be willing to put together a documentation PR.

Sure, that would be welcome. Note though that this code along with documentation will migrate to rust rather soon.

> it's unclear e.g. when to use `UPSTREAM_HOMEPAGE` vs `PROJECT_HOMEPAGE` vs `PACKAGE_HOMEPAGE`

`UPSTREAM_HOMEPAGE` - page dedicated to the given software and maintained by its authors. For intsance, for python Flask it would be https://flask.palletsprojects.com/en/3.0.x/ or https://github.com/pallets/flask/
`PROJECT_HOMEPAGE` - when a project belongs to some official software distribution ecosystem (PyPI for python, crates.io for rust, CPAN for perl etc.), page in that system. For instance, https://pypi.org/project/Flask/
`PACKAGE_HOMEPAGE` - page dedicated to the downstream package, for instance https://archlinux.org/packages/extra/any/python-flask/
