### ISSUE TITLE
please revert disable pkgsrc

### ISSUE THREAD

**Issue by 0323pin** [repology/repology-updater#1443]
Please revert /6abda7b72adb2c14eaafb1325e7e3691b215f82f

The issue causing this has now been fixed.

**Comment by AMDmi3** [comment]
These need to be fixed too:
```
% curl -s https://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/INDEX | awk -F\| 'NF!=12{print}'
gcli-2.2.0nb2|devel/gcli|/usr/pkg|Portable CLI tool for interacting with Git(Hub|Lab|Tea)|devel/gcli/DESCR|tm@NetBSD.org|devel|curl>=7.12.3 libidn2>=2.0.0 libunistring>=0.9.3 libunistring>=1.1 nghttp2>=1.0.0 libxml2>=2.6.2 xmlcatmgr>=2.0beta1 libxml2>=2.10.4nb3 libidn2>=2.3.3nb1 nghttp2>=1.58.0nb1 curl>=8.7.1nb1|curl>=7.12.3 libidn2>=2.0.0 libunistring>=0.9.3 libunistring>=1.1 nghttp2>=1.0.0 libxml2>=2.6.2 xmlcatmgr>=2.0beta1 libxml2>=2.10.4nb3 libidn2>=2.3.3nb1 nghttp2>=1.58.0nb1 curl>=8.7.1nb1|any|any|https://herrhotzenplotz.de/gcli/
go-tcr-1.2.0nb2|devel/go-tcr|/usr/pkg|TCR (Test && Commit || Revert) utility|devel/go-tcr/DESCR|schmonz@NetBSD.org|devel|||*-*-i386 *-*-x86_64 *-*-earmv[67]hf *-*-aarch64|notfor devel/go-tcr not SunOS-*-i386|https://github.com/murex/TCR/
```

**Comment by 0323pin** [comment]
I'll have a look at these in the coming days, too busy right now. I'll let you know when they are fixed.

**Comment by schmonz** [comment]
I've removed `|` characters from both packages' `COMMENT` field and requested that `pkglint` error on these cases.

If there's nothing left standing in the way, please reenable the pkgsrc feed. Thanks!

**Comment by AMDmi3** [comment]
The fix doesn't seem to have propagated to INDEX yet, still I've reenabled the repository - it will reappear after INDEX updates.

Aren't you guys interested in (re)adding quarterly releases (e.g. pkgsrc-2024Q3)? These suffer from the same INDEX problems.
@schmonz @0323pin

**Comment by 0323pin** [comment]
@schmonz so this time were the `|` :o ... I had a look earlier and couldn't figure that.

@AMDmi3 I don't know what @schmonz thinks but, I don't use (or, think too much about) Q-releases. Although, if this gets fixed in current now, it will propagate to the Q4 release.

**Comment by schmonz** [comment]
As a package maintainer, repology's reporting on pkgsrc-current is all I need. (And I rely on it, to help me notice when there are upstream updates to keep up with. Happy to have that reporting back soon :-)

For pkgsrc users, yes, probably helpful to know what's in the quarterly branches. Given a sufficiently motivated pkgsrc developer, we could pull these changes up to 2024Q3. I'm happy if we try to remember to turn on the feed for 2024Q4.
