### ISSUE TITLE
CentOS missing packages

### ISSUE THREAD

**Issue by dabdine** [repology/repology-updater#1446]
Packages such as `libsss_certmap` are missing from the repology dataset. It does exist in the CentOS mirror (https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/libsss_certmap-2.9.4-6.el9.i686.rpm), however.

Looking at the repo file for CentOS, it seems like repology is parsing the source packages instead of the compiled binaries: https://github.com/repology/repology-updater/blob/master/repos.d/rpm/centos.yaml#L151. There is no version of libsss_certmap under the `/source/tree` structure pointed at by the existing repo yaml.

Should the repofile be updated to look at the per-arch repo structure instead?

**Comment by AMDmi3** [comment]
No, Repology parses source packages. You are looking for [sssd](https://repology.org/project/sssd/versions).

**Comment by dabdine** [comment]
> No, Repology parses source packages. You are looking for [sssd](https://repology.org/project/sssd/versions).

That's fair, however `libsss_certmap` is an installable rpm package (https://www.rpmfind.net/linux/rpm2html/search.php?query=libsss_certmap&submit=Search+...).

Should one assume that a package installed on a RHEL system from a standard repo will not necessarily be in repology?

**Comment by AMDmi3** [comment]
Yes, obviously

**Comment by AMDmi3** [comment]
> but that's not the case for centos

That has been fixed. As soon as new data propagates, it should be possible to get to the right Repology project given binary package name in centos via link like this: https://repology.org/tools/project-by?repo=centos_stream_9&name_type=binname&target_page=project_versions&name=libsss_certmap ([a tool](https://repology.org/tools/project-by) to construct these links).

But search by binname is still not implemented (see repology/repology-webapp#111)
