### ISSUE TITLE
Mageia madb have chaged something

### ISSUE THREAD

**Issue by FabioLolix** [repology/repology-updater#1448]
Hello, I was looking into yarock https://repology.org/project/yarock/versions

They have changed something in the last month and the link to the packages page no longer works

* replogy link https://madb.mageialinux-online.org/package/show/source/1/application/0/release/cauldron/name/yarock
* current link https://madb.mageialinux-online.org/show?distribution=cauldron&architecture=x86_64&rpm=yarock&repo=&group=&page=

Also tested with another package strawberry

**Comment by AMDmi3** [comment]
I've used a bit different urls which seem more related to SRPMs.
