### ISSUE TITLE
Add frugalware

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#169]
https://github.com/frugalware/frugalware-current

Need shell parser

**Comment by AMDmi3** [comment]
Actually, there's arch like binary packages database: ftp://ftp5.frugalware.org/mirror/ftp.frugalware.org/pub/frugalware/frugalware-current/frugalware-x86_64/frugalware-current.fdb

**Comment by abucodonosor** [comment]
@AMDmi3 

here is an early package-to-json demo ... is such format ok for you ?

https://bpaste.net/show/6c6e1f888cbe

**Comment by AMDmi3** [comment]
These are per-FrugalBuild, and json structure is mirroring repository directory structure, right? In that case apart from the nested quotes it's good.

**Comment by abucodonosor** [comment]
@AMDmi3 

yes per-FrugalBuild and yes json is then per directory aka per-group .. so you don't even have to care about subpackages. ( ofc we can add the subpackage infos/fields if you wish )

Yes quotes will go away and probably more fields will be added.

**Comment by AMDmi3** [comment]
> ofc we can add the subpackage infos/fields if you wish

This may be useful in future, but currently there's no policy on distinction between source and binary (sub)packages. Probably these still could be useful if they may have different categories.

> Yes quotes will go away and probably more fields will be added.

:+1:
