### ISSUE TITLE
Fix PyPi support

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#278]
PyPi removed their all packages index: https://pypi.python.org/pypi/ so it's no longer parsed. Need to find a replacement

**Comment by FRidh** [comment]
Check out the xmlrpc API:
https://wiki.python.org/moin/PyPIXmlRpc

I use the API here https://github.com/FRidh/make-pypi-dump/blob/1c158f3dda1848c7020f6c0fd4839e32530db5cc/make-pypi-dump#L33

**Comment by AMDmi3** [comment]
It says it's deprecated

> The XMLRPC interface for PyPI is considered legacy and should not be used

and there's no way to get at least names+versions for all packages with a single request. Scraping all 100k+ packages is not an option.

**Comment by FRidh** [comment]
Yet they did implement the methods on the new Warehouse. I wouldn't worry about that, at least not for now. They definitely won't remove that without having an alternative.

**Comment by AMDmi3** [comment]
Still it's useless without a way to get all data with a single request.

**Comment by FRidh** [comment]
>  Scraping all 100k+ packages is not an option.

You could scrape only what has changed, e.g. like I did with the script I referred to. 
The following link contains a dump of all the JSON that is updated daily. It uses the xmlrpc api to determine which packages were changed, and performs requests for those.

If interested, I could update the Travis job to create a file listing all packages along with the latest version.

**Comment by AMDmi3** [comment]
Ok, let me experiment a bit.

**Comment by FRidh** [comment]
This is the link I meant to include https://github.com/FRidh/pypi-dump

**Comment by mgeier** [comment]
PyPI support would be great!

Python packages typically get updated first on PyPI. If the information from PyPI isn't available on repology, the other packages are displayed as "up-to-date" (in green) even though a newer PyPI release is already available.

**Comment by mgeier** [comment]
I think this is a/the relevant issue: https://github.com/pypa/warehouse/issues/347

**Comment by mgeier** [comment]
Would the API for https://libraries.io/pypi help, as suggested by https://github.com/pypa/warehouse/issues/347#issuecomment-373251938?

**Comment by AMDmi3** [comment]
Thanks for the pointer, I'll investigate this. I already don't like that it requires registration though.

**Comment by nemaniarjun** [comment]
Any updates on this?

**Comment by AMDmi3** [comment]
Unfortunately, libraries.io is not suitable - I've commented in warehouse issue.

There's still no way to fetch information on all PyPi packages.

**Comment by AMDmi3** [comment]
And I've investigated method suggested by @FRidh - while inconvenient (needs a lot of time to bootstrap and persistent storage) and incomplete (only supplies versions), it could work as a temporary solution (use `list_packages` xmlrpc method to get all package names, scrape them with `package_releases` by one on first run, then only use `changelog` to get updates), but the problem is that `changelog` method doesn't differentiate stable and developer releases. So the changelog will supply data like

```
>>> [i for i in client.changelog(1528310115-3600) if i[0] == 'toil-vg']
[['toil-vg', '1.4.1a1.dev1044', 1528309044, 'new release'], ['toil-vg', '1.4.1a1.dev1044', 1528309044, 'add source file toil-vg-1.4.1a1.dev1044.tar.gz'], ['toil-vg', '1.4.1a1.dev1044', 1528309045, 'add 2.7 file toil_vg-1.4.1a1.dev1044-py2.7.egg']]
```

while the stable version is like

```
>>> client.package_releases('toil-vg')
['1.2.0']
```

**Comment by ackalker** [comment]
@AMDmi3 There may yet be a a workable solution for getting at least a list of all package names: parsing the HTML returned by https://pypi.python.org/simple/
If anything, retrieving it is _fast_. On my machine (with GbE internet connection):
```sh
$ time curl 'https://pypi.org/simple/' -o out.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9478k  100 9478k    0     0  30.4M      0 --:--:-- --:--:-- --:--:-- 30.3M

real	0m0.315s
user	0m0.048s
sys	0m0.045s
```
Sample snippets of the content:
```
$ head out.html 
<!DOCTYPE html>
<html>
  <head>
    <title>Simple index</title>
  </head>
  <body>
    <a href="/simple/0/">0</a>
    <a href="/simple/0-0/">0-._.-._.-._.-._.-._.-._.-0</a>
    <a href="/simple/0-0-1/">0.0.1</a>
    <a href="/simple/00print-lol/">00print_lol</a>
```
```
$ tail out.html 
    <a href="/simple/zzr/">zzr</a>
    <a href="/simple/zzyzx/">zzyzx</a>
    <a href="/simple/zzz/">zzz</a>
    <a href="/simple/zzzeeksphinx/">zzzeeksphinx</a>
    <a href="/simple/zzzfs/">zzzfs</a>
    <a href="/simple/zzzutils/">zzzutils</a>
    <a href="/simple/zzz-web/">zzz-web</a>
    <a href="/simple/zzzzzzzzz/">zzzZZZzzz</a>
    </body>
```
I hope this can be of some use, but I have no idea whether and how long this feature will remain available. I do think it is a good workaround, and hope to see full PyPI support in Repology return soon :-)

**Comment by AMDmi3** [comment]
@ackalker unfortunately, none of this is usable.

**Comment by ackalker** [comment]
That's too bad. Could you please explain what is missing with this approach? I would guess it is at least usable for bootstrapping (getting the initial list of package names and available versions). Given it's speedy transfer, the list page could even be useful for quickly spotting package additions/removals.

**Comment by AMDmi3** [comment]
- Doing a HTTP request per package is not acceptable
- Version information has to be extracted from file names, I don't think it's reliable
- Stable/unstable distinction is missing

**Comment by ackalker** [comment]
Thanks for the explanation.
Please see pypa/warehouse#2912 for more recent upstream discussion, JSON API.

**Comment by AMDmi3** [comment]
That issue was closed a year ago. And I doubt an API would be of any help, as APIs usually do not provide bulk data access (and as mentioned before, doing a lot of requests is not acceptable). Topology needs a _dump_ .

**Comment by abitrolly** [comment]
https://packaging.python.org/guides/analyzing-pypi-package-downloads/ - can that help? BigQuery most likely requires registration and there are some limits.

**Comment by AMDmi3** [comment]
It needs google account. This is not acceptable.

**Comment by davidak** [comment]
The data is soon accessible under the `the-psf.pypi.distribution_metadata public` dataset on BigQuery.

https://github.com/pypa/warehouse/issues/7403#issuecomment-663131927

>It needs google account. This is not acceptable.

So you need a JSON export? Would daily be OK? I fear the traffic alone would be a problem for hourly.

**Comment by AMDmi3** [comment]
Since there's currently no PyPI support at all, any update frequency would be OK.

**Comment by davidak** [comment]
@AMDmi3 would it be acceptable for you to use [kaggle](https://www.kaggle.com/)?
You need an account to download datasets from there, but you can create one with e-mail and password. It's owned by Google.

**Comment by AMDmi3** [comment]
No, google crap which requires registration would definitely not be acceptable.

**Comment by abitrolly** [comment]
What is the size of the index?

If it is too big to be hosted on CDN, then maybe with JSON API it is possible to update once and then subscribe to updates?

**Comment by pradyunsg** [comment]
> Version information has to be extracted from file names, I don't think it's reliable

Just wanted to hop in to say -- it is. pip also relies on this information and shouts at the user if things don't match.

**Comment by AMDmi3** [comment]
Close as there's nothing to do here on repology side until PyPI or someone publishes an usable index.

**Comment by abitrolly** [comment]
1. Get the size of index
2. Speak with Fastly
3. Setup sync script

PyPi is not a person and can not do the steps above.

**Comment by AMDmi3** [comment]
PyPI is maintained by people, and it's their work to make it accessible, especially after they broke it by removing the index. I'm definitely not doing it for them.

**Comment by abitrolly** [comment]
@AMDmi3 I am sure that nobody works at PyPI.

**Comment by AMDmi3** [comment]
I've had to do PyPI developers' work after all, as PyPI data is too important for Repology users.

I've set up a dedicated service at https://pypicache.repology.org/ which talks to PyPI via APIs and updates metadata on packages which were recently changed. I've also populated it with PyPI modules already present on Repology so it should be fairly complete for the task.

**Comment by abitrolly** [comment]
@AMDmi3 looks awesome. )

> An endpoint to get information on individual project - not suitable as it requires thousands of HTTP requests to fetch data on all packages.

I am afraid https://release-monitoring.org/ does just that. :D @Zlopez can tell more.

**Comment by Zlopez** [comment]
Yes, we are doing this. We are trying to check each project once in a hour. And as @AMDmi3 is saying there are thousands of HTTP requests each hour.

You can check how many projects were checked in last run at the bottom of https://release-monitoring.org/ page.

**Comment by abitrolly** [comment]
@Zlopez there is no [API](https://stg.release-monitoring.org/static/docs/api.html) to get all data on PyPI projects for comparison, right?

**Comment by Zlopez** [comment]
There is https://anitya.readthedocs.io/en/stable/api.html#http-api-v2 You just need to specify the ecosystem for `/api/v2/projects/` GET request.

**Comment by abitrolly** [comment]
API query returned 91754. https://pypicache.repology.org/ reports 26796 packages.

**Comment by AMDmi3** [comment]
> I am afraid https://release-monitoring.org/ does just that

It's not really suitable for Repology. 
- it doesn't contain all python packages present in Repology 
- it doesn't provide enough data on each package (homepage, downloads, author, summary etc.) 
- pypicache provides smaller lag and easier access to data

> We are trying to check each project once in a hour

I don't think there's a point in that since PyPI has xmlrpc endpoint which returns projects changed since given timestamp and allows one to only recheck updated projects with a lot smaller lag without skipping any updates. I still have to confirm that there haven't been any lost updates though.

> API query returned 91754. https://pypicache.repology.org/ reports 26796 packages.

As mentioned, these 26k fully cover Repology needs. If there's demand, it can pull in all 274k pypi packages.

**Comment by abitrolly** [comment]
Interesting coincidence that at the same day when Google Big Query went offline, PyPI XML-RPC started to experience overload. But Google incident was reported 12:07 UTC and PyPI report is dated 09:41 UTC.

![image](https://user-images.githubusercontent.com/8781107/102581402-8b2a8080-4111-11eb-80bd-368729973b9b.png)

Interesting that Atlassian Statuspage used by https://status.python.org/ doesn't highlight the incident in the log in any way.

![image](https://user-images.githubusercontent.com/8781107/102581872-7995a880-4112-11eb-9917-eeb765c62b15.png)

**Comment by swills** [comment]
> Interesting coincidence that at the same day when Google Big Query went offline, PyPI XML-RPC started to experience overload. But Google incident was reported 12:07 UTC and PyPI report is dated 09:41 UTC.

This seems like the wrong place to report this issue.

**Comment by abitrolly** [comment]
I was just curious to check if the reason for PyPI XML-RPC were people who've lost access to BigQuery and needed alternative way to gather the same stats.
