### ISSUE TITLE
Add more openSUSE repos

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#280]
See:

http://download.opensuse.org/repositories/
https://en.opensuse.org/Additional_package_repositories

**Comment by kingthorin** [comment]
Agreed, quoting the report here: https://repology.org/metapackage/zaproxy/report

> Comment:
> As you can see here the coverage provided by the OpenSuse package is quite extensive across other platforms (OpenSuse, CentOS, Debian, Fedora, RHEL, xUbuntu, etc):
> https://build.opensuse.org/package/show/home:cabelo/owasp-zap 

> Repology reply:
> I've merged some of "zap" packages into "zaproxy", otherwise this report refers to repositories not supported by repology 

How about: https://software.opensuse.org/package/owasp-zap which is probably more central/official than the build link I'd provided in the quoted report.

**Comment by AMDmi3** [comment]
Some repos have been added, other may be added on request.
