### ISSUE TITLE
Puppy Linux

### ISSUE THREAD

**Issue by Symbian9** [repology/repology-updater#324]
FAQ
* http://puppylinux.org/wikka/software
* http://puppylinux.org/wikka/SoftwareIndex

Repositories
* http://puppylinux.org/wikka/Repositories
  * http://distro.ibiblio.org/puppylinux/
  * ...

TODO
* https://github.com/repology/repology/issues/166

REFERENCE:
* http://puppylinux.org/
* https://github.com/puppylinux-woof-CE
* http://www.murga-linux.com/puppy/index.php

**Comment by AMDmi3** [comment]
No suitable package metadata found
