### ISSUE TITLE
Add Chakra linux support

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#327]
https://chakralinux.org/
https://chakralinux.org/code/

~~needs shell parser~~
Need package metadata dump

**Comment by luzpaz** [comment]
Posted a [forum thread](https://community.chakralinux.org/t/repology-and-chakralinux/7999) to the chakralinux community about this ticket

**Comment by luzpaz** [comment]
Hi @AMDmi3 
What kind of assistance do you need from upstream?

**Comment by AMDmi3** [comment]
A parsable (e.g. JSON), regularly updated dump of all package data (package name, version, and optionally one line summary, maintainer(s), categorie(s), license(s), homepage and download url(s).

**Comment by luzpaz** [comment]
@AMDmi3 do you have an example JSON file I can look at, in respect to how you'd like the data to be dumped ?

**Comment by AMDmi3** [comment]
I guess it's time to write a documentation page for this.

**Comment by AMDmi3** [comment]
Please track status of #647.

**Comment by AMDmi3** [comment]
Documentation done: https://repology.org/addrepo.

**Comment by AMDmi3** [comment]
It turns out that chakra has repository in Arch format, though it took time to look for it on their site.
