### ISSUE TITLE
opencsw support?

### ISSUE THREAD

**Issue by sitsofe** [repology/repology-updater#367]
There seems to be an old (Sun-era?) Solaris package repository over on https://www.opencsw.org/about/ . I'm not a Solaris user myself but it is seemingly still getting new packages...

**Comment by AMDmi3** [comment]
It's suitable for repology, but I didn't find any machine readable dump of source package information. We won't be parsing Makefiles.

**Comment by AMDmi3** [comment]
Otoh, https://www.opencsw.org/get-it/packages/ looks usable

**Comment by AMDmi3** [comment]
Unfortunately, no - these are (split) binary packages not suitable for repology.

**Comment by AMDmi3** [comment]
No usable package metadata dump.
