### ISSUE TITLE
Add MidnightBSD mports

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#422]
Site: http://app.midnightbsd.org
- `http://app.midnightbsd.org/api/category` - list categories
- `http://app.midnightbsd.org/api/package/category/{category}` - list packages for a category

Nice json format, easy to parse

**Comment by AMDmi3** [comment]
JSON format has problems with categories. For instance, `wayland` has moved from `x11-servers` to `graphics` there are now two entries, and it's impossible to tell which is the correct category to generate packagelink. 

Alternatively, there's also sqlite3 database for binary packages http://index.mport.midnightbsd.org/amd64/1.2/index.db.bz2 which contains port name bindings as well, but it lacks urls.

**Comment by laffer1** [comment]
I've created a new endpoint in our package build cluster software that might work for you.  

http://www.midnightbsd.org/magus/api/latest

It should grab the latest versions by architectures, merge the list together and also populates flavors as subpackages.
