### ISSUE TITLE
single representative of fresh packages for clones?

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-updater#514]
I've been watching manjaro testing and manjaro unstable for months.  They are normally identical, or at worst differ by a couple of packages.  For the purposes of statistics, they are clones.

There are only 8 slots in the "percentage of fresh packages" scoreboard on the front page.   It doesn't seem fair that manjaro takes up 2 slots with virtually identical repositories.

My suggestion is have the ability filter out certain repositories for the purposes of these scoreboards, and filter out manjaro testing.  Free up a spot so the current 9th place repository gets on the board.

A deeper question is whether 2 such similar repositories should be registered at all, but I'll assume that you deem it worthwhile.  It appears they are synced together frequently, e.g. daily or multiple times daily.

**Comment by AMDmi3** [comment]
Sure, this is long planned (#409), but I still haven't decided the best way to do it.

**Comment by AMDmi3** [comment]
An idea is to split repository `name` into `name` + optional `variant`, e.g. `Ubuntu` + `18.10 Backports`, `Arch` + `Testing`, `FreeBSD ports` + <none>. These would just be concatenated when shown on the site, but also allow more complex handling for grouping purposes. This does not handle derivatives (e.g. Ubuntu/Debian) yet, but should be a nice start.
