### ISSUE TITLE
Add info on patches

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#53]
Some repos include patches, it would be nice to report them upstream.

**Comment by alexws54tk** [comment]
Часть патчей, например в Генту, специфичны и необходимы лишь для корректной сборки пакета.

**Comment by AMDmi3** [comment]
Yes, same with FreeBSD. I can't think of a way to sort this out automatically, but this still is a useful info. A bit heavy to retrieve though.

**Comment by alexws54tk** [comment]
There is a sentence simply to specify existence of patches for a packet.
And there can be as we will invent … (=

**Comment by AMDmi3** [comment]
What I've meant is that while the information on patches is easily retrievable for e.g. Gentoo (as we already have the whole repository and all we need is to look into ```files/``` for each package), for other repos it's not that trivial - for instance, we only retrieve single INDEX file for FreeBSD now, but in order to discover patches we'll have to get whole ports repository and parse it as well. Even more complex for other repos. It may be done gradually though.

**Comment by alexws54tk** [comment]
> we need is to look into files/ for each package

We also need to look into `Manifest` file and in `.ebuild`.
In `Manifest` listed ALL files for package. In `.ebuild` patches maybe listed in **`${PATCHES}`**, **`${EPATCH_*}`** and **`${SRC_URI}`** variables and still somewhere.

**Comment by AMDmi3** [comment]
> We also need to look into Manifest file

Why? It just lists checksums.

> and in .ebuild

Yes, but it looks to be more complex. For example, app-emacs/teco, uses ```${ELISP_PATCHES}```, in which it references other variable.

**Comment by alexws54tk** [comment]
Emacs, this separate, it is written on Lisp therefore plugins to it so collect, mostly.
This that still a some magic to rake `.eclasses` from `/path/to/portage/tree/eclasses` folder which use `.ebuilds` from «inherit … keyword».

**Comment by AMDmi3** [comment]
This is supported by package-specific links
