### ISSUE TITLE
Merge unsupported repos into master

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#532]
There's a bunch of unsupported repos in separate branches (npack, anitya, fink, free software directory, maybe more). Better to merge them to trunk, disabled, so the code is not lost and they can be experimented with anytime.

- [x] fink
- [x] free software directory
- [ ] maui/netrunnet
- [ ] midnightbsd
- [ ] anitya
- [ ] elive
- [ ] unixpackages
- [ ] easybuild/spack

**Comment by XVilka** [comment]
Are there any updates on Fink?

**Comment by AMDmi3** [comment]
> Are there any updates on Fink?

No

**Comment by AMDmi3** [comment]
Rather, let's not keep the garbage in the repository.
