### ISSUE TITLE
Autoignore more fedora releases

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#575]
Even with #559 fixed, there are cases where Fedora violates its [rules](https://fedoraproject.org/wiki/Packaging:Versioning#Prerelease_versions) and does not start `release` field with zero for pre-release versions. Here's recent example: [perl](https://apps.fedoraproject.org/packages/perl/changelog/) and there are also related ignore rules left in the ruleset. It seems that we need a more pessimistic approach, at least looking for rc/alpha/beta patterns in the `release` field, at most ignoring everything not matching the safe `release` field pattern of `[0-9]+.fc[0-9]+`

@ppisar Hi, could you please give a comment? In short, we need to distinguish pre-release versions from actual releases. It's pretty hard with RPM-based repos, as they tend to remove alpha/rc/betaN suffixes from `version` field and place them into `release` field which is not really parsable. There are [guidelines](https://fedoraproject.org/wiki/Packaging:Versioning#Prerelease_versions) which require `release` field to start with zero for pre-releases, however this rule doesn't seem to be followed strictly. Any ideas how this can be solved in a better way than described above? Maybe guideline violations are worth reporting?

**Comment by ppisar** [comment]
On Sun, Apr 01, 2018 at 10:09:35PM +0000, Dmitry Marakasov wrote:
> Even with #559 fixed, there are cases where Fedora violates its
> [rules](https://fedoraproject.org/wiki/Packaging:Versioning#Prerelease_versions)
> and does not start `release` field with zero for pre-release versions.
> Here's recent example:
> [perl](https://apps.fedoraproject.org/packages/perl/changelog/)

I know about the rule and I broke it intentionally.

perl.spec produces binary packages that have independend version numbers. To
ensure full version string, so called NEVRA, never decreases, perl.spec's
Release value cannot never be reset to 0. Thus even perl release candidate
Release cannot ever start with 0 number.

> In short, we need to distinguish pre-release versions from actual releases.

You cannot. There is no programatic way of doing that. Whether something is
a prerelease only author knows. E.g. glibc is glibc-2.27.9000-13.fc29 now.
In fact it's a 2.28 prerelease.

-- Petr

**Comment by AMDmi3** [comment]
That's unfortunate. Seems like we'll have to use more handwork and heuristics. Thank you for explanation!

**Comment by AMDmi3** [comment]
- CentOS
- 0.12-0.37.pre6.el7 (0.12pre6)

Just some samples:
```
0.5.alpha2.el7
0.5.b3.el7
0.5.git20130619.a1d9681.el7
0.5.git3454319.el7
0.54.el7
0.6.20120212git76e1a2.el7
0.6.b10.4.el7
0.65.el7.centos.2
0.7.20120212git2fabd8.el7
0.7.alpha11.el7
0.7.beta7.el7
0.7.dev.el7
0.7.git269f928.el7
0.7.r12.el7
0.8.20120119svn.el7
0.8.20120120svn.el7
0.8.Beta2.el7
0.8.svn234.el7
0.9.20080714svn.el7
0.9.20120319git49a904.el7
0.9.20120407git0deb9c.el7
0.9.hg74691fb6f837.el7
0.el7
0.el7_5
1.1.1.el7
1.1.el7
1.13.13.1.el7_3
1.2.1.el7_5
1.3.1.el7_5
1.3.el7
1.a2.25.el7
1.dev.gitae64ff7.el7.centos
1.dev.gitb08350d.el7
1.el7
1.el7.centos
1.el7_1
1.el7_3
1.el7_4
1.el7_4.1
1.el7_5
1.el7_5.1
```

**Comment by AMDmi3** [comment]
## EPEL
```
0.7.alpha9.el7
0.7.beta2.el7
0.7.git20170912.7cb788c.el7
0.7.git287b434.el7
0.7.gita8b3385.el7
0.8.20140510svn7747.el7
0.8.20140920git1edbe523.el7
0.8.20181018git212cb79.el7
0.8.a9.el7
0.8.b4.el7
0.8.git8373c9f.el7
0.8.rc1.el7
0.8.rc5.el7
0.9.20120406git.el7
0.9.20140530.el7
0.9.alpha1.el7
0.9.b3.el7
0.9.b5.el7
0.9.beta1.el7
0.9.beta2.el7
0.9.beta7.el7
0.9.el7
0.9.git75cd24fc2f2c.el7
0.9.git792786c.el7
0.9.gitd228c1a.el7
0.RC1.2.el7
0.el7
03.18.el7
1.0.hgd32b5854c941.el7
1.1.20180101git9b59468.el7
1.1.20180504cvs.el7
1.1.el7
1.1.el7.2
1.1lsb3.2.el7
1.2.el7
1.20140212git7fea071.el7
1.20140522gitad6fb3e.el7
1.20140613cvs.el7
1.20141016git3b33a5a.el7
1.20141205git858edfe.el7
1.20151118gitf4d2682.el7
1.20170717git35b742d.el7
1.20171024gita812520.el7
1.20171225git60ea749.el7
1.20180106.el7
1.20180306gite986688.el7
1.20180605gitcd8d91c.el7
1.20180919git21ae32a.el7
1.2bc722agit.el7
1.el7
1.el7.0
1.el7.1
1.el7.2
```

**Comment by AMDmi3** [comment]
## Fedora
```
0.9.git20160309.597ce9f.fc29
0.9.git51ad441.fc29
0.9.git83b52d7.fc27
0.9.git85041cd.fc29
0.9.gita085181.fc29
0.9.gitb15639c.fc29
0.9.gitc7bacac.fc29
0.9.gitdc507ad.fc29
0.9.gite7603b0.fc29
0.9.hgc3294304d93f.fc27
0.9.rc1.fc29
0.9a4.fc30
0.9gitfe0f368.fc29
0.a3.3.fc29.1
0.a3.fc30.11
0.beta1exp2.fc29
0.beta2.fc29.15
0.e64ff9.fc29.13
0.fc29
0.fc30
0.fc30.1
0.fc30.20180816
0.gitd32d9973.1.fc29.3
0.rc1.2.47815c2.fc29.5
0.rc1.fc28.1
0.rc5.git0.1.fc30
0.rc5.git3.1.fc30
1.1.20180101git9b59468.fc30
1.1.20180504cvs.fc29.1
1.1.fc29
1.1.fc29.3
1.20160208git8c278ef.fc24
1.20180520git66bb071.0.fc29
1.20180623svn9962.fc29
1.20180717git0003eff.fc29
1.20180719cvs.fc29
1.20180806gita7e4d91.fc30
1.20180806gite694813.fc30
1.20180829git4df5ca1.fc30
1.20180914gita654f6f.fc30
1.20180919git21ae32a.fc30
1.20180919git402c22886.fc30
1.20180921git7e801b5.fc30
1.20181006gitb2de0cb.fc30
1.20181006gitef6db91.fc30
1.20181026gitfe5e611.fc30
1.20181107git029717b.fc30
1.20181107gitfd1a5a5.fc30
1.20181112gitf9ffefc.fc30
1.20181114git0bd5694.fc30
1.20181120git0e0ff3a.fc30
1.20181129git19d6db1.fc30
1.20181129gitd86462c.fc30
```
