### ISSUE TITLE
Adding support for LTS version markers

### ISSUE THREAD

**Issue by awilfox** [repology/repology-updater#691]
I was wondering if there would be any hope of merging an additional version marker for LTS releases.  For instance, Adélie only ships Firefox ESR, so we'll only show "newest" every six versions.  But that is not outdated.  Similar with KDE Plasma 5: they have 5.12, which is LTS, and 5.13 and 5.14, which are unstable.

Obviously, the non-ESR versions of Firefox are not "unstable" so to speak, but shipping the LTS version only does not mean that the package is out of date.

**Comment by awilfox** [comment]
I've just noticed that another large chunk of packages marked "outdated" on Adélie's repo is Qt.  This would also benefit from a "LTS" version marker.

Qt 5.9.6 is the newest stable.  I would not call 5.10 or 5.11 "stable".  I would barely qualify them as beta.  Note that 5.9 is considered the "LTS" branch.  The number of regressions, both in performance and crashes - for both 5.10 and 5.11, is astronomical.

**Comment by AMDmi3** [comment]
It is planned in somewhat more flexible form of 'branches' which would allow more than one of them. E.g. postgresql 9.4, 9.5, 9.6, 10 with possible latest version in each of them.

However the main purpose of that would be showing more versions as outdated, not newest (e.g. postgresql versions 10.5, 9.6.9 in a single repo show as newest/legacy currently, while it should be newest/outdated as there's newer 9.6.10 in 9.6 branch). Overall philosophy of repology is centered around helping repositories ship fresh and actual software and I don't plan to gratify forcing users to legacy versions. These are still somewhat tolerated, as they are not reported as outdated if a newer version is also shipped, and IMO that's quite enough.

**Comment by awilfox** [comment]
That choice doesn't benefit users when packagers don't have the time to maintain a stable and unstable branch of entire swaths of software.  KDE Plasma is nearly 50 packages.  Qt is 30, and each bump of Qt affects hundreds and hundreds of packages; 5.11 in particular had a lot of breaking changes that caused many software packages to be unbuildable or worse, unusable.  Firefox is a moving target.  Sure, there are corporate backed distros like Red Hat and Ubuntu that can put that manpower together, but smaller distros like us don't have that time.

Put another way: Yes, having that choice can benefit users.  But some users (and distros) make the *choice* to only ship LTS.  And showing that a distro ships the latest LTS software, even if it doesn't appear as "Newest", can help users that are making that choice.  It also helps adoption of open source software for people and organisations (corporations, non-profits, hospitals, ...) that want something that is not going to have new features and a new design every single time they update every month.
