### ISSUE TITLE
Consistent snapshot version handling

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#920]
I'm puzzled each time I have to handle snapshot patterns in some new repository, so there's a need to at least decide on consistent way to handle them.

How should we represent a snapshot version to the user?
  - Debian may have `1.2.3~beta1~20110101`, should the date be included into user visible version?
  - RPM distros may have version `1.2.3` revision `1.beta1.20110101`, should date be added to the version?
  - GUIX may have `1.2.3-0.a1b2c3d` or `1.2.3-1.a1b2c3d` (which are ordered differently against `1.2.3` btw.)
  - Other distros may have e.g. `1.2.3.20110101`

Do we always include snapshot information? Do we always remove snapshot part? How do we deal with ordering? To what extend do we want to encourage distros to switch to consistent scheme? To which one?

Related: #345 #218 #811 #575.

**Comment by holgersson32644** [comment]
As far as I see it snapshots are used when upstream does not create proper releases or does not yet do so, i.e. the package is younger than the youngest official release from upstream.
That’s my perspective running Gentoo and maintaining some packages here.

Therefore I propose you keep the date visible to the user (and maybe link to a FAQ explaining these strange bunch of numbers to new Linux users).

**Comment by AMDmi3** [comment]
I don't think I'm going to work on this. Recently I've improved handling of RPM and Debian versions, now less garbage is stripped, and the current policy is to mark snapshots with versions greater than the latest official as ignored and snapshots with versions lesser than latest official are automatically outdated. Incompatible snapshot schemes (e.g. 2021-01-01 when upstream uses X.Y.Z) are always marked incorrect.
