### ISSUE TITLE
Please add support for the MX 19 main and testing repositories, as it's being released.

### ISSUE THREAD

**Issue by stevenpusser** [repology/repology-updater#935]
The repo URLs are the same as for the MX 17 Stretch-based ones, except the word "stretch" is replaced with "buster". 

Thanks!

**Comment by AMDmi3** [comment]
Does it make sense to use numeric versions (17, 19) in repository names, or is it better to stay with codenames? I've seen the announces, and it seems to me that numeric versions are more widely used/known.

**Comment by stevenpusser** [comment]
I'd follow something like Mint's lead and use the numeric versions instead of the Debian codenames.  I don't see anything like "xenial" in the Mint 18 results, for instance, though it's using those repos.

**Comment by stevenpusser** [comment]
I'd follow something like Mint's lead and use the numeric versions instead of the Debian codenames.  I don't see anything like "xenial" in the Mint 18 results, for instance, though it's using those repos.
