### ISSUE TITLE
Wrong parsing of nixos unstable packages

### ISSUE THREAD

**Issue by prusnak** [repology/repology-updater#941]
Example: https://repology.org/project/trezor-udev-rules/versions

UI says the package name is `trezor-udev-rules-unstable` and version is `2019-07-17` while in reality, the package name is `trezor-udev-rules` and version is `unstable-2019-07-17` as can be seen here:

https://github.com/NixOS/nixpkgs/blob/b5ac99fe007409a06ef02bc629a9885e0f38154f/pkgs/os-specific/linux/trezor-udev-rules/default.nix#L4-L5

**Comment by AMDmi3** [comment]
Nix problem. #854

**Comment by AMDmi3** [comment]
Also NixOS/nixos-homepage#306
