### ISSUE TITLE
Add opensource.apple.com

### ISSUE THREAD

**Issue by Necklaces** [repology/repology-updater#943]
Could we discuss if it would be possible to add https://opensource.apple.com/ ?

Useful to see what packages come and go, for example for the [latest version of macOS](https://opensource.apple.com/release/macos-10145.html)

It looks like they also have files we could parse
- .plist files: https://opensource.apple.com/plist/macos-10145.plist
- custom .txt files: https://opensource.apple.com/text/macos-10145.txt

I might start working on a PR unless there are any objections.

**Comment by AMDmi3** [comment]
This doesn't look usable - versions have nothing to do with upstream.

**Comment by Necklaces** [comment]
Hm yeah, shame. One could use those "versions" to further get the link for the specific directory. So, for example:

Curl is listed as:
```
<key>curl</key>
<dict>
<key>version</key>
<string>105.200.2</string>
</dict>
```

Then, we go here to find the source code for that "version" (build or distribution, I guess) of curl: https://opensource.apple.com/source/curl/curl-105.20.2/curl.plist

There, the actual version number is properly listed as 

```
<key>OpenSourceVersion</key>
<string>7.54.0</string>
```

Of course, that means another GET request for every single entry, and I'm guessing that's a no-no?

**Comment by AMDmi3** [comment]
> There, the actual version number is properly listed as

Oh, this looks much better. Especially that it does contain other info such as homepage and download URLs.

> Of course, that means another GET request for every single entry, and I'm guessing that's a no-no?

That depends on how many requests needs to be done, and as there are about 200 packages it should probably be OK, at least for now.

However, not all projects have directly accessible plists, for example:

https://opensource.apple.com/source/vim/vim-70.220.1/
https://opensource.apple.com/source/python/python-109.200.2/
https://opensource.apple.com/source/perl/perl-113.261.1/
https://opensource.apple.com/source/python_modules/python_modules-46.200.1/

**Comment by Necklaces** [comment]
I've also found some inconsistencies, so some projects have `packagename.plist`, and others have `Info.plist`.

Seems for some (those you list) have plists hidden in subdirectories:

https://opensource.apple.com/source/vim/vim-70.220.1/local/vim.plist
https://opensource.apple.com/source/python/python-109.200.2/2.7/python.plist
https://opensource.apple.com/source/perl/perl-113.261.1/5.18/perl.plist

And never the same sudirectory, of course.. sigh

However those python modules does indeed not have a plist, but I guess we could parse this: https://opensource.apple.com/source/python_modules/python_modules-46.200.1/2.7.inc

They also seem to have 'partials': https://opensource.apple.com/source/python_modules/python_modules-46.200.1/Modules/altgraph-0.10.2/altgraph.partial

But that's a whole lot of work and a whole lot of inconsistencies. I'm sure there are more.

**Comment by AMDmi3** [comment]
Well, yes. I'd prefer to not have overcomplicated parsers based on heuristics and/or parsers which can miss some information. Otherwise it could work.

**Comment by AMDmi3** [comment]
So, I don't see workable solution for this now.
