### ISSUE TITLE
FreshFOSS

### ISSUE THREAD

**Issue by davidak** [repology/repology-updater#947]
distrowatch.org links to https://freshfoss.com/

The site design looks like an abandoned project with lots of ads, but the data is actually up-to-date.

License is CC-BY-SA

The RSS-Feed has only a few entries: https://freshfoss.com/feeds/freshfoss.rss

Not sure if we can fetch all the data somehow.

Might be interesting where they get their data from.

There are no contact details on the site.

Nothing was posted on their Twitter in a long time: https://twitter.com/FreshFOSS

**Comment by luzpaz** [comment]
freshfoss.com is a clone of freshcode.club which is a source that repology pulls from already https://repology.org/repository/freshcode.

Ticket can be closed
