### ISSUE TITLE
Add Euler OS and Inspur K-UX

### ISSUE THREAD

**Issue by XVilka** [repology/repology-updater#959]
[EulerOS](https://en.wikipedia.org/wiki/EulerOS) is a commercial Linux distribution developed by Huawei Technologies based on CentOS for enterprise applications. It is one of six commercial operating systems that have versions certified to The Open Group's UNIX 03 standard.

https://developer.huaweicloud.com/en-us/euleros/euleros-introduction.html

[Inspur K-UX](https://en.wikipedia.org/wiki/Inspur_K-UX) is a Linux distribution based on Red Hat Enterprise Linux produced by Inspur, a Chinese multinational company specializing in information technology. Inspur K-UX 2.0 and 3.0 for x86-64 were officially certified as UNIX systems by The Open Group.

**Comment by AMDmi3** [comment]
Repository URLs?
