### ISSUE TITLE
Handling of plus sign (+) for deb based distros

### ISSUE THREAD

**Issue by samueloph** [repology/repology-updater#966]
Hello,

First of all, thanks for working on repology, it's a great tool and I use it daily.

This request is coming in after I noticed some packages that were being marked as outdated:
https://repology.org/projects/?maintainer=samueloph%40debian.org&inrepo=debian_unstable&outdated=1

Looking at one of these packages specifically, we can have an idea on how many distros this would affect: Debian, Devuan, Kali, Parrot, PureOs, Raspbian, Ubuntu... (most likely all deb based ones).

The problem is that versions that ends with `+something` seems to be considered as lower than its preceding number by repology's rules. Eg.: `4.0 > 4.0+git20193012`.

It seems like a similar case that you described in https://github.com/repology/repology-rules/issues/22#issuecomment-384680775

The main point is that the ordering of versions for dpkg is:
`1.0~something < 1.0 < 1.0+something`, this means that when the version contains the plus sign, everything after it can be dropped.

You can test these things with the command:
```
dpkg --compare-versions 1.0 gt 1.0+something
echo $?
```

The biggest usecase for having the plus sign is when a git snapshot is packaged, so the last version release is used as the main version and the snapshot timestamp is added, eg: last release version was 1.0 in january, the packaged version is a git snapshot of december, so the version would look like `1.0+git20191201`. 

This being said, it's always possible that the maintainer used the wrong prefix, they could have used `+` for an alpha/beta/rc release or `~` for a git snapshot. I believe this cases are hard to catch and maybe replogogy shouldn't even try, as that's a maintainer's mistake. 

There are some other edge cases like `~dfsg` (and some other small variations) that ideally should be ignored or `2.5+really2.4` which is a way of avoiding the use of epoch when a downgrade is needed, not common but it happens. But I understand these are moving targets and not fun to deal with.

If you have time to point me to it, I would like to also understand how the tilt `~` is currently being treated, but this issue is only about the plus sing.

PS.: For simplicity, I ignored the debian revision part of the versions (everything after the last hyphen `-`), so when I say version `1.0~something` that is actually `1.0~something-1`

Once again thanks for working on repology :)

**Comment by AMDmi3** [comment]
(moved this issue to the right repository)

I'm well aware of how Debian version comparison works. The problem though is that Debian rules do not apply here as we compare versions from a lot of repository realms, so we basically have to a) convert Debian versions to something at least nominally comparable to official release versions (e.g. pre-release < release < post-release), and b) mark anything which doesn't look like real versions as ignored. This way post-release snapshots would be ignored, and pre-releases would be outdated by corresponding upstream releases (and ignored as well if there's no such release yet).

As you can see this is not yet working as intended. In fact, I have WIP code which tries to extract as much useful information from suffixes as possible, however it kinda have stalled - it became ugly mess of heuristics, it needs to be rechecked against the list of versions after each change, and I still have no clear notion of how much it should try to extract.

Well, probably we should go the straightforward way, leaving suffixes intact, ensuring correct order and ignoring them all.

Related #345 #811 #851

**Comment by AMDmi3** [comment]
NB: for full control on ordering without residing to version modification (e.g. adding `pre`/`post` keywords) we may need extra features from libversion (see repology/libversion#24).

**Comment by AMDmi3** [comment]
> Well, probably we should go the straightforward way, leaving suffixes intact, ensuring correct order and ignoring them all.

NB2: ...and in future this could be refined by normalizing the version, as in cutting meaningful parts like `alphaN` from any part of the suffix and appending them to the version.

**Comment by AMDmi3** [comment]
Debian version handling was improved in #1176.
