### ISSUE TITLE
Reenable Rosa 2019.1 when its ready

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#970]
Rosa is switching to rpm4 in 2019.1, which includes switch from urpmi metadata (info.xml) to standard `repodata` format. The new metadata is currently partially available:

```sh
for a in contrib main non-free restricted; do
    for b in release testing updates; do
        echo -n "$a/$b "
        curl --silent http://abf-downloads.rosalinux.ru/rosa2019.1/repository/SRPMS/$a/$b/ | grep -c repodata/
    done
done
```

```
contrib/release 1
contrib/testing 0
contrib/updates 0
main/release 1
main/testing 0
main/updates 0
non-free/release 0
non-free/testing 0
non-free/updates 0
restricted/release 0
restricted/testing 0
restricted/updates 0
```

I suspect that `testing` and `updates` subrepositories will remain empty for some time, so as soon as repodata is available for `non-free` and `restricted` we can switch `rosa_2019_1` to RepodataFetcher/RepodataParser and reenable it.

@mikhailnov does this look correct?

**Comment by mikhailnov** [comment]
Probably yes, I've asked ABF developers to answer more exactly

**Comment by mikhailnov** [comment]
Publisher has been fixed (https://github.com/OpenMandrivaSoftware/rosa-publish-worker/commit/5f99e0ab201cd4b6eb67d75e80922b2c6b14ac6c) and metadata has been generated:

```
contrib/release 1
contrib/testing 0
contrib/updates 0
main/release 1
main/testing 0
main/updates 0
non-free/release 1
non-free/testing 0
non-free/updates 0
restricted/release 1
restricted/testing 0
restricted/updates 0
```

> I suspect that testing and updates subrepositories will remain empty for some time

Yes, until platform is "released", only `release` subrepos will be not empty.

**Comment by AMDmi3** [comment]
New metadata contains 12k packages versus 22k from info.xml, is this expected? For instance,
```
-2048-qt
-2mandvd
-3proxy
-4kstogram
-4pane
-4stattack
-4ti2
-7kaa
-7kaa-music
-9base
-a-a-p
-a2jmidid
```
In fact this seems right as there are no corresponding .src.rpm's. There are binary packages though, but with 2016.1 disttag.
