### ISSUE TITLE
Handling non-numbers during version comparison

### ISSUE THREAD

**Issue by mikhailnov** [repology/repology-updater#978]
Version comparison in Repology differs from how package managers do it.
https://repology.org/projects/?search=libressl - here Repology web UI thinks that version "3.0.2.git20191207" is older than "3.0.2", but, as far as I know, most package managers will think that "3.0.2.git20191207" is higher than "3.0.2", despite that the last part starts with not a number.

In reality "3.0.2.git20191207" in this case means a cvs snapshot for the date 20191207 after the release 3.0.2 but before any other release (it is not any how standartized in most distros, git date ot commit hash may be in version or release in different forms).

P.S. See also http://wiki.rosalab.ru/ru/index.php/Perl_policy#Versioning for an example how handling of comparing versions may be different

**Comment by AMDmi3** [comment]
> as far as I know, most package managers will think that "3.0.2.git20191207" is higher than "3.0.2"

In fact it is unspecified for most package managers, and may vary depending on whether there are separators before and which separators are used if they have special meaning (such as `~` in Debian). Most RPM distros even move snapshot part into (unspecified position in) `Release:` field, leaving non-existing "next" version in `Version:`.

In Repology, ambiguous comparisons are resolved in a way that does not affect genuine versions, e.g. does not make official releases outdated by snapshots or fake/incorrect versions.

Correct ordering of snapshots is thus not possible without repositories conveying additional information and/or strictly sticking to a documented version format for which a rule may be created (such as Gentoo with their `_pNNN` scheme). I don't think something like that exists for Rosa, looking at the following samples:

```
       version       |      effname      
---------------------+-------------------
 0.1.git84a4013f96e0 | go:net
 0.4.gitf394c3       | wsdd
 0.9.6.1git20120725  | php:eaccelerator
 1.0.3.20171230git   | python:whiteboard
 3.0.2.git20191207   | libressl
```

Notably, even if snapshots are ordered correctly wrt official releases, there's not much we can do with them other than ignore snapshots newer than the latest release and outdate snapshots older than the latest release. That is, comparison between snapshots would be impossible or pointless in most cases.

See #345 for thoughts on a unified snapshot format, #966 for somewhat similar issue related to Debian, also #920 and #801 for other snapshot related ideas.
