### ISSUE TITLE
antiX repos out of date

### ISSUE THREAD

**Issue by anticapitalista** [repology/repology-updater#983]
antiX-16 and and antiX-17 repo info is out of date eg we have palemoon 28.8 in all repos.
thanks
anticapitalista - antiX dev.

**Comment by AMDmi3** [comment]
```
% curl --silent http://ftp.cc.uoc.gr/mirrors/linux/mx/antix/stretch/dists/stretch/main/source/Sources.gz | gunzip | grep -A5 'Package: palemoon' | grep Version
Version: 28.5.2+repack-1~mx17+2
```

Or is this a bad mirror?

**Comment by anticapitalista** [comment]
If you look in the repo folder you will see Palemoon 28.8 (not sure why the sources files didn't mirror over).

https://ftp.cc.uoc.gr/mirrors/linux/mx/antix/stretch/pool/main/p/palemoon/

I'll let you know when the sources files get mirrored.

**Comment by AMDmi3** [comment]
It's the same on master, no?

```
% curl --silent http://repo.antixlinux.com/stretch/dists/stretch/main/source/Sources.gz | gunzip | grep -A5 'Package: palemoon' | grep Version 
Version: 28.5.2+repack-1~mx17+2
```

**Comment by anticapitalista** [comment]
The problem seems to be caused by the fact that there are no .orig.xx files in some of the repos. I'll check with our repo dev.

**Comment by AMDmi3** [comment]
Master seem to list 28.8.1 for palemoon now, mirror still lagging.
Would it be OK to switch Repology to master for faster updates?

**Comment by anticapitalista** [comment]
This mirror might be better (our master repo is 'sensitive').

https://mirror.math.princeton.edu/pub/mxlinux/antix/

Many thanks
