### ISSUE TITLE
Multiple packages build from a singe source package are ignored for openSUSE 

### ISSUE THREAD

**Issue by StefanBruens** [repology/repology-updater#986]
openSUSE builds the aspell-* dictionaries from a single source package, "aspell-dictionaries", but these binary packages (aspell-af, aspell-ar, ...) are not picked up by repology. Only outlier is aspell-en, where source and binary package names match.

**Comment by AMDmi3** [comment]
Repology only parses source packages, so this works as expected.

**Comment by AMDmi3** [comment]
> In future it's likely that binary packages will be added as well.

Although that won't help here - all `aspell-*` subpackages will still be tied to `aspell-dictionaries` project, and there's no way to split them as source package name is used as a basis for project name. Binary package names cannot be used too as they contain prefixes and suffixes which break project matching. IMO it's a packaging problem, when unrelated projects are for some reason united in a single package. This has other drawbacks, such as inability to update them independently.
