### ISSUE TITLE
Please add Clear Linux repositiories

### ISSUE THREAD

**Issue by jurobystricky** [repology/repology-updater#989]
I am following the advice from https://repology.org/addrepo "add a repository the easy way".  I hope I did not misconstrue "the easy way", my interpretation was to simply ask via opening a ticket.
So here it goes: Please add the Clear Linux repository.
The home page for Clear Linux for IA is here: https://clearlinux.org/
The Github repos (6600+ packages)  live here: https://github.com/clearlinux-pkgs
(these repositories contain RPM spec files)
RPM packages: https://cdn.download.clearlinux.org/current/x86_64/os/Packages/ 
The corresponding SRPMs can be found here:
https://cdn.download.clearlinux.org/current/source/SRPMS/

Thanks, if I missed something, please let me know.

**Comment by AMDmi3** [comment]
- This is "current" repository, are there other repositories (e.g. versioned releases or branches) or may such repositories appear in future?
- Does if follow naming rules or borrow packages from some other RPM distros like centos/fedora/mageia/openmandriva/... or is in completely original?

**Comment by AMDmi3** [comment]
The show stoppers are:
- it doesn't provide any way to distinguish python modules from other packages (like how it's done for Perl modules with `perl-` prefix)
- it doesn't provide project homepages. For some reason it uses source download location as URL, which doesn't serve its purpose and is incorrect
- it provides garbage as summaries ("No detailed summary available")

**Comment by jurobystricky** [comment]
Thanks for your quick feedback. I was not aware there were hard coded constraints for package identification, such as package home URL and the content of the "Summary" line.
I will try to address some of your concerns/questions:

- Clear Linux is a "rolling" distro. It is 100% open source based. Packages and package versions for previous releases can be seen here:
https://download.clearlinux.org/releases/
Most of the packages (possibly all) are quite common in other Linux distributions.

- The package naming scheme is fairly consistent, package name is normally identical to the source code repository.
For example, a repository  https://github.com/xxx/yyy would be used to create packages 
yyy-pkgcontent-version.x86_64.RPM, where pkgcontent can by "bin", "dev", "python3"  etc.  So python packages are identifiable. Version scheme is identical to other distros RPM packages.

- The link to the source code repository should be enough to uniquely identify the package, even if the package naming scheme is different from other distribution naming schemes and the URL for package home page is missing.

- The individual .spec files may be edited manually, in which case the "Summary" should contain a short description of the package. However, if the spec file was generated by build tools, the "Summary" line is "machine created" from the information available and be unreliable.

**Comment by AMDmi3** [comment]
>  I was not aware there were hard coded constraints for package identification, such as package home URL

These are mentioned on https://repology.org/addrepo btw.

> and the content of the "Summary" line.

This one is in fact optional and may be ignored if its not reliable.

> Clear Linux is a "rolling" distro. It is 100% open source based. Packages and package versions for previous releases can be seen here:

I was asking in order to pick a future proof internal name for the repo. As far as I can see, it's safe to just use `clear` as there's basically a single rolling repo only.

> The package naming scheme is fairly consistent, package name is normally identical to the source code repository.
> For example, a repository https://github.com/xxx/yyy would be used to create packages yyy-pkgcontent-version.x86_64.RPM, where pkgcontent can by "bin", "dev", "python3" etc. So python packages are identifiable. Version scheme is identical to other distros RPM packages.

That doesn't seem to be correct. For instance, there is `requests` package in both source and x86_64 repositories - there's neither prefix nor other property which could be used to classify it as python package.

Autospec docs also mention thay only perl, r and rubygems packages are prefixed.

> The link to the source code repository should be enough to uniquely identify the package, even if the package naming scheme is different from other distribution naming schemes and the URL for package home page is missing.

Well this may be true in many cases, but I've seen at least some mirrored files, and mirror URLs may not contain enough information to distinguish packages. Also I don't like the fact that I'll have to add a hack to use homepage url as download url.

Anyway the main show stopper is unprefixed python packages.

**Comment by jurobystricky** [comment]
Once again, thanks for your quick reply. To my defense, the page
https://repology.org/addrepo says:
_...URL information (project homepages or download locations, or better both) ..._
so I read it as home page URL is not compulsory. Unfortunately, home page URL info is not available, so there is not much one can do about it.

The Clear Linux python packages generally fall into two categories. There are pure python packages, those actually are prefixed with "python-" or "python3-". For example, searching for "python-" in https://download.clearlinux.org/releases/32130/clear/x86_64/os/Packages/ says more than 1000 found.
Then there are packages that also contain some python context, those are without python prefix, but "python" is part of the package name. 

Regarding mirrored repositories: I would imagine that the actual name of the tarball would be the same regardless of the tarball URL being mirrored or not. And IMHO mirrored URL should be viewed as less reliable. Having said that, I admit I don't know much about repology internals and there probably are legitimate concerns.

As for python issue being the main showstopper: what is the worst case scenario? Would some packages be simply not listed or are there any other dire ramifications I am not aware of?

**Comment by AMDmi3** [comment]
> There are pure python packages, those actually are prefixed with "python-" or "python3-". For example, searching for "python-" in https://download.clearlinux.org/releases/32130/clear/x86_64/os/Packages/ says more than 1000 found.

These are only present in binary packages (while Repology only uses either source repositories, or source package names for binary packages) and for each suffixed package there it still one without suffix, which pose the problem:

```
requests-2.22.0-80.x86_64.rpm                            17-Jan-2020 21:52          6372
requests-python3-2.22.0-80.x86_64.rpm                    17-Jan-2020 21:52        118253
requests-python-2.22.0-80.x86_64.rpm                     17-Jan-2020 21:52          6300
```

> Regarding mirrored repositories: I would imagine that the actual name of the tarball would be the same regardless of the tarball URL being mirrored or not

The point of requiring homepage URLs is in using their parts other than file names - that is, hostnames primarily (as filenames for similarly names packages are still very likely to be indistinguishable). Mirrors obviously break the whole idea.

> As for python issue being the main showstopper: what is the worst case scenario? Would some packages be simply not listed or are there any other dire ramifications I am not aware of?

All packages would be listed, however either
- they would be listed as duplicated `pkgname` project present only in Clear linux, separate from `python:pkgname` (present in all other repos) which python modules are intended to be listed as. Duplication pollutes project lists, invalidates statistics and hinders new version reporting.
- they would end up incorrectly merged with an unrelated project with the same name, reporting incorrect versions as latest  

Either way, it would degrade Repology quality and/or require extra effort to maintain via the ruleset, which I cannot afford.

**Comment by jurobystricky** [comment]
I am closing this issue as it seems like there is no simple way to add Clear Linux packages to repology.
Thank you for your time and explantion.
