### ISSUE TITLE
homebrew_tap_brewsci_bio data out of date

### ISSUE THREAD

**Issue by sjackman** [repology/repology-updater#990]
Hi. The data for `homebrew_tap_brewsci_bio` appears to be out of date. The data was updated a week ago on 2020-01-13 in commit https://github.com/brewsci/homebrew-bio/commit/2b2f33ae3e5ff38f4186954f35fcd9caa2ede709. https://github.com/brewsci/homebrew-bio/blob/gh-pages/api/formula.json

For example `beast2` was updated from version 2.5.2 to version 2.6.1, but Repology is still showing version 2.5.2. https://repology.org/projects/?inrepo=homebrew_tap_brewsci_bio&outdated=1

How often is the data ingested?

**Comment by AMDmi3** [comment]
Hourly on average. In this case it seems that it's not updated because of incorrect last-modified handling on your side:
https://repology.org/log/1932356

**Comment by sjackman** [comment]
```
2020-01-20 14:34:48     fetching https://brewsci.github.io/homebrew-bio/api/formula.json
2020-01-20 14:34:48     using if-modified-since: Tue, 01 Oct 2019 00:57:35 GMT
2020-01-20 14:34:48     got 403 not modified
```
That file is being served up by GitHub Pages. Do you know this `last-modified` feature to work with GitHub Pages in general? I'm not sure what I could have done to mess it up.

**Comment by AMDmi3** [comment]
No idea. You should probably ask GH support why `last-modified` time isn't updated properly.

**Comment by sjackman** [comment]
Ah, thanks for helping troubleshoot, Dmitry. I've manually triggered a rebuild of the GitHub Pages. It seems like there's a bug in GitHub Actions that pushing to the `gh-pages` branch form an action doesn't automatically trigger a rebuild of pages, as happens when you do it outside of GitHub Actions. I'll look into it.
