### ISSUE TITLE
Add support for showing maintainers to KISS repositories

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology-updater#992]
KISS uses Git to store the maintainer for each package. More specifically, the last (most recent) person to write a commit to a package's files is the maintainer (as they are solely responsible for the package).

For repology, this could be a simple check of the `Author:` of `git log /path/to/pkg/version`.

Here's an example:

```sh
-> git log -1 --format="tformat:%an = %ae" /path/to/pkg/version
Dylan Araps = dylan.araps@gmail.com
```

Thanks

**Comment by AMDmi3** [comment]
@cemkeylan is this also true for Carbs?

**Comment by cemkeylan** [comment]
Yes, it is.

**Comment by dylanaraps** [comment]
Thanks a bunch for doing this. :+1:

**Comment by AMDmi3** [comment]
:ok_hand: 

The right way to do it right now would be in fact to implement per-repository feed (repology/repology-webapp#47) similar to current per-maintainer+repository feeds, but I suspect that KISS would have more maintainers in future and global repository feed would become less useful.

**Comment by dylanaraps** [comment]
Not sure if you saw my message edit in the other thread. The maintainers list for the community repository lists me as the maintainer for all packages instead of the real maintainers. Thanks again :+1:

**Comment by AMDmi3** [comment]
See #994
