### ISSUE TITLE
Allow unlimited depth checkouts for git fetcher

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#994]
Needed for repositories (such as KISS) for which some information need to be extracted from git history.

**Comment by dylanaraps** [comment]
Wonderful. Many thanks once again. :+1:

**Comment by AMDmi3** [comment]
Note that this has unfortunate consequences, such as:
1. Requirement for the tree to be fetched specifically with git (while otherwise we could technically use a tarball snapshot)
2. More wasted space on the server for storing whole repository history
3. Slower parsing and more load during it as it needs to call external process for each package, and the process needs to reread (reparse, probably redecompress) the same data
4. Package may jump between maintainers because of unrelated (such as housekeeping) commits. For Repology, this would lead to feed cluttering with "package XXX is now maintained by YYY/package XXX is no longer maintainer by YYY".
5. Same for pull requests, e.g. drive by commits by other people who are not interested in full-fledged maintainership.

I'm not bothered by 1 but this may change in future; 2-3 are OK as long as repositories are small; 4 should probably not be a problem as long as we only look at `version` files, which should only change with real updates. 5 may pose a problem as soon it happens that two people are interested in a same port.

Summarizing, I'm OK with it now, but in future it may either be that a repository-wide feed as mentioned #992 would work better for KISS/Carbs, or you'll embrace a concept of explicit maintainership.

**Comment by dylanaraps** [comment]
I'm fine with per-repository feeds if it makes things easier on your end. I don't want you to go out of your way for KISS as you're already providing an immensely valuable service to me and the user's of KISS. 

Feel free to revert the maintainer changes and (whenever you're ready, there's no rush) move KISS to per-repository feeds. I don't want to add any extra (and unneeded) burden to the free service you provide. 

Thanks again and apologies for the rocky back and forth for this feature. :+1:

**Comment by AMDmi3** [comment]
As said, for now this is OK. For sure it won't be reverted until per-repo feeds are available.

**Comment by dylanaraps** [comment]
I have published a maintainers list available here: https://getkiss.org/authors

- This list is updated whenever a commit is made to both repositories (kisslinux/repo and kisslinux/community).
- The maintainer listed is the most recent person to modify the `version` file of a package. The only time this happens is when a package is updated by its maintainer.
- Tracking the version file also prevents false-positives in the rare case when tiny changes are made to the other package's files but `version` stays untouched.
- There are three fields which are separated by the `<TAB>` character.
- The first field is `repo_name/pkg_name`.
- The second field is the maintainer's name.
- The third field is the maintainer's email.

Please let me know if any changes need to be made to the format of this file. :+1:

**Comment by AMDmi3** [comment]
Nice, but switching to this now would complicate stuff even more. However if can act as a fallback for the case when parsing git history becomes problematic.

**Comment by dylanaraps** [comment]
Sounds good. 

Community still seems to be broken however. It still shows me as the sole maintainer of every package. 

- https://repology.org/repository/kiss_community ("There are 1 maintainer(s) for this repository")
- https://repology.org/maintainer/dylan.araps%40gmail.com

**Comment by AMDmi3** [comment]
> Community still seems to be broken however. It still shows me as the sole maintainer of every package.

I haven't deployed it yet. Should be fixed in about an hour.

> Edit: Also, if you'd like I can populate this file with the entire repository's information. ie, extending each line to show primary source ("homepage") and the package's version. You can then ditch git clones altogether for KISS.

This is great, however I'd avoid switching to it unless there are other options. The preference for Repology is to use the original source if possible (that is, if it's parsable, which is thankfully the case for KISS) - this allows to minimize update lag and get all the possible data (in future we may support dependency and patch tracking). Also I'm not sure that this format will be adopted by other KISS infrastructure users, e.g. Carbs, which means that we'll need two different parsers. As said, the only problem with using raw KISS repo is the way of maintainer parsing, and still we can live with that for now.

**Comment by cemkeylan** [comment]
Hey Dmitry, I will be doing the same. I will push the package list to https://carbslinux.org/db around 12PM UTC. I would do it now, but my computer is not around at the moment. This would solve the issue for not being able to switch.

**Comment by cemkeylan** [comment]
I have published it.

**Comment by cemkeylan** [comment]
Since the Github repository is a mirror of the original repository at <git://git.carbslinux.org/repository>, it has delayed updates. The db file is generated via post-receive so it has no delays.

**Comment by dylanaraps** [comment]
Fixed link: https://carbslinux.org/packages/db
